#define _XOPEN_SOURCE
#include <stdio.h>
#include <locale.h>
#include <wchar.h>

void print_wcwidth(wchar_t c, char *str)
{
  printf("wcwidth('[%lc]') == %d, codepoint [%x], %s\n", c, wcwidth(c), c, str);
}
int main()
{
  setlocale(LC_CTYPE, "");
  print_wcwidth(0xa9, "COPYRIGHT SIGN");
  print_wcwidth(0xae, "REGISTERED SIGN");
  print_wcwidth(0x203c, "DOUBLE EXCLAMATION MARK");
  print_wcwidth(0x2049, "EXCLAMATION QUESTION MARK");
  print_wcwidth(0x2122, "TRADE MARK SIGN");
  print_wcwidth(0x2139, "INFORMATION SOURCE");
  print_wcwidth(0x2194, "LEFT RIGHT ARROW");
  print_wcwidth(0x2195, "UP DOWN ARROW");
  print_wcwidth(0x2196, "NORTH WEST ARROW");
  print_wcwidth(0x2197, "NORTH EAST ARROW");
  print_wcwidth(0x2198, "SOUTH EAST ARROW");
  print_wcwidth(0x2199, "SOUTH WEST ARROW");
  print_wcwidth(0x21a9, "LEFTWARDS ARROW WITH HOOK");
  print_wcwidth(0x21aa, "RIGHTWARDS ARROW WITH HOOK");
  print_wcwidth(0x231a, "WATCH");
  print_wcwidth(0x231b, "HOURGLASS");
  print_wcwidth(0x2328, "KEYBOARD");
  print_wcwidth(0x23cf, "EJECT SYMBOL");
  print_wcwidth(0x23e9, "BLACK RIGHT-POINTING DOUBLE TRIANGLE");
  print_wcwidth(0x23ea, "BLACK LEFT-POINTING DOUBLE TRIANGLE");
  print_wcwidth(0x23eb, "BLACK UP-POINTING DOUBLE TRIANGLE");
  print_wcwidth(0x23ec, "BLACK DOWN-POINTING DOUBLE TRIANGLE");
  print_wcwidth(0x23ed, "BLACK RIGHT-POINTING DOUBLE TRIANGLE WITH VERTICAL BAR");
  print_wcwidth(0x23ee, "BLACK LEFT-POINTING DOUBLE TRIANGLE WITH VERTICAL BAR");
  print_wcwidth(0x23ef, "BLACK RIGHT-POINTING TRIANGLE WITH DOUBLE VERTICAL BAR");
  print_wcwidth(0x23f0, "ALARM CLOCK");
  print_wcwidth(0x23f1, "STOPWATCH");
  print_wcwidth(0x23f2, "TIMER CLOCK");
  print_wcwidth(0x23f3, "HOURGLASS WITH FLOWING SAND");
  print_wcwidth(0x23f8, "DOUBLE VERTICAL BAR");
  print_wcwidth(0x23f9, "BLACK SQUARE FOR STOP");
  print_wcwidth(0x23fa, "BLACK CIRCLE FOR RECORD");
  print_wcwidth(0x24c2, "CIRCLED LATIN CAPITAL LETTER M");
  print_wcwidth(0x25aa, "BLACK SMALL SQUARE");
  print_wcwidth(0x25ab, "WHITE SMALL SQUARE");
  print_wcwidth(0x25b6, "BLACK RIGHT-POINTING TRIANGLE");
  print_wcwidth(0x25c0, "BLACK LEFT-POINTING TRIANGLE");
  print_wcwidth(0x25fb, "WHITE MEDIUM SQUARE");
  print_wcwidth(0x25fc, "BLACK MEDIUM SQUARE");
  print_wcwidth(0x25fd, "WHITE MEDIUM SMALL SQUARE");
  print_wcwidth(0x25fe, "BLACK MEDIUM SMALL SQUARE");
  print_wcwidth(0x2600, "BLACK SUN WITH RAYS");
  print_wcwidth(0x2601, "CLOUD");
  print_wcwidth(0x2602, "UMBRELLA");
  print_wcwidth(0x2603, "SNOWMAN");
  print_wcwidth(0x2604, "COMET");
  print_wcwidth(0x260e, "BLACK TELEPHONE");
  print_wcwidth(0x2611, "BALLOT BOX WITH CHECK");
  print_wcwidth(0x2614, "UMBRELLA WITH RAIN DROPS");
  print_wcwidth(0x2615, "HOT BEVERAGE");
  print_wcwidth(0x2618, "SHAMROCK");
  print_wcwidth(0x261d, "WHITE UP POINTING INDEX");
  print_wcwidth(0x2620, "SKULL AND CROSSBONES");
  print_wcwidth(0x2622, "RADIOACTIVE SIGN");
  print_wcwidth(0x2623, "BIOHAZARD SIGN");
  print_wcwidth(0x2626, "ORTHODOX CROSS");
  print_wcwidth(0x262a, "STAR AND CRESCENT");
  print_wcwidth(0x262e, "PEACE SYMBOL");
  print_wcwidth(0x262f, "YIN YANG");
  print_wcwidth(0x2638, "WHEEL OF DHARMA");
  print_wcwidth(0x2639, "WHITE FROWNING FACE");
  print_wcwidth(0x263a, "WHITE SMILING FACE");
  print_wcwidth(0x2648, "ARIES");
  print_wcwidth(0x2649, "TAURUS");
  print_wcwidth(0x264a, "GEMINI");
  print_wcwidth(0x264b, "CANCER");
  print_wcwidth(0x264c, "LEO");
  print_wcwidth(0x264d, "VIRGO");
  print_wcwidth(0x264e, "LIBRA");
  print_wcwidth(0x264f, "SCORPIUS");
  print_wcwidth(0x2650, "SAGITTARIUS");
  print_wcwidth(0x2651, "CAPRICORN");
  print_wcwidth(0x2652, "AQUARIUS");
  print_wcwidth(0x2653, "PISCES");
  print_wcwidth(0x2660, "BLACK SPADE SUIT");
  print_wcwidth(0x2663, "BLACK CLUB SUIT");
  print_wcwidth(0x2665, "BLACK HEART SUIT");
  print_wcwidth(0x2666, "BLACK DIAMOND SUIT");
  print_wcwidth(0x2668, "HOT SPRINGS");
  print_wcwidth(0x267b, "BLACK UNIVERSAL RECYCLING SYMBOL");
  print_wcwidth(0x267f, "WHEELCHAIR SYMBOL");
  print_wcwidth(0x2692, "HAMMER AND PICK");
  print_wcwidth(0x2693, "ANCHOR");
  print_wcwidth(0x2694, "CROSSED SWORDS");
  print_wcwidth(0x2696, "SCALES");
  print_wcwidth(0x2697, "ALEMBIC");
  print_wcwidth(0x2699, "GEAR");
  print_wcwidth(0x269b, "ATOM SYMBOL");
  print_wcwidth(0x269c, "FLEUR-DE-LIS");
  print_wcwidth(0x26a0, "WARNING SIGN");
  print_wcwidth(0x26a1, "HIGH VOLTAGE SIGN");
  print_wcwidth(0x26aa, "MEDIUM WHITE CIRCLE");
  print_wcwidth(0x26ab, "MEDIUM BLACK CIRCLE");
  print_wcwidth(0x26b0, "COFFIN");
  print_wcwidth(0x26b1, "FUNERAL URN");
  print_wcwidth(0x26bd, "SOCCER BALL");
  print_wcwidth(0x26be, "BASEBALL");
  print_wcwidth(0x26c4, "SNOWMAN WITHOUT SNOW");
  print_wcwidth(0x26c5, "SUN BEHIND CLOUD");
  print_wcwidth(0x26c8, "THUNDER CLOUD AND RAIN");
  print_wcwidth(0x26ce, "OPHIUCHUS");
  print_wcwidth(0x26cf, "PICK");
  print_wcwidth(0x26d1, "HELMET WITH WHITE CROSS");
  print_wcwidth(0x26d3, "CHAINS");
  print_wcwidth(0x26d4, "NO ENTRY");
  print_wcwidth(0x26e9, "SHINTO SHRINE");
  print_wcwidth(0x26ea, "CHURCH");
  print_wcwidth(0x26f0, "MOUNTAIN");
  print_wcwidth(0x26f1, "UMBRELLA ON GROUND");
  print_wcwidth(0x26f2, "FOUNTAIN");
  print_wcwidth(0x26f3, "FLAG IN HOLE");
  print_wcwidth(0x26f4, "FERRY");
  print_wcwidth(0x26f5, "SAILBOAT");
  print_wcwidth(0x26f7, "SKIER");
  print_wcwidth(0x26f8, "ICE SKATE");
  print_wcwidth(0x26f9, "PERSON WITH BALL");
  print_wcwidth(0x26fa, "TENT");
  print_wcwidth(0x26fd, "FUEL PUMP");
  print_wcwidth(0x2702, "BLACK SCISSORS");
  print_wcwidth(0x2705, "WHITE HEAVY CHECK MARK");
  print_wcwidth(0x2708, "AIRPLANE");
  print_wcwidth(0x2709, "ENVELOPE");
  print_wcwidth(0x270a, "RAISED FIST");
  print_wcwidth(0x270b, "RAISED HAND");
  print_wcwidth(0x270c, "VICTORY HAND");
  print_wcwidth(0x270d, "WRITING HAND");
  print_wcwidth(0x270f, "PENCIL");
  print_wcwidth(0x2712, "BLACK NIB");
  print_wcwidth(0x2714, "HEAVY CHECK MARK");
  print_wcwidth(0x2716, "HEAVY MULTIPLICATION X");
  print_wcwidth(0x271d, "LATIN CROSS");
  print_wcwidth(0x2721, "STAR OF DAVID");
  print_wcwidth(0x2728, "SPARKLES");
  print_wcwidth(0x2733, "EIGHT SPOKED ASTERISK");
  print_wcwidth(0x2734, "EIGHT POINTED BLACK STAR");
  print_wcwidth(0x2744, "SNOWFLAKE");
  print_wcwidth(0x2747, "SPARKLE");
  print_wcwidth(0x274c, "CROSS MARK");
  print_wcwidth(0x274e, "NEGATIVE SQUARED CROSS MARK");
  print_wcwidth(0x2753, "BLACK QUESTION MARK ORNAMENT");
  print_wcwidth(0x2754, "WHITE QUESTION MARK ORNAMENT");
  print_wcwidth(0x2755, "WHITE EXCLAMATION MARK ORNAMENT");
  print_wcwidth(0x2757, "HEAVY EXCLAMATION MARK SYMBOL");
  print_wcwidth(0x2763, "HEAVY HEART EXCLAMATION MARK ORNAMENT");
  print_wcwidth(0x2764, "HEAVY BLACK HEART");
  print_wcwidth(0x2795, "HEAVY PLUS SIGN");
  print_wcwidth(0x2796, "HEAVY MINUS SIGN");
  print_wcwidth(0x2797, "HEAVY DIVISION SIGN");
  print_wcwidth(0x27a1, "BLACK RIGHTWARDS ARROW");
  print_wcwidth(0x27b0, "CURLY LOOP");
  print_wcwidth(0x27bf, "DOUBLE CURLY LOOP");
  print_wcwidth(0x2934, "ARROW POINTING RIGHTWARDS THEN CURVING UPWARDS");
  print_wcwidth(0x2935, "ARROW POINTING RIGHTWARDS THEN CURVING DOWNWARDS");
  print_wcwidth(0x2b05, "LEFTWARDS BLACK ARROW");
  print_wcwidth(0x2b06, "UPWARDS BLACK ARROW");
  print_wcwidth(0x2b07, "DOWNWARDS BLACK ARROW");
  print_wcwidth(0x2b1b, "BLACK LARGE SQUARE");
  print_wcwidth(0x2b1c, "WHITE LARGE SQUARE");
  print_wcwidth(0x2b50, "WHITE MEDIUM STAR");
  print_wcwidth(0x2b55, "HEAVY LARGE CIRCLE");
  print_wcwidth(0x3030, "WAVY DASH");
  print_wcwidth(0x303d, "PART ALTERNATION MARK");
  print_wcwidth(0x3297, "CIRCLED IDEOGRAPH CONGRATULATION");
  print_wcwidth(0x3299, "CIRCLED IDEOGRAPH SECRET");
  print_wcwidth(0x1f004, "MAHJONG TILE RED DRAGON");
  print_wcwidth(0x1f0cf, "PLAYING CARD BLACK JOKER");
  print_wcwidth(0x1f170, "NEGATIVE SQUARED LATIN CAPITAL LETTER A");
  print_wcwidth(0x1f171, "NEGATIVE SQUARED LATIN CAPITAL LETTER B");
  print_wcwidth(0x1f17e, "NEGATIVE SQUARED LATIN CAPITAL LETTER O");
  print_wcwidth(0x1f17f, "NEGATIVE SQUARED LATIN CAPITAL LETTER P");
  print_wcwidth(0x1f18e, "NEGATIVE SQUARED AB");
  print_wcwidth(0x1f191, "SQUARED CL");
  print_wcwidth(0x1f192, "SQUARED COOL");
  print_wcwidth(0x1f193, "SQUARED FREE");
  print_wcwidth(0x1f194, "SQUARED ID");
  print_wcwidth(0x1f195, "SQUARED NEW");
  print_wcwidth(0x1f196, "SQUARED NG");
  print_wcwidth(0x1f197, "SQUARED OK");
  print_wcwidth(0x1f198, "SQUARED SOS");
  print_wcwidth(0x1f199, "SQUARED UP WITH EXCLAMATION MARK");
  print_wcwidth(0x1f19a, "SQUARED VS");
  print_wcwidth(0x1f201, "SQUARED KATAKANA KOKO");
  print_wcwidth(0x1f202, "SQUARED KATAKANA SA");
  print_wcwidth(0x1f21a, "SQUARED CJK UNIFIED IDEOGRAPH-7121");
  print_wcwidth(0x1f22f, "SQUARED CJK UNIFIED IDEOGRAPH-6307");
  print_wcwidth(0x1f232, "SQUARED CJK UNIFIED IDEOGRAPH-7981");
  print_wcwidth(0x1f233, "SQUARED CJK UNIFIED IDEOGRAPH-7A7A");
  print_wcwidth(0x1f234, "SQUARED CJK UNIFIED IDEOGRAPH-5408");
  print_wcwidth(0x1f235, "SQUARED CJK UNIFIED IDEOGRAPH-6E80");
  print_wcwidth(0x1f236, "SQUARED CJK UNIFIED IDEOGRAPH-6709");
  print_wcwidth(0x1f237, "SQUARED CJK UNIFIED IDEOGRAPH-6708");
  print_wcwidth(0x1f238, "SQUARED CJK UNIFIED IDEOGRAPH-7533");
  print_wcwidth(0x1f239, "SQUARED CJK UNIFIED IDEOGRAPH-5272");
  print_wcwidth(0x1f23a, "SQUARED CJK UNIFIED IDEOGRAPH-55B6");
  print_wcwidth(0x1f250, "CIRCLED IDEOGRAPH ADVANTAGE");
  print_wcwidth(0x1f251, "CIRCLED IDEOGRAPH ACCEPT");
  print_wcwidth(0x1f300, "CYCLONE");
  print_wcwidth(0x1f301, "FOGGY");
  print_wcwidth(0x1f302, "CLOSED UMBRELLA");
  print_wcwidth(0x1f303, "NIGHT WITH STARS");
  print_wcwidth(0x1f304, "SUNRISE OVER MOUNTAINS");
  print_wcwidth(0x1f305, "SUNRISE");
  print_wcwidth(0x1f306, "CITYSCAPE AT DUSK");
  print_wcwidth(0x1f307, "SUNSET OVER BUILDINGS");
  print_wcwidth(0x1f308, "RAINBOW");
  print_wcwidth(0x1f309, "BRIDGE AT NIGHT");
  print_wcwidth(0x1f30a, "WATER WAVE");
  print_wcwidth(0x1f30b, "VOLCANO");
  print_wcwidth(0x1f30c, "MILKY WAY");
  print_wcwidth(0x1f30d, "EARTH GLOBE EUROPE-AFRICA");
  print_wcwidth(0x1f30e, "EARTH GLOBE AMERICAS");
  print_wcwidth(0x1f30f, "EARTH GLOBE ASIA-AUSTRALIA");
  print_wcwidth(0x1f310, "GLOBE WITH MERIDIANS");
  print_wcwidth(0x1f311, "NEW MOON SYMBOL");
  print_wcwidth(0x1f312, "WAXING CRESCENT MOON SYMBOL");
  print_wcwidth(0x1f313, "FIRST QUARTER MOON SYMBOL");
  print_wcwidth(0x1f314, "WAXING GIBBOUS MOON SYMBOL");
  print_wcwidth(0x1f315, "FULL MOON SYMBOL");
  print_wcwidth(0x1f316, "WANING GIBBOUS MOON SYMBOL");
  print_wcwidth(0x1f317, "LAST QUARTER MOON SYMBOL");
  print_wcwidth(0x1f318, "WANING CRESCENT MOON SYMBOL");
  print_wcwidth(0x1f319, "CRESCENT MOON");
  print_wcwidth(0x1f31a, "NEW MOON WITH FACE");
  print_wcwidth(0x1f31b, "FIRST QUARTER MOON WITH FACE");
  print_wcwidth(0x1f31c, "LAST QUARTER MOON WITH FACE");
  print_wcwidth(0x1f31d, "FULL MOON WITH FACE");
  print_wcwidth(0x1f31e, "SUN WITH FACE");
  print_wcwidth(0x1f31f, "GLOWING STAR");
  print_wcwidth(0x1f320, "SHOOTING STAR");
  print_wcwidth(0x1f321, "THERMOMETER");
  print_wcwidth(0x1f324, "WHITE SUN WITH SMALL CLOUD");
  print_wcwidth(0x1f325, "WHITE SUN BEHIND CLOUD");
  print_wcwidth(0x1f326, "WHITE SUN BEHIND CLOUD WITH RAIN");
  print_wcwidth(0x1f327, "CLOUD WITH RAIN");
  print_wcwidth(0x1f328, "CLOUD WITH SNOW");
  print_wcwidth(0x1f329, "CLOUD WITH LIGHTNING");
  print_wcwidth(0x1f32a, "CLOUD WITH TORNADO");
  print_wcwidth(0x1f32b, "FOG");
  print_wcwidth(0x1f32c, "WIND BLOWING FACE");
  print_wcwidth(0x1f32d, "HOT DOG");
  print_wcwidth(0x1f32e, "TACO");
  print_wcwidth(0x1f32f, "BURRITO");
  print_wcwidth(0x1f330, "CHESTNUT");
  print_wcwidth(0x1f331, "SEEDLING");
  print_wcwidth(0x1f332, "EVERGREEN TREE");
  print_wcwidth(0x1f333, "DECIDUOUS TREE");
  print_wcwidth(0x1f334, "PALM TREE");
  print_wcwidth(0x1f335, "CACTUS");
  print_wcwidth(0x1f336, "HOT PEPPER");
  print_wcwidth(0x1f337, "TULIP");
  print_wcwidth(0x1f338, "CHERRY BLOSSOM");
  print_wcwidth(0x1f339, "ROSE");
  print_wcwidth(0x1f33a, "HIBISCUS");
  print_wcwidth(0x1f33b, "SUNFLOWER");
  print_wcwidth(0x1f33c, "BLOSSOM");
  print_wcwidth(0x1f33d, "EAR OF MAIZE");
  print_wcwidth(0x1f33e, "EAR OF RICE");
  print_wcwidth(0x1f33f, "HERB");
  print_wcwidth(0x1f340, "FOUR LEAF CLOVER");
  print_wcwidth(0x1f341, "MAPLE LEAF");
  print_wcwidth(0x1f342, "FALLEN LEAF");
  print_wcwidth(0x1f343, "LEAF FLUTTERING IN WIND");
  print_wcwidth(0x1f344, "MUSHROOM");
  print_wcwidth(0x1f345, "TOMATO");
  print_wcwidth(0x1f346, "AUBERGINE");
  print_wcwidth(0x1f347, "GRAPES");
  print_wcwidth(0x1f348, "MELON");
  print_wcwidth(0x1f349, "WATERMELON");
  print_wcwidth(0x1f34a, "TANGERINE");
  print_wcwidth(0x1f34b, "LEMON");
  print_wcwidth(0x1f34c, "BANANA");
  print_wcwidth(0x1f34d, "PINEAPPLE");
  print_wcwidth(0x1f34e, "RED APPLE");
  print_wcwidth(0x1f34f, "GREEN APPLE");
  print_wcwidth(0x1f350, "PEAR");
  print_wcwidth(0x1f351, "PEACH");
  print_wcwidth(0x1f352, "CHERRIES");
  print_wcwidth(0x1f353, "STRAWBERRY");
  print_wcwidth(0x1f354, "HAMBURGER");
  print_wcwidth(0x1f355, "SLICE OF PIZZA");
  print_wcwidth(0x1f356, "MEAT ON BONE");
  print_wcwidth(0x1f357, "POULTRY LEG");
  print_wcwidth(0x1f358, "RICE CRACKER");
  print_wcwidth(0x1f359, "RICE BALL");
  print_wcwidth(0x1f35a, "COOKED RICE");
  print_wcwidth(0x1f35b, "CURRY AND RICE");
  print_wcwidth(0x1f35c, "STEAMING BOWL");
  print_wcwidth(0x1f35d, "SPAGHETTI");
  print_wcwidth(0x1f35e, "BREAD");
  print_wcwidth(0x1f35f, "FRENCH FRIES");
  print_wcwidth(0x1f360, "ROASTED SWEET POTATO");
  print_wcwidth(0x1f361, "DANGO");
  print_wcwidth(0x1f362, "ODEN");
  print_wcwidth(0x1f363, "SUSHI");
  print_wcwidth(0x1f364, "FRIED SHRIMP");
  print_wcwidth(0x1f365, "FISH CAKE WITH SWIRL DESIGN");
  print_wcwidth(0x1f366, "SOFT ICE CREAM");
  print_wcwidth(0x1f367, "SHAVED ICE");
  print_wcwidth(0x1f368, "ICE CREAM");
  print_wcwidth(0x1f369, "DOUGHNUT");
  print_wcwidth(0x1f36a, "COOKIE");
  print_wcwidth(0x1f36b, "CHOCOLATE BAR");
  print_wcwidth(0x1f36c, "CANDY");
  print_wcwidth(0x1f36d, "LOLLIPOP");
  print_wcwidth(0x1f36e, "CUSTARD");
  print_wcwidth(0x1f36f, "HONEY POT");
  print_wcwidth(0x1f370, "SHORTCAKE");
  print_wcwidth(0x1f371, "BENTO BOX");
  print_wcwidth(0x1f372, "POT OF FOOD");
  print_wcwidth(0x1f373, "COOKING");
  print_wcwidth(0x1f374, "FORK AND KNIFE");
  print_wcwidth(0x1f375, "TEACUP WITHOUT HANDLE");
  print_wcwidth(0x1f376, "SAKE BOTTLE AND CUP");
  print_wcwidth(0x1f377, "WINE GLASS");
  print_wcwidth(0x1f378, "COCKTAIL GLASS");
  print_wcwidth(0x1f379, "TROPICAL DRINK");
  print_wcwidth(0x1f37a, "BEER MUG");
  print_wcwidth(0x1f37b, "CLINKING BEER MUGS");
  print_wcwidth(0x1f37c, "BABY BOTTLE");
  print_wcwidth(0x1f37d, "FORK AND KNIFE WITH PLATE");
  print_wcwidth(0x1f37e, "BOTTLE WITH POPPING CORK");
  print_wcwidth(0x1f37f, "POPCORN");
  print_wcwidth(0x1f380, "RIBBON");
  print_wcwidth(0x1f381, "WRAPPED PRESENT");
  print_wcwidth(0x1f382, "BIRTHDAY CAKE");
  print_wcwidth(0x1f383, "JACK-O-LANTERN");
  print_wcwidth(0x1f384, "CHRISTMAS TREE");
  print_wcwidth(0x1f385, "FATHER CHRISTMAS");
  print_wcwidth(0x1f386, "FIREWORKS");
  print_wcwidth(0x1f387, "FIREWORK SPARKLER");
  print_wcwidth(0x1f388, "BALLOON");
  print_wcwidth(0x1f389, "PARTY POPPER");
  print_wcwidth(0x1f38a, "CONFETTI BALL");
  print_wcwidth(0x1f38b, "TANABATA TREE");
  print_wcwidth(0x1f38c, "CROSSED FLAGS");
  print_wcwidth(0x1f38d, "PINE DECORATION");
  print_wcwidth(0x1f38e, "JAPANESE DOLLS");
  print_wcwidth(0x1f38f, "CARP STREAMER");
  print_wcwidth(0x1f390, "WIND CHIME");
  print_wcwidth(0x1f391, "MOON VIEWING CEREMONY");
  print_wcwidth(0x1f392, "SCHOOL SATCHEL");
  print_wcwidth(0x1f393, "GRADUATION CAP");
  print_wcwidth(0x1f396, "MILITARY MEDAL");
  print_wcwidth(0x1f397, "REMINDER RIBBON");
  print_wcwidth(0x1f399, "STUDIO MICROPHONE");
  print_wcwidth(0x1f39a, "LEVEL SLIDER");
  print_wcwidth(0x1f39b, "CONTROL KNOBS");
  print_wcwidth(0x1f39e, "FILM FRAMES");
  print_wcwidth(0x1f39f, "ADMISSION TICKETS");
  print_wcwidth(0x1f3a0, "CAROUSEL HORSE");
  print_wcwidth(0x1f3a1, "FERRIS WHEEL");
  print_wcwidth(0x1f3a2, "ROLLER COASTER");
  print_wcwidth(0x1f3a3, "FISHING POLE AND FISH");
  print_wcwidth(0x1f3a4, "MICROPHONE");
  print_wcwidth(0x1f3a5, "MOVIE CAMERA");
  print_wcwidth(0x1f3a6, "CINEMA");
  print_wcwidth(0x1f3a7, "HEADPHONE");
  print_wcwidth(0x1f3a8, "ARTIST PALETTE");
  print_wcwidth(0x1f3a9, "TOP HAT");
  print_wcwidth(0x1f3aa, "CIRCUS TENT");
  print_wcwidth(0x1f3ab, "TICKET");
  print_wcwidth(0x1f3ac, "CLAPPER BOARD");
  print_wcwidth(0x1f3ad, "PERFORMING ARTS");
  print_wcwidth(0x1f3ae, "VIDEO GAME");
  print_wcwidth(0x1f3af, "DIRECT HIT");
  print_wcwidth(0x1f3b0, "SLOT MACHINE");
  print_wcwidth(0x1f3b1, "BILLIARDS");
  print_wcwidth(0x1f3b2, "GAME DIE");
  print_wcwidth(0x1f3b3, "BOWLING");
  print_wcwidth(0x1f3b4, "FLOWER PLAYING CARDS");
  print_wcwidth(0x1f3b5, "MUSICAL NOTE");
  print_wcwidth(0x1f3b6, "MULTIPLE MUSICAL NOTES");
  print_wcwidth(0x1f3b7, "SAXOPHONE");
  print_wcwidth(0x1f3b8, "GUITAR");
  print_wcwidth(0x1f3b9, "MUSICAL KEYBOARD");
  print_wcwidth(0x1f3ba, "TRUMPET");
  print_wcwidth(0x1f3bb, "VIOLIN");
  print_wcwidth(0x1f3bc, "MUSICAL SCORE");
  print_wcwidth(0x1f3bd, "RUNNING SHIRT WITH SASH");
  print_wcwidth(0x1f3be, "TENNIS RACQUET AND BALL");
  print_wcwidth(0x1f3bf, "SKI AND SKI BOOT");
  print_wcwidth(0x1f3c0, "BASKETBALL AND HOOP");
  print_wcwidth(0x1f3c1, "CHEQUERED FLAG");
  print_wcwidth(0x1f3c2, "SNOWBOARDER");
  print_wcwidth(0x1f3c3, "RUNNER");
  print_wcwidth(0x1f3c4, "SURFER");
  print_wcwidth(0x1f3c5, "SPORTS MEDAL");
  print_wcwidth(0x1f3c6, "TROPHY");
  print_wcwidth(0x1f3c7, "HORSE RACING");
  print_wcwidth(0x1f3c8, "AMERICAN FOOTBALL");
  print_wcwidth(0x1f3c9, "RUGBY FOOTBALL");
  print_wcwidth(0x1f3ca, "SWIMMER");
  print_wcwidth(0x1f3cb, "WEIGHT LIFTER");
  print_wcwidth(0x1f3cc, "GOLFER");
  print_wcwidth(0x1f3cd, "RACING MOTORCYCLE");
  print_wcwidth(0x1f3ce, "RACING CAR");
  print_wcwidth(0x1f3cf, "CRICKET BAT AND BALL");
  print_wcwidth(0x1f3d0, "VOLLEYBALL");
  print_wcwidth(0x1f3d1, "FIELD HOCKEY STICK AND BALL");
  print_wcwidth(0x1f3d2, "ICE HOCKEY STICK AND PUCK");
  print_wcwidth(0x1f3d3, "TABLE TENNIS PADDLE AND BALL");
  print_wcwidth(0x1f3d4, "SNOW CAPPED MOUNTAIN");
  print_wcwidth(0x1f3d5, "CAMPING");
  print_wcwidth(0x1f3d6, "BEACH WITH UMBRELLA");
  print_wcwidth(0x1f3d7, "BUILDING CONSTRUCTION");
  print_wcwidth(0x1f3d8, "HOUSE BUILDINGS");
  print_wcwidth(0x1f3d9, "CITYSCAPE");
  print_wcwidth(0x1f3da, "DERELICT HOUSE BUILDING");
  print_wcwidth(0x1f3db, "CLASSICAL BUILDING");
  print_wcwidth(0x1f3dc, "DESERT");
  print_wcwidth(0x1f3dd, "DESERT ISLAND");
  print_wcwidth(0x1f3de, "NATIONAL PARK");
  print_wcwidth(0x1f3df, "STADIUM");
  print_wcwidth(0x1f3e0, "HOUSE BUILDING");
  print_wcwidth(0x1f3e1, "HOUSE WITH GARDEN");
  print_wcwidth(0x1f3e2, "OFFICE BUILDING");
  print_wcwidth(0x1f3e3, "JAPANESE POST OFFICE");
  print_wcwidth(0x1f3e4, "EUROPEAN POST OFFICE");
  print_wcwidth(0x1f3e5, "HOSPITAL");
  print_wcwidth(0x1f3e6, "BANK");
  print_wcwidth(0x1f3e7, "AUTOMATED TELLER MACHINE");
  print_wcwidth(0x1f3e8, "HOTEL");
  print_wcwidth(0x1f3e9, "LOVE HOTEL");
  print_wcwidth(0x1f3ea, "CONVENIENCE STORE");
  print_wcwidth(0x1f3eb, "SCHOOL");
  print_wcwidth(0x1f3ec, "DEPARTMENT STORE");
  print_wcwidth(0x1f3ed, "FACTORY");
  print_wcwidth(0x1f3ee, "IZAKAYA LANTERN");
  print_wcwidth(0x1f3ef, "JAPANESE CASTLE");
  print_wcwidth(0x1f3f0, "EUROPEAN CASTLE");
  print_wcwidth(0x1f3f3, "WAVING WHITE FLAG");
  print_wcwidth(0x1f3f4, "WAVING BLACK FLAG");
  print_wcwidth(0x1f3f5, "ROSETTE");
  print_wcwidth(0x1f3f7, "LABEL");
  print_wcwidth(0x1f3f8, "BADMINTON RACQUET AND SHUTTLECOCK");
  print_wcwidth(0x1f3f9, "BOW AND ARROW");
  print_wcwidth(0x1f3fa, "AMPHORA");
  print_wcwidth(0x1f3fb, "EMOJI MODIFIER FITZPATRICK TYPE-1-2");
  print_wcwidth(0x1f3fc, "EMOJI MODIFIER FITZPATRICK TYPE-3");
  print_wcwidth(0x1f3fd, "EMOJI MODIFIER FITZPATRICK TYPE-4");
  print_wcwidth(0x1f3fe, "EMOJI MODIFIER FITZPATRICK TYPE-5");
  print_wcwidth(0x1f3ff, "EMOJI MODIFIER FITZPATRICK TYPE-6");
  print_wcwidth(0x1f400, "RAT");
  print_wcwidth(0x1f401, "MOUSE");
  print_wcwidth(0x1f402, "OX");
  print_wcwidth(0x1f403, "WATER BUFFALO");
  print_wcwidth(0x1f404, "COW");
  print_wcwidth(0x1f405, "TIGER");
  print_wcwidth(0x1f406, "LEOPARD");
  print_wcwidth(0x1f407, "RABBIT");
  print_wcwidth(0x1f408, "CAT");
  print_wcwidth(0x1f409, "DRAGON");
  print_wcwidth(0x1f40a, "CROCODILE");
  print_wcwidth(0x1f40b, "WHALE");
  print_wcwidth(0x1f40c, "SNAIL");
  print_wcwidth(0x1f40d, "SNAKE");
  print_wcwidth(0x1f40e, "HORSE");
  print_wcwidth(0x1f40f, "RAM");
  print_wcwidth(0x1f410, "GOAT");
  print_wcwidth(0x1f411, "SHEEP");
  print_wcwidth(0x1f412, "MONKEY");
  print_wcwidth(0x1f413, "ROOSTER");
  print_wcwidth(0x1f414, "CHICKEN");
  print_wcwidth(0x1f415, "DOG");
  print_wcwidth(0x1f416, "PIG");
  print_wcwidth(0x1f417, "BOAR");
  print_wcwidth(0x1f418, "ELEPHANT");
  print_wcwidth(0x1f419, "OCTOPUS");
  print_wcwidth(0x1f41a, "SPIRAL SHELL");
  print_wcwidth(0x1f41b, "BUG");
  print_wcwidth(0x1f41c, "ANT");
  print_wcwidth(0x1f41d, "HONEYBEE");
  print_wcwidth(0x1f41e, "LADY BEETLE");
  print_wcwidth(0x1f41f, "FISH");
  print_wcwidth(0x1f420, "TROPICAL FISH");
  print_wcwidth(0x1f421, "BLOWFISH");
  print_wcwidth(0x1f422, "TURTLE");
  print_wcwidth(0x1f423, "HATCHING CHICK");
  print_wcwidth(0x1f424, "BABY CHICK");
  print_wcwidth(0x1f425, "FRONT-FACING BABY CHICK");
  print_wcwidth(0x1f426, "BIRD");
  print_wcwidth(0x1f427, "PENGUIN");
  print_wcwidth(0x1f428, "KOALA");
  print_wcwidth(0x1f429, "POODLE");
  print_wcwidth(0x1f42a, "DROMEDARY CAMEL");
  print_wcwidth(0x1f42b, "BACTRIAN CAMEL");
  print_wcwidth(0x1f42c, "DOLPHIN");
  print_wcwidth(0x1f42d, "MOUSE FACE");
  print_wcwidth(0x1f42e, "COW FACE");
  print_wcwidth(0x1f42f, "TIGER FACE");
  print_wcwidth(0x1f430, "RABBIT FACE");
  print_wcwidth(0x1f431, "CAT FACE");
  print_wcwidth(0x1f432, "DRAGON FACE");
  print_wcwidth(0x1f433, "SPOUTING WHALE");
  print_wcwidth(0x1f434, "HORSE FACE");
  print_wcwidth(0x1f435, "MONKEY FACE");
  print_wcwidth(0x1f436, "DOG FACE");
  print_wcwidth(0x1f437, "PIG FACE");
  print_wcwidth(0x1f438, "FROG FACE");
  print_wcwidth(0x1f439, "HAMSTER FACE");
  print_wcwidth(0x1f43a, "WOLF FACE");
  print_wcwidth(0x1f43b, "BEAR FACE");
  print_wcwidth(0x1f43c, "PANDA FACE");
  print_wcwidth(0x1f43d, "PIG NOSE");
  print_wcwidth(0x1f43e, "PAW PRINTS");
  print_wcwidth(0x1f43f, "CHIPMUNK");
  print_wcwidth(0x1f440, "EYES");
  print_wcwidth(0x1f441, "EYE");
  print_wcwidth(0x1f442, "EAR");
  print_wcwidth(0x1f443, "NOSE");
  print_wcwidth(0x1f444, "MOUTH");
  print_wcwidth(0x1f445, "TONGUE");
  print_wcwidth(0x1f446, "WHITE UP POINTING BACKHAND INDEX");
  print_wcwidth(0x1f447, "WHITE DOWN POINTING BACKHAND INDEX");
  print_wcwidth(0x1f448, "WHITE LEFT POINTING BACKHAND INDEX");
  print_wcwidth(0x1f449, "WHITE RIGHT POINTING BACKHAND INDEX");
  print_wcwidth(0x1f44a, "FISTED HAND SIGN");
  print_wcwidth(0x1f44b, "WAVING HAND SIGN");
  print_wcwidth(0x1f44c, "OK HAND SIGN");
  print_wcwidth(0x1f44d, "THUMBS UP SIGN");
  print_wcwidth(0x1f44e, "THUMBS DOWN SIGN");
  print_wcwidth(0x1f44f, "CLAPPING HANDS SIGN");
  print_wcwidth(0x1f450, "OPEN HANDS SIGN");
  print_wcwidth(0x1f451, "CROWN");
  print_wcwidth(0x1f452, "WOMANS HAT");
  print_wcwidth(0x1f453, "EYEGLASSES");
  print_wcwidth(0x1f454, "NECKTIE");
  print_wcwidth(0x1f455, "T-SHIRT");
  print_wcwidth(0x1f456, "JEANS");
  print_wcwidth(0x1f457, "DRESS");
  print_wcwidth(0x1f458, "KIMONO");
  print_wcwidth(0x1f459, "BIKINI");
  print_wcwidth(0x1f45a, "WOMANS CLOTHES");
  print_wcwidth(0x1f45b, "PURSE");
  print_wcwidth(0x1f45c, "HANDBAG");
  print_wcwidth(0x1f45d, "POUCH");
  print_wcwidth(0x1f45e, "MANS SHOE");
  print_wcwidth(0x1f45f, "ATHLETIC SHOE");
  print_wcwidth(0x1f460, "HIGH-HEELED SHOE");
  print_wcwidth(0x1f461, "WOMANS SANDAL");
  print_wcwidth(0x1f462, "WOMANS BOOTS");
  print_wcwidth(0x1f463, "FOOTPRINTS");
  print_wcwidth(0x1f464, "BUST IN SILHOUETTE");
  print_wcwidth(0x1f465, "BUSTS IN SILHOUETTE");
  print_wcwidth(0x1f466, "BOY");
  print_wcwidth(0x1f467, "GIRL");
  print_wcwidth(0x1f468, "MAN");
  print_wcwidth(0x1f469, "WOMAN");
  print_wcwidth(0x1f46a, "FAMILY");
  print_wcwidth(0x1f46b, "MAN AND WOMAN HOLDING HANDS");
  print_wcwidth(0x1f46c, "TWO MEN HOLDING HANDS");
  print_wcwidth(0x1f46d, "TWO WOMEN HOLDING HANDS");
  print_wcwidth(0x1f46e, "POLICE OFFICER");
  print_wcwidth(0x1f46f, "WOMAN WITH BUNNY EARS");
  print_wcwidth(0x1f470, "BRIDE WITH VEIL");
  print_wcwidth(0x1f471, "PERSON WITH BLOND HAIR");
  print_wcwidth(0x1f472, "MAN WITH GUA PI MAO");
  print_wcwidth(0x1f473, "MAN WITH TURBAN");
  print_wcwidth(0x1f474, "OLDER MAN");
  print_wcwidth(0x1f475, "OLDER WOMAN");
  print_wcwidth(0x1f476, "BABY");
  print_wcwidth(0x1f477, "CONSTRUCTION WORKER");
  print_wcwidth(0x1f478, "PRINCESS");
  print_wcwidth(0x1f479, "JAPANESE OGRE");
  print_wcwidth(0x1f47a, "JAPANESE GOBLIN");
  print_wcwidth(0x1f47b, "GHOST");
  print_wcwidth(0x1f47c, "BABY ANGEL");
  print_wcwidth(0x1f47d, "EXTRATERRESTRIAL ALIEN");
  print_wcwidth(0x1f47e, "ALIEN MONSTER");
  print_wcwidth(0x1f47f, "IMP");
  print_wcwidth(0x1f480, "SKULL");
  print_wcwidth(0x1f481, "INFORMATION DESK PERSON");
  print_wcwidth(0x1f482, "GUARDSMAN");
  print_wcwidth(0x1f483, "DANCER");
  print_wcwidth(0x1f484, "LIPSTICK");
  print_wcwidth(0x1f485, "NAIL POLISH");
  print_wcwidth(0x1f486, "FACE MASSAGE");
  print_wcwidth(0x1f487, "HAIRCUT");
  print_wcwidth(0x1f488, "BARBER POLE");
  print_wcwidth(0x1f489, "SYRINGE");
  print_wcwidth(0x1f48a, "PILL");
  print_wcwidth(0x1f48b, "KISS MARK");
  print_wcwidth(0x1f48c, "LOVE LETTER");
  print_wcwidth(0x1f48d, "RING");
  print_wcwidth(0x1f48e, "GEM STONE");
  print_wcwidth(0x1f48f, "KISS");
  print_wcwidth(0x1f490, "BOUQUET");
  print_wcwidth(0x1f491, "COUPLE WITH HEART");
  print_wcwidth(0x1f492, "WEDDING");
  print_wcwidth(0x1f493, "BEATING HEART");
  print_wcwidth(0x1f494, "BROKEN HEART");
  print_wcwidth(0x1f495, "TWO HEARTS");
  print_wcwidth(0x1f496, "SPARKLING HEART");
  print_wcwidth(0x1f497, "GROWING HEART");
  print_wcwidth(0x1f498, "HEART WITH ARROW");
  print_wcwidth(0x1f499, "BLUE HEART");
  print_wcwidth(0x1f49a, "GREEN HEART");
  print_wcwidth(0x1f49b, "YELLOW HEART");
  print_wcwidth(0x1f49c, "PURPLE HEART");
  print_wcwidth(0x1f49d, "HEART WITH RIBBON");
  print_wcwidth(0x1f49e, "REVOLVING HEARTS");
  print_wcwidth(0x1f49f, "HEART DECORATION");
  print_wcwidth(0x1f4a0, "DIAMOND SHAPE WITH A DOT INSIDE");
  print_wcwidth(0x1f4a1, "ELECTRIC LIGHT BULB");
  print_wcwidth(0x1f4a2, "ANGER SYMBOL");
  print_wcwidth(0x1f4a3, "BOMB");
  print_wcwidth(0x1f4a4, "SLEEPING SYMBOL");
  print_wcwidth(0x1f4a5, "COLLISION SYMBOL");
  print_wcwidth(0x1f4a6, "SPLASHING SWEAT SYMBOL");
  print_wcwidth(0x1f4a7, "DROPLET");
  print_wcwidth(0x1f4a8, "DASH SYMBOL");
  print_wcwidth(0x1f4a9, "PILE OF POO");
  print_wcwidth(0x1f4aa, "FLEXED BICEPS");
  print_wcwidth(0x1f4ab, "DIZZY SYMBOL");
  print_wcwidth(0x1f4ac, "SPEECH BALLOON");
  print_wcwidth(0x1f4ad, "THOUGHT BALLOON");
  print_wcwidth(0x1f4ae, "WHITE FLOWER");
  print_wcwidth(0x1f4af, "HUNDRED POINTS SYMBOL");
  print_wcwidth(0x1f4b0, "MONEY BAG");
  print_wcwidth(0x1f4b1, "CURRENCY EXCHANGE");
  print_wcwidth(0x1f4b2, "HEAVY DOLLAR SIGN");
  print_wcwidth(0x1f4b3, "CREDIT CARD");
  print_wcwidth(0x1f4b4, "BANKNOTE WITH YEN SIGN");
  print_wcwidth(0x1f4b5, "BANKNOTE WITH DOLLAR SIGN");
  print_wcwidth(0x1f4b6, "BANKNOTE WITH EURO SIGN");
  print_wcwidth(0x1f4b7, "BANKNOTE WITH POUND SIGN");
  print_wcwidth(0x1f4b8, "MONEY WITH WINGS");
  print_wcwidth(0x1f4b9, "CHART WITH UPWARDS TREND AND YEN SIGN");
  print_wcwidth(0x1f4ba, "SEAT");
  print_wcwidth(0x1f4bb, "PERSONAL COMPUTER");
  print_wcwidth(0x1f4bc, "BRIEFCASE");
  print_wcwidth(0x1f4bd, "MINIDISC");
  print_wcwidth(0x1f4be, "FLOPPY DISK");
  print_wcwidth(0x1f4bf, "OPTICAL DISC");
  print_wcwidth(0x1f4c0, "DVD");
  print_wcwidth(0x1f4c1, "FILE FOLDER");
  print_wcwidth(0x1f4c2, "OPEN FILE FOLDER");
  print_wcwidth(0x1f4c3, "PAGE WITH CURL");
  print_wcwidth(0x1f4c4, "PAGE FACING UP");
  print_wcwidth(0x1f4c5, "CALENDAR");
  print_wcwidth(0x1f4c6, "TEAR-OFF CALENDAR");
  print_wcwidth(0x1f4c7, "CARD INDEX");
  print_wcwidth(0x1f4c8, "CHART WITH UPWARDS TREND");
  print_wcwidth(0x1f4c9, "CHART WITH DOWNWARDS TREND");
  print_wcwidth(0x1f4ca, "BAR CHART");
  print_wcwidth(0x1f4cb, "CLIPBOARD");
  print_wcwidth(0x1f4cc, "PUSHPIN");
  print_wcwidth(0x1f4cd, "ROUND PUSHPIN");
  print_wcwidth(0x1f4ce, "PAPERCLIP");
  print_wcwidth(0x1f4cf, "STRAIGHT RULER");
  print_wcwidth(0x1f4d0, "TRIANGULAR RULER");
  print_wcwidth(0x1f4d1, "BOOKMARK TABS");
  print_wcwidth(0x1f4d2, "LEDGER");
  print_wcwidth(0x1f4d3, "NOTEBOOK");
  print_wcwidth(0x1f4d4, "NOTEBOOK WITH DECORATIVE COVER");
  print_wcwidth(0x1f4d5, "CLOSED BOOK");
  print_wcwidth(0x1f4d6, "OPEN BOOK");
  print_wcwidth(0x1f4d7, "GREEN BOOK");
  print_wcwidth(0x1f4d8, "BLUE BOOK");
  print_wcwidth(0x1f4d9, "ORANGE BOOK");
  print_wcwidth(0x1f4da, "BOOKS");
  print_wcwidth(0x1f4db, "NAME BADGE");
  print_wcwidth(0x1f4dc, "SCROLL");
  print_wcwidth(0x1f4dd, "MEMO");
  print_wcwidth(0x1f4de, "TELEPHONE RECEIVER");
  print_wcwidth(0x1f4df, "PAGER");
  print_wcwidth(0x1f4e0, "FAX MACHINE");
  print_wcwidth(0x1f4e1, "SATELLITE ANTENNA");
  print_wcwidth(0x1f4e2, "PUBLIC ADDRESS LOUDSPEAKER");
  print_wcwidth(0x1f4e3, "CHEERING MEGAPHONE");
  print_wcwidth(0x1f4e4, "OUTBOX TRAY");
  print_wcwidth(0x1f4e5, "INBOX TRAY");
  print_wcwidth(0x1f4e6, "PACKAGE");
  print_wcwidth(0x1f4e7, "E-MAIL SYMBOL");
  print_wcwidth(0x1f4e8, "INCOMING ENVELOPE");
  print_wcwidth(0x1f4e9, "ENVELOPE WITH DOWNWARDS ARROW ABOVE");
  print_wcwidth(0x1f4ea, "CLOSED MAILBOX WITH LOWERED FLAG");
  print_wcwidth(0x1f4eb, "CLOSED MAILBOX WITH RAISED FLAG");
  print_wcwidth(0x1f4ec, "OPEN MAILBOX WITH RAISED FLAG");
  print_wcwidth(0x1f4ed, "OPEN MAILBOX WITH LOWERED FLAG");
  print_wcwidth(0x1f4ee, "POSTBOX");
  print_wcwidth(0x1f4ef, "POSTAL HORN");
  print_wcwidth(0x1f4f0, "NEWSPAPER");
  print_wcwidth(0x1f4f1, "MOBILE PHONE");
  print_wcwidth(0x1f4f2, "MOBILE PHONE WITH RIGHTWARDS ARROW AT LEFT");
  print_wcwidth(0x1f4f3, "VIBRATION MODE");
  print_wcwidth(0x1f4f4, "MOBILE PHONE OFF");
  print_wcwidth(0x1f4f5, "NO MOBILE PHONES");
  print_wcwidth(0x1f4f6, "ANTENNA WITH BARS");
  print_wcwidth(0x1f4f7, "CAMERA");
  print_wcwidth(0x1f4f8, "CAMERA WITH FLASH");
  print_wcwidth(0x1f4f9, "VIDEO CAMERA");
  print_wcwidth(0x1f4fa, "TELEVISION");
  print_wcwidth(0x1f4fb, "RADIO");
  print_wcwidth(0x1f4fc, "VIDEOCASSETTE");
  print_wcwidth(0x1f4fd, "FILM PROJECTOR");
  print_wcwidth(0x1f4ff, "PRAYER BEADS");
  print_wcwidth(0x1f500, "TWISTED RIGHTWARDS ARROWS");
  print_wcwidth(0x1f501, "CLOCKWISE RIGHTWARDS AND LEFTWARDS OPEN CIRCLE ARROWS");
  print_wcwidth(0x1f502, "CLOCKWISE RIGHTWARDS AND LEFTWARDS OPEN CIRCLE ARROWS WITH CIRCLED ONE OVERLAY");
  print_wcwidth(0x1f503, "CLOCKWISE DOWNWARDS AND UPWARDS OPEN CIRCLE ARROWS");
  print_wcwidth(0x1f504, "ANTICLOCKWISE DOWNWARDS AND UPWARDS OPEN CIRCLE ARROWS");
  print_wcwidth(0x1f505, "LOW BRIGHTNESS SYMBOL");
  print_wcwidth(0x1f506, "HIGH BRIGHTNESS SYMBOL");
  print_wcwidth(0x1f507, "SPEAKER WITH CANCELLATION STROKE");
  print_wcwidth(0x1f508, "SPEAKER");
  print_wcwidth(0x1f509, "SPEAKER WITH ONE SOUND WAVE");
  print_wcwidth(0x1f50a, "SPEAKER WITH THREE SOUND WAVES");
  print_wcwidth(0x1f50b, "BATTERY");
  print_wcwidth(0x1f50c, "ELECTRIC PLUG");
  print_wcwidth(0x1f50d, "LEFT-POINTING MAGNIFYING GLASS");
  print_wcwidth(0x1f50e, "RIGHT-POINTING MAGNIFYING GLASS");
  print_wcwidth(0x1f50f, "LOCK WITH INK PEN");
  print_wcwidth(0x1f510, "CLOSED LOCK WITH KEY");
  print_wcwidth(0x1f511, "KEY");
  print_wcwidth(0x1f512, "LOCK");
  print_wcwidth(0x1f513, "OPEN LOCK");
  print_wcwidth(0x1f514, "BELL");
  print_wcwidth(0x1f515, "BELL WITH CANCELLATION STROKE");
  print_wcwidth(0x1f516, "BOOKMARK");
  print_wcwidth(0x1f517, "LINK SYMBOL");
  print_wcwidth(0x1f518, "RADIO BUTTON");
  print_wcwidth(0x1f519, "BACK WITH LEFTWARDS ARROW ABOVE");
  print_wcwidth(0x1f51a, "END WITH LEFTWARDS ARROW ABOVE");
  print_wcwidth(0x1f51b, "ON WITH EXCLAMATION MARK WITH LEFT RIGHT ARROW ABOVE");
  print_wcwidth(0x1f51c, "SOON WITH RIGHTWARDS ARROW ABOVE");
  print_wcwidth(0x1f51d, "TOP WITH UPWARDS ARROW ABOVE");
  print_wcwidth(0x1f51e, "NO ONE UNDER EIGHTEEN SYMBOL");
  print_wcwidth(0x1f51f, "KEYCAP TEN");
  print_wcwidth(0x1f520, "INPUT SYMBOL FOR LATIN CAPITAL LETTERS");
  print_wcwidth(0x1f521, "INPUT SYMBOL FOR LATIN SMALL LETTERS");
  print_wcwidth(0x1f522, "INPUT SYMBOL FOR NUMBERS");
  print_wcwidth(0x1f523, "INPUT SYMBOL FOR SYMBOLS");
  print_wcwidth(0x1f524, "INPUT SYMBOL FOR LATIN LETTERS");
  print_wcwidth(0x1f525, "FIRE");
  print_wcwidth(0x1f526, "ELECTRIC TORCH");
  print_wcwidth(0x1f527, "WRENCH");
  print_wcwidth(0x1f528, "HAMMER");
  print_wcwidth(0x1f529, "NUT AND BOLT");
  print_wcwidth(0x1f52a, "HOCHO");
  print_wcwidth(0x1f52b, "PISTOL");
  print_wcwidth(0x1f52c, "MICROSCOPE");
  print_wcwidth(0x1f52d, "TELESCOPE");
  print_wcwidth(0x1f52e, "CRYSTAL BALL");
  print_wcwidth(0x1f52f, "SIX POINTED STAR WITH MIDDLE DOT");
  print_wcwidth(0x1f530, "JAPANESE SYMBOL FOR BEGINNER");
  print_wcwidth(0x1f531, "TRIDENT EMBLEM");
  print_wcwidth(0x1f532, "BLACK SQUARE BUTTON");
  print_wcwidth(0x1f533, "WHITE SQUARE BUTTON");
  print_wcwidth(0x1f534, "LARGE RED CIRCLE");
  print_wcwidth(0x1f535, "LARGE BLUE CIRCLE");
  print_wcwidth(0x1f536, "LARGE ORANGE DIAMOND");
  print_wcwidth(0x1f537, "LARGE BLUE DIAMOND");
  print_wcwidth(0x1f538, "SMALL ORANGE DIAMOND");
  print_wcwidth(0x1f539, "SMALL BLUE DIAMOND");
  print_wcwidth(0x1f53a, "UP-POINTING RED TRIANGLE");
  print_wcwidth(0x1f53b, "DOWN-POINTING RED TRIANGLE");
  print_wcwidth(0x1f53c, "UP-POINTING SMALL RED TRIANGLE");
  print_wcwidth(0x1f53d, "DOWN-POINTING SMALL RED TRIANGLE");
  print_wcwidth(0x1f549, "OM SYMBOL");
  print_wcwidth(0x1f54a, "DOVE OF PEACE");
  print_wcwidth(0x1f54b, "KAABA");
  print_wcwidth(0x1f54c, "MOSQUE");
  print_wcwidth(0x1f54d, "SYNAGOGUE");
  print_wcwidth(0x1f54e, "MENORAH WITH NINE BRANCHES");
  print_wcwidth(0x1f550, "CLOCK FACE ONE OCLOCK");
  print_wcwidth(0x1f551, "CLOCK FACE TWO OCLOCK");
  print_wcwidth(0x1f552, "CLOCK FACE THREE OCLOCK");
  print_wcwidth(0x1f553, "CLOCK FACE FOUR OCLOCK");
  print_wcwidth(0x1f554, "CLOCK FACE FIVE OCLOCK");
  print_wcwidth(0x1f555, "CLOCK FACE SIX OCLOCK");
  print_wcwidth(0x1f556, "CLOCK FACE SEVEN OCLOCK");
  print_wcwidth(0x1f557, "CLOCK FACE EIGHT OCLOCK");
  print_wcwidth(0x1f558, "CLOCK FACE NINE OCLOCK");
  print_wcwidth(0x1f559, "CLOCK FACE TEN OCLOCK");
  print_wcwidth(0x1f55a, "CLOCK FACE ELEVEN OCLOCK");
  print_wcwidth(0x1f55b, "CLOCK FACE TWELVE OCLOCK");
  print_wcwidth(0x1f55c, "CLOCK FACE ONE-THIRTY");
  print_wcwidth(0x1f55d, "CLOCK FACE TWO-THIRTY");
  print_wcwidth(0x1f55e, "CLOCK FACE THREE-THIRTY");
  print_wcwidth(0x1f55f, "CLOCK FACE FOUR-THIRTY");
  print_wcwidth(0x1f560, "CLOCK FACE FIVE-THIRTY");
  print_wcwidth(0x1f561, "CLOCK FACE SIX-THIRTY");
  print_wcwidth(0x1f562, "CLOCK FACE SEVEN-THIRTY");
  print_wcwidth(0x1f563, "CLOCK FACE EIGHT-THIRTY");
  print_wcwidth(0x1f564, "CLOCK FACE NINE-THIRTY");
  print_wcwidth(0x1f565, "CLOCK FACE TEN-THIRTY");
  print_wcwidth(0x1f566, "CLOCK FACE ELEVEN-THIRTY");
  print_wcwidth(0x1f567, "CLOCK FACE TWELVE-THIRTY");
  print_wcwidth(0x1f56f, "CANDLE");
  print_wcwidth(0x1f570, "MANTELPIECE CLOCK");
  print_wcwidth(0x1f573, "HOLE");
  print_wcwidth(0x1f574, "MAN IN BUSINESS SUIT LEVITATING");
  print_wcwidth(0x1f575, "SLEUTH OR SPY");
  print_wcwidth(0x1f576, "DARK SUNGLASSES");
  print_wcwidth(0x1f577, "SPIDER");
  print_wcwidth(0x1f578, "SPIDER WEB");
  print_wcwidth(0x1f579, "JOYSTICK");
  print_wcwidth(0x1f587, "LINKED PAPERCLIPS");
  print_wcwidth(0x1f58a, "LOWER LEFT BALLPOINT PEN");
  print_wcwidth(0x1f58b, "LOWER LEFT FOUNTAIN PEN");
  print_wcwidth(0x1f58c, "LOWER LEFT PAINTBRUSH");
  print_wcwidth(0x1f58d, "LOWER LEFT CRAYON");
  print_wcwidth(0x1f590, "RAISED HAND WITH FINGERS SPLAYED");
  print_wcwidth(0x1f595, "REVERSED HAND WITH MIDDLE FINGER EXTENDED");
  print_wcwidth(0x1f596, "RAISED HAND WITH PART BETWEEN MIDDLE AND RING FINGERS");
  print_wcwidth(0x1f5a5, "DESKTOP COMPUTER");
  print_wcwidth(0x1f5a8, "PRINTER");
  print_wcwidth(0x1f5b1, "THREE BUTTON MOUSE");
  print_wcwidth(0x1f5b2, "TRACKBALL");
  print_wcwidth(0x1f5bc, "FRAME WITH PICTURE");
  print_wcwidth(0x1f5c2, "CARD INDEX DIVIDERS");
  print_wcwidth(0x1f5c3, "CARD FILE BOX");
  print_wcwidth(0x1f5c4, "FILE CABINET");
  print_wcwidth(0x1f5d1, "WASTEBASKET");
  print_wcwidth(0x1f5d2, "SPIRAL NOTE PAD");
  print_wcwidth(0x1f5d3, "SPIRAL CALENDAR PAD");
  print_wcwidth(0x1f5dc, "COMPRESSION");
  print_wcwidth(0x1f5dd, "OLD KEY");
  print_wcwidth(0x1f5de, "ROLLED-UP NEWSPAPER");
  print_wcwidth(0x1f5e1, "DAGGER KNIFE");
  print_wcwidth(0x1f5e3, "SPEAKING HEAD IN SILHOUETTE");
  print_wcwidth(0x1f5ef, "RIGHT ANGER BUBBLE");
  print_wcwidth(0x1f5f3, "BALLOT BOX WITH BALLOT");
  print_wcwidth(0x1f5fa, "WORLD MAP");
  print_wcwidth(0x1f5fb, "MOUNT FUJI");
  print_wcwidth(0x1f5fc, "TOKYO TOWER");
  print_wcwidth(0x1f5fd, "STATUE OF LIBERTY");
  print_wcwidth(0x1f5fe, "SILHOUETTE OF JAPAN");
  print_wcwidth(0x1f5ff, "MOYAI");
  print_wcwidth(0x1f600, "GRINNING FACE");
  print_wcwidth(0x1f601, "GRINNING FACE WITH SMILING EYES");
  print_wcwidth(0x1f602, "FACE WITH TEARS OF JOY");
  print_wcwidth(0x1f603, "SMILING FACE WITH OPEN MOUTH");
  print_wcwidth(0x1f604, "SMILING FACE WITH OPEN MOUTH AND SMILING EYES");
  print_wcwidth(0x1f605, "SMILING FACE WITH OPEN MOUTH AND COLD SWEAT");
  print_wcwidth(0x1f606, "SMILING FACE WITH OPEN MOUTH AND TIGHTLY-CLOSED EYES");
  print_wcwidth(0x1f607, "SMILING FACE WITH HALO");
  print_wcwidth(0x1f608, "SMILING FACE WITH HORNS");
  print_wcwidth(0x1f609, "WINKING FACE");
  print_wcwidth(0x1f60a, "SMILING FACE WITH SMILING EYES");
  print_wcwidth(0x1f60b, "FACE SAVOURING DELICIOUS FOOD");
  print_wcwidth(0x1f60c, "RELIEVED FACE");
  print_wcwidth(0x1f60d, "SMILING FACE WITH HEART-SHAPED EYES");
  print_wcwidth(0x1f60e, "SMILING FACE WITH SUNGLASSES");
  print_wcwidth(0x1f60f, "SMIRKING FACE");
  print_wcwidth(0x1f610, "NEUTRAL FACE");
  print_wcwidth(0x1f611, "EXPRESSIONLESS FACE");
  print_wcwidth(0x1f612, "UNAMUSED FACE");
  print_wcwidth(0x1f613, "FACE WITH COLD SWEAT");
  print_wcwidth(0x1f614, "PENSIVE FACE");
  print_wcwidth(0x1f615, "CONFUSED FACE");
  print_wcwidth(0x1f616, "CONFOUNDED FACE");
  print_wcwidth(0x1f617, "KISSING FACE");
  print_wcwidth(0x1f618, "FACE THROWING A KISS");
  print_wcwidth(0x1f619, "KISSING FACE WITH SMILING EYES");
  print_wcwidth(0x1f61a, "KISSING FACE WITH CLOSED EYES");
  print_wcwidth(0x1f61b, "FACE WITH STUCK-OUT TONGUE");
  print_wcwidth(0x1f61c, "FACE WITH STUCK-OUT TONGUE AND WINKING EYE");
  print_wcwidth(0x1f61d, "FACE WITH STUCK-OUT TONGUE AND TIGHTLY-CLOSED EYES");
  print_wcwidth(0x1f61e, "DISAPPOINTED FACE");
  print_wcwidth(0x1f61f, "WORRIED FACE");
  print_wcwidth(0x1f620, "ANGRY FACE");
  print_wcwidth(0x1f621, "POUTING FACE");
  print_wcwidth(0x1f622, "CRYING FACE");
  print_wcwidth(0x1f623, "PERSEVERING FACE");
  print_wcwidth(0x1f624, "FACE WITH LOOK OF TRIUMPH");
  print_wcwidth(0x1f625, "DISAPPOINTED BUT RELIEVED FACE");
  print_wcwidth(0x1f626, "FROWNING FACE WITH OPEN MOUTH");
  print_wcwidth(0x1f627, "ANGUISHED FACE");
  print_wcwidth(0x1f628, "FEARFUL FACE");
  print_wcwidth(0x1f629, "WEARY FACE");
  print_wcwidth(0x1f62a, "SLEEPY FACE");
  print_wcwidth(0x1f62b, "TIRED FACE");
  print_wcwidth(0x1f62c, "GRIMACING FACE");
  print_wcwidth(0x1f62d, "LOUDLY CRYING FACE");
  print_wcwidth(0x1f62e, "FACE WITH OPEN MOUTH");
  print_wcwidth(0x1f62f, "HUSHED FACE");
  print_wcwidth(0x1f630, "FACE WITH OPEN MOUTH AND COLD SWEAT");
  print_wcwidth(0x1f631, "FACE SCREAMING IN FEAR");
  print_wcwidth(0x1f632, "ASTONISHED FACE");
  print_wcwidth(0x1f633, "FLUSHED FACE");
  print_wcwidth(0x1f634, "SLEEPING FACE");
  print_wcwidth(0x1f635, "DIZZY FACE");
  print_wcwidth(0x1f636, "FACE WITHOUT MOUTH");
  print_wcwidth(0x1f637, "FACE WITH MEDICAL MASK");
  print_wcwidth(0x1f638, "GRINNING CAT FACE WITH SMILING EYES");
  print_wcwidth(0x1f639, "CAT FACE WITH TEARS OF JOY");
  print_wcwidth(0x1f63a, "SMILING CAT FACE WITH OPEN MOUTH");
  print_wcwidth(0x1f63b, "SMILING CAT FACE WITH HEART-SHAPED EYES");
  print_wcwidth(0x1f63c, "CAT FACE WITH WRY SMILE");
  print_wcwidth(0x1f63d, "KISSING CAT FACE WITH CLOSED EYES");
  print_wcwidth(0x1f63e, "POUTING CAT FACE");
  print_wcwidth(0x1f63f, "CRYING CAT FACE");
  print_wcwidth(0x1f640, "WEARY CAT FACE");
  print_wcwidth(0x1f641, "SLIGHTLY FROWNING FACE");
  print_wcwidth(0x1f642, "SLIGHTLY SMILING FACE");
  print_wcwidth(0x1f643, "UPSIDE-DOWN FACE");
  print_wcwidth(0x1f644, "FACE WITH ROLLING EYES");
  print_wcwidth(0x1f645, "FACE WITH NO GOOD GESTURE");
  print_wcwidth(0x1f646, "FACE WITH OK GESTURE");
  print_wcwidth(0x1f647, "PERSON BOWING DEEPLY");
  print_wcwidth(0x1f648, "SEE-NO-EVIL MONKEY");
  print_wcwidth(0x1f649, "HEAR-NO-EVIL MONKEY");
  print_wcwidth(0x1f64a, "SPEAK-NO-EVIL MONKEY");
  print_wcwidth(0x1f64b, "HAPPY PERSON RAISING ONE HAND");
  print_wcwidth(0x1f64c, "PERSON RAISING BOTH HANDS IN CELEBRATION");
  print_wcwidth(0x1f64d, "PERSON FROWNING");
  print_wcwidth(0x1f64e, "PERSON WITH POUTING FACE");
  print_wcwidth(0x1f64f, "PERSON WITH FOLDED HANDS");
  print_wcwidth(0x1f680, "ROCKET");
  print_wcwidth(0x1f681, "HELICOPTER");
  print_wcwidth(0x1f682, "STEAM LOCOMOTIVE");
  print_wcwidth(0x1f683, "RAILWAY CAR");
  print_wcwidth(0x1f684, "HIGH-SPEED TRAIN");
  print_wcwidth(0x1f685, "HIGH-SPEED TRAIN WITH BULLET NOSE");
  print_wcwidth(0x1f686, "TRAIN");
  print_wcwidth(0x1f687, "METRO");
  print_wcwidth(0x1f688, "LIGHT RAIL");
  print_wcwidth(0x1f689, "STATION");
  print_wcwidth(0x1f68a, "TRAM");
  print_wcwidth(0x1f68b, "TRAM CAR");
  print_wcwidth(0x1f68c, "BUS");
  print_wcwidth(0x1f68d, "ONCOMING BUS");
  print_wcwidth(0x1f68e, "TROLLEYBUS");
  print_wcwidth(0x1f68f, "BUS STOP");
  print_wcwidth(0x1f690, "MINIBUS");
  print_wcwidth(0x1f691, "AMBULANCE");
  print_wcwidth(0x1f692, "FIRE ENGINE");
  print_wcwidth(0x1f693, "POLICE CAR");
  print_wcwidth(0x1f694, "ONCOMING POLICE CAR");
  print_wcwidth(0x1f695, "TAXI");
  print_wcwidth(0x1f696, "ONCOMING TAXI");
  print_wcwidth(0x1f697, "AUTOMOBILE");
  print_wcwidth(0x1f698, "ONCOMING AUTOMOBILE");
  print_wcwidth(0x1f699, "RECREATIONAL VEHICLE");
  print_wcwidth(0x1f69a, "DELIVERY TRUCK");
  print_wcwidth(0x1f69b, "ARTICULATED LORRY");
  print_wcwidth(0x1f69c, "TRACTOR");
  print_wcwidth(0x1f69d, "MONORAIL");
  print_wcwidth(0x1f69e, "MOUNTAIN RAILWAY");
  print_wcwidth(0x1f69f, "SUSPENSION RAILWAY");
  print_wcwidth(0x1f6a0, "MOUNTAIN CABLEWAY");
  print_wcwidth(0x1f6a1, "AERIAL TRAMWAY");
  print_wcwidth(0x1f6a2, "SHIP");
  print_wcwidth(0x1f6a3, "ROWBOAT");
  print_wcwidth(0x1f6a4, "SPEEDBOAT");
  print_wcwidth(0x1f6a5, "HORIZONTAL TRAFFIC LIGHT");
  print_wcwidth(0x1f6a6, "VERTICAL TRAFFIC LIGHT");
  print_wcwidth(0x1f6a7, "CONSTRUCTION SIGN");
  print_wcwidth(0x1f6a8, "POLICE CARS REVOLVING LIGHT");
  print_wcwidth(0x1f6a9, "TRIANGULAR FLAG ON POST");
  print_wcwidth(0x1f6aa, "DOOR");
  print_wcwidth(0x1f6ab, "NO ENTRY SIGN");
  print_wcwidth(0x1f6ac, "SMOKING SYMBOL");
  print_wcwidth(0x1f6ad, "NO SMOKING SYMBOL");
  print_wcwidth(0x1f6ae, "PUT LITTER IN ITS PLACE SYMBOL");
  print_wcwidth(0x1f6af, "DO NOT LITTER SYMBOL");
  print_wcwidth(0x1f6b0, "POTABLE WATER SYMBOL");
  print_wcwidth(0x1f6b1, "NON-POTABLE WATER SYMBOL");
  print_wcwidth(0x1f6b2, "BICYCLE");
  print_wcwidth(0x1f6b3, "NO BICYCLES");
  print_wcwidth(0x1f6b4, "BICYCLIST");
  print_wcwidth(0x1f6b5, "MOUNTAIN BICYCLIST");
  print_wcwidth(0x1f6b6, "PEDESTRIAN");
  print_wcwidth(0x1f6b7, "NO PEDESTRIANS");
  print_wcwidth(0x1f6b8, "CHILDREN CROSSING");
  print_wcwidth(0x1f6b9, "MENS SYMBOL");
  print_wcwidth(0x1f6ba, "WOMENS SYMBOL");
  print_wcwidth(0x1f6bb, "RESTROOM");
  print_wcwidth(0x1f6bc, "BABY SYMBOL");
  print_wcwidth(0x1f6bd, "TOILET");
  print_wcwidth(0x1f6be, "WATER CLOSET");
  print_wcwidth(0x1f6bf, "SHOWER");
  print_wcwidth(0x1f6c0, "BATH");
  print_wcwidth(0x1f6c1, "BATHTUB");
  print_wcwidth(0x1f6c2, "PASSPORT CONTROL");
  print_wcwidth(0x1f6c3, "CUSTOMS");
  print_wcwidth(0x1f6c4, "BAGGAGE CLAIM");
  print_wcwidth(0x1f6c5, "LEFT LUGGAGE");
  print_wcwidth(0x1f6cb, "COUCH AND LAMP");
  print_wcwidth(0x1f6cc, "SLEEPING ACCOMMODATION");
  print_wcwidth(0x1f6cd, "SHOPPING BAGS");
  print_wcwidth(0x1f6ce, "BELLHOP BELL");
  print_wcwidth(0x1f6cf, "BED");
  print_wcwidth(0x1f6d0, "PLACE OF WORSHIP");
  print_wcwidth(0x1f6e0, "HAMMER AND WRENCH");
  print_wcwidth(0x1f6e1, "SHIELD");
  print_wcwidth(0x1f6e2, "OIL DRUM");
  print_wcwidth(0x1f6e3, "MOTORWAY");
  print_wcwidth(0x1f6e4, "RAILWAY TRACK");
  print_wcwidth(0x1f6e5, "MOTOR BOAT");
  print_wcwidth(0x1f6e9, "SMALL AIRPLANE");
  print_wcwidth(0x1f6eb, "AIRPLANE DEPARTURE");
  print_wcwidth(0x1f6ec, "AIRPLANE ARRIVING");
  print_wcwidth(0x1f6f0, "SATELLITE");
  print_wcwidth(0x1f6f3, "PASSENGER SHIP");
  print_wcwidth(0x1f910, "ZIPPER-MOUTH FACE");
  print_wcwidth(0x1f911, "MONEY-MOUTH FACE");
  print_wcwidth(0x1f912, "FACE WITH THERMOMETER");
  print_wcwidth(0x1f913, "NERD FACE");
  print_wcwidth(0x1f914, "THINKING FACE");
  print_wcwidth(0x1f915, "FACE WITH HEAD-BANDAGE");
  print_wcwidth(0x1f916, "ROBOT FACE");
  print_wcwidth(0x1f917, "HUGGING FACE");
  print_wcwidth(0x1f918, "SIGN OF THE HORNS");
  print_wcwidth(0x1f980, "CRAB");
  print_wcwidth(0x1f981, "LION FACE");
  print_wcwidth(0x1f982, "SCORPION");
  print_wcwidth(0x1f983, "TURKEY");
  print_wcwidth(0x1f984, "UNICORN FACE");
  print_wcwidth(0x1f9c0, "CHEESE WEDGE");
  return 0;
}
