#define _XOPEN_SOURCE
#include <stdio.h>
#include <locale.h>
#include <wchar.h>

void print_wcwidth(wchar_t c, char *str)
{
  printf("wcwidth('[%lc]') == %d, codepoint [%x], %s\n", c, wcwidth(c), c, str);
}
int main()
{
  setlocale(LC_CTYPE, "");
  print_wcwidth(0xa1, "INVERTED EXCLAMATION MARK");
  print_wcwidth(0xa4, "CURRENCY SIGN");
  print_wcwidth(0xa7, "SECTION SIGN");
  print_wcwidth(0xa8, "DIAERESIS");
  print_wcwidth(0xaa, "FEMININE ORDINAL INDICATOR");
  print_wcwidth(0xad, "SOFT HYPHEN");
  print_wcwidth(0xae, "REGISTERED SIGN");
  print_wcwidth(0xb0, "DEGREE SIGN");
  print_wcwidth(0xb1, "PLUS-MINUS SIGN");
  print_wcwidth(0xb2, "SUPERSCRIPT TWO");
  print_wcwidth(0xb3, "SUPERSCRIPT THREE");
  print_wcwidth(0xb4, "ACUTE ACCENT");
  print_wcwidth(0xb6, "PILCROW SIGN");
  print_wcwidth(0xb7, "MIDDLE DOT");
  print_wcwidth(0xb8, "CEDILLA");
  print_wcwidth(0xb9, "SUPERSCRIPT ONE");
  print_wcwidth(0xba, "MASCULINE ORDINAL INDICATOR");
  print_wcwidth(0xbc, "VULGAR FRACTION ONE QUARTER");
  print_wcwidth(0xbd, "VULGAR FRACTION ONE HALF");
  print_wcwidth(0xbe, "VULGAR FRACTION THREE QUARTERS");
  print_wcwidth(0xbf, "INVERTED QUESTION MARK");
  print_wcwidth(0xc6, "LATIN CAPITAL LETTER AE");
  print_wcwidth(0xd0, "LATIN CAPITAL LETTER ETH");
  print_wcwidth(0xd7, "MULTIPLICATION SIGN");
  print_wcwidth(0xd8, "LATIN CAPITAL LETTER O WITH STROKE");
  print_wcwidth(0xde, "LATIN CAPITAL LETTER THORN");
  print_wcwidth(0xdf, "LATIN SMALL LETTER SHARP S");
  print_wcwidth(0xe0, "LATIN SMALL LETTER A WITH GRAVE");
  print_wcwidth(0xe1, "LATIN SMALL LETTER A WITH ACUTE");
  print_wcwidth(0xe6, "LATIN SMALL LETTER AE");
  print_wcwidth(0xe8, "LATIN SMALL LETTER E WITH GRAVE");
  print_wcwidth(0xe9, "LATIN SMALL LETTER E WITH ACUTE");
  print_wcwidth(0xea, "LATIN SMALL LETTER E WITH CIRCUMFLEX");
  print_wcwidth(0xec, "LATIN SMALL LETTER I WITH GRAVE");
  print_wcwidth(0xed, "LATIN SMALL LETTER I WITH ACUTE");
  print_wcwidth(0xf0, "LATIN SMALL LETTER ETH");
  print_wcwidth(0xf2, "LATIN SMALL LETTER O WITH GRAVE");
  print_wcwidth(0xf3, "LATIN SMALL LETTER O WITH ACUTE");
  print_wcwidth(0xf7, "DIVISION SIGN");
  print_wcwidth(0xf8, "LATIN SMALL LETTER O WITH STROKE");
  print_wcwidth(0xf9, "LATIN SMALL LETTER U WITH GRAVE");
  print_wcwidth(0xfa, "LATIN SMALL LETTER U WITH ACUTE");
  print_wcwidth(0xfc, "LATIN SMALL LETTER U WITH DIAERESIS");
  print_wcwidth(0xfe, "LATIN SMALL LETTER THORN");
  print_wcwidth(0x101, "LATIN SMALL LETTER A WITH MACRON");
  print_wcwidth(0x111, "LATIN SMALL LETTER D WITH STROKE");
  print_wcwidth(0x113, "LATIN SMALL LETTER E WITH MACRON");
  print_wcwidth(0x11b, "LATIN SMALL LETTER E WITH CARON");
  print_wcwidth(0x126, "LATIN CAPITAL LETTER H WITH STROKE");
  print_wcwidth(0x127, "LATIN SMALL LETTER H WITH STROKE");
  print_wcwidth(0x12b, "LATIN SMALL LETTER I WITH MACRON");
  print_wcwidth(0x131, "LATIN SMALL LETTER DOTLESS I");
  print_wcwidth(0x132, "LATIN CAPITAL LIGATURE IJ");
  print_wcwidth(0x133, "LATIN SMALL LIGATURE IJ");
  print_wcwidth(0x138, "LATIN SMALL LETTER KRA");
  print_wcwidth(0x13f, "LATIN CAPITAL LETTER L WITH MIDDLE DOT");
  print_wcwidth(0x140, "LATIN SMALL LETTER L WITH MIDDLE DOT");
  print_wcwidth(0x141, "LATIN CAPITAL LETTER L WITH STROKE");
  print_wcwidth(0x142, "LATIN SMALL LETTER L WITH STROKE");
  print_wcwidth(0x144, "LATIN SMALL LETTER N WITH ACUTE");
  print_wcwidth(0x148, "LATIN SMALL LETTER N WITH CARON");
  print_wcwidth(0x149, "LATIN SMALL LETTER N PRECEDED BY APOSTROPHE");
  print_wcwidth(0x14a, "LATIN CAPITAL LETTER ENG");
  print_wcwidth(0x14b, "LATIN SMALL LETTER ENG");
  print_wcwidth(0x14d, "LATIN SMALL LETTER O WITH MACRON");
  print_wcwidth(0x152, "LATIN CAPITAL LIGATURE OE");
  print_wcwidth(0x153, "LATIN SMALL LIGATURE OE");
  print_wcwidth(0x166, "LATIN CAPITAL LETTER T WITH STROKE");
  print_wcwidth(0x167, "LATIN SMALL LETTER T WITH STROKE");
  print_wcwidth(0x16b, "LATIN SMALL LETTER U WITH MACRON");
  print_wcwidth(0x1ce, "LATIN SMALL LETTER A WITH CARON");
  print_wcwidth(0x1d0, "LATIN SMALL LETTER I WITH CARON");
  print_wcwidth(0x1d2, "LATIN SMALL LETTER O WITH CARON");
  print_wcwidth(0x1d4, "LATIN SMALL LETTER U WITH CARON");
  print_wcwidth(0x1d6, "LATIN SMALL LETTER U WITH DIAERESIS AND MACRON");
  print_wcwidth(0x1d8, "LATIN SMALL LETTER U WITH DIAERESIS AND ACUTE");
  print_wcwidth(0x1da, "LATIN SMALL LETTER U WITH DIAERESIS AND CARON");
  print_wcwidth(0x1dc, "LATIN SMALL LETTER U WITH DIAERESIS AND GRAVE");
  print_wcwidth(0x251, "LATIN SMALL LETTER ALPHA");
  print_wcwidth(0x261, "LATIN SMALL LETTER SCRIPT G");
  print_wcwidth(0x2c4, "MODIFIER LETTER UP ARROWHEAD");
  print_wcwidth(0x2c7, "CARON");
  print_wcwidth(0x2c9, "MODIFIER LETTER MACRON");
  print_wcwidth(0x2ca, "MODIFIER LETTER ACUTE ACCENT");
  print_wcwidth(0x2cb, "MODIFIER LETTER GRAVE ACCENT");
  print_wcwidth(0x2cd, "MODIFIER LETTER LOW MACRON");
  print_wcwidth(0x2d0, "MODIFIER LETTER TRIANGULAR COLON");
  print_wcwidth(0x2d8, "BREVE");
  print_wcwidth(0x2d9, "DOT ABOVE");
  print_wcwidth(0x2da, "RING ABOVE");
  print_wcwidth(0x2db, "OGONEK");
  print_wcwidth(0x2dd, "DOUBLE ACUTE ACCENT");
  print_wcwidth(0x2df, "MODIFIER LETTER CROSS ACCENT");
  print_wcwidth(0x391, "GREEK CAPITAL LETTER ALPHA");
  print_wcwidth(0x392, "GREEK CAPITAL LETTER BETA");
  print_wcwidth(0x393, "GREEK CAPITAL LETTER GAMMA");
  print_wcwidth(0x394, "GREEK CAPITAL LETTER DELTA");
  print_wcwidth(0x395, "GREEK CAPITAL LETTER EPSILON");
  print_wcwidth(0x396, "GREEK CAPITAL LETTER ZETA");
  print_wcwidth(0x397, "GREEK CAPITAL LETTER ETA");
  print_wcwidth(0x398, "GREEK CAPITAL LETTER THETA");
  print_wcwidth(0x399, "GREEK CAPITAL LETTER IOTA");
  print_wcwidth(0x39a, "GREEK CAPITAL LETTER KAPPA");
  print_wcwidth(0x39b, "GREEK CAPITAL LETTER LAMDA");
  print_wcwidth(0x39c, "GREEK CAPITAL LETTER MU");
  print_wcwidth(0x39d, "GREEK CAPITAL LETTER NU");
  print_wcwidth(0x39e, "GREEK CAPITAL LETTER XI");
  print_wcwidth(0x39f, "GREEK CAPITAL LETTER OMICRON");
  print_wcwidth(0x3a0, "GREEK CAPITAL LETTER PI");
  print_wcwidth(0x3a1, "GREEK CAPITAL LETTER RHO");
  print_wcwidth(0x3a3, "GREEK CAPITAL LETTER SIGMA");
  print_wcwidth(0x3a4, "GREEK CAPITAL LETTER TAU");
  print_wcwidth(0x3a5, "GREEK CAPITAL LETTER UPSILON");
  print_wcwidth(0x3a6, "GREEK CAPITAL LETTER PHI");
  print_wcwidth(0x3a7, "GREEK CAPITAL LETTER CHI");
  print_wcwidth(0x3a8, "GREEK CAPITAL LETTER PSI");
  print_wcwidth(0x3a9, "GREEK CAPITAL LETTER OMEGA");
  print_wcwidth(0x3b1, "GREEK SMALL LETTER ALPHA");
  print_wcwidth(0x3b2, "GREEK SMALL LETTER BETA");
  print_wcwidth(0x3b3, "GREEK SMALL LETTER GAMMA");
  print_wcwidth(0x3b4, "GREEK SMALL LETTER DELTA");
  print_wcwidth(0x3b5, "GREEK SMALL LETTER EPSILON");
  print_wcwidth(0x3b6, "GREEK SMALL LETTER ZETA");
  print_wcwidth(0x3b7, "GREEK SMALL LETTER ETA");
  print_wcwidth(0x3b8, "GREEK SMALL LETTER THETA");
  print_wcwidth(0x3b9, "GREEK SMALL LETTER IOTA");
  print_wcwidth(0x3ba, "GREEK SMALL LETTER KAPPA");
  print_wcwidth(0x3bb, "GREEK SMALL LETTER LAMDA");
  print_wcwidth(0x3bc, "GREEK SMALL LETTER MU");
  print_wcwidth(0x3bd, "GREEK SMALL LETTER NU");
  print_wcwidth(0x3be, "GREEK SMALL LETTER XI");
  print_wcwidth(0x3bf, "GREEK SMALL LETTER OMICRON");
  print_wcwidth(0x3c0, "GREEK SMALL LETTER PI");
  print_wcwidth(0x3c1, "GREEK SMALL LETTER RHO");
  print_wcwidth(0x3c3, "GREEK SMALL LETTER SIGMA");
  print_wcwidth(0x3c4, "GREEK SMALL LETTER TAU");
  print_wcwidth(0x3c5, "GREEK SMALL LETTER UPSILON");
  print_wcwidth(0x3c6, "GREEK SMALL LETTER PHI");
  print_wcwidth(0x3c7, "GREEK SMALL LETTER CHI");
  print_wcwidth(0x3c8, "GREEK SMALL LETTER PSI");
  print_wcwidth(0x3c9, "GREEK SMALL LETTER OMEGA");
  print_wcwidth(0x401, "CYRILLIC CAPITAL LETTER IO");
  print_wcwidth(0x410, "CYRILLIC CAPITAL LETTER A");
  print_wcwidth(0x411, "CYRILLIC CAPITAL LETTER BE");
  print_wcwidth(0x412, "CYRILLIC CAPITAL LETTER VE");
  print_wcwidth(0x413, "CYRILLIC CAPITAL LETTER GHE");
  print_wcwidth(0x414, "CYRILLIC CAPITAL LETTER DE");
  print_wcwidth(0x415, "CYRILLIC CAPITAL LETTER IE");
  print_wcwidth(0x416, "CYRILLIC CAPITAL LETTER ZHE");
  print_wcwidth(0x417, "CYRILLIC CAPITAL LETTER ZE");
  print_wcwidth(0x418, "CYRILLIC CAPITAL LETTER I");
  print_wcwidth(0x419, "CYRILLIC CAPITAL LETTER SHORT I");
  print_wcwidth(0x41a, "CYRILLIC CAPITAL LETTER KA");
  print_wcwidth(0x41b, "CYRILLIC CAPITAL LETTER EL");
  print_wcwidth(0x41c, "CYRILLIC CAPITAL LETTER EM");
  print_wcwidth(0x41d, "CYRILLIC CAPITAL LETTER EN");
  print_wcwidth(0x41e, "CYRILLIC CAPITAL LETTER O");
  print_wcwidth(0x41f, "CYRILLIC CAPITAL LETTER PE");
  print_wcwidth(0x420, "CYRILLIC CAPITAL LETTER ER");
  print_wcwidth(0x421, "CYRILLIC CAPITAL LETTER ES");
  print_wcwidth(0x422, "CYRILLIC CAPITAL LETTER TE");
  print_wcwidth(0x423, "CYRILLIC CAPITAL LETTER U");
  print_wcwidth(0x424, "CYRILLIC CAPITAL LETTER EF");
  print_wcwidth(0x425, "CYRILLIC CAPITAL LETTER HA");
  print_wcwidth(0x426, "CYRILLIC CAPITAL LETTER TSE");
  print_wcwidth(0x427, "CYRILLIC CAPITAL LETTER CHE");
  print_wcwidth(0x428, "CYRILLIC CAPITAL LETTER SHA");
  print_wcwidth(0x429, "CYRILLIC CAPITAL LETTER SHCHA");
  print_wcwidth(0x42a, "CYRILLIC CAPITAL LETTER HARD SIGN");
  print_wcwidth(0x42b, "CYRILLIC CAPITAL LETTER YERU");
  print_wcwidth(0x42c, "CYRILLIC CAPITAL LETTER SOFT SIGN");
  print_wcwidth(0x42d, "CYRILLIC CAPITAL LETTER E");
  print_wcwidth(0x42e, "CYRILLIC CAPITAL LETTER YU");
  print_wcwidth(0x42f, "CYRILLIC CAPITAL LETTER YA");
  print_wcwidth(0x430, "CYRILLIC SMALL LETTER A");
  print_wcwidth(0x431, "CYRILLIC SMALL LETTER BE");
  print_wcwidth(0x432, "CYRILLIC SMALL LETTER VE");
  print_wcwidth(0x433, "CYRILLIC SMALL LETTER GHE");
  print_wcwidth(0x434, "CYRILLIC SMALL LETTER DE");
  print_wcwidth(0x435, "CYRILLIC SMALL LETTER IE");
  print_wcwidth(0x436, "CYRILLIC SMALL LETTER ZHE");
  print_wcwidth(0x437, "CYRILLIC SMALL LETTER ZE");
  print_wcwidth(0x438, "CYRILLIC SMALL LETTER I");
  print_wcwidth(0x439, "CYRILLIC SMALL LETTER SHORT I");
  print_wcwidth(0x43a, "CYRILLIC SMALL LETTER KA");
  print_wcwidth(0x43b, "CYRILLIC SMALL LETTER EL");
  print_wcwidth(0x43c, "CYRILLIC SMALL LETTER EM");
  print_wcwidth(0x43d, "CYRILLIC SMALL LETTER EN");
  print_wcwidth(0x43e, "CYRILLIC SMALL LETTER O");
  print_wcwidth(0x43f, "CYRILLIC SMALL LETTER PE");
  print_wcwidth(0x440, "CYRILLIC SMALL LETTER ER");
  print_wcwidth(0x441, "CYRILLIC SMALL LETTER ES");
  print_wcwidth(0x442, "CYRILLIC SMALL LETTER TE");
  print_wcwidth(0x443, "CYRILLIC SMALL LETTER U");
  print_wcwidth(0x444, "CYRILLIC SMALL LETTER EF");
  print_wcwidth(0x445, "CYRILLIC SMALL LETTER HA");
  print_wcwidth(0x446, "CYRILLIC SMALL LETTER TSE");
  print_wcwidth(0x447, "CYRILLIC SMALL LETTER CHE");
  print_wcwidth(0x448, "CYRILLIC SMALL LETTER SHA");
  print_wcwidth(0x449, "CYRILLIC SMALL LETTER SHCHA");
  print_wcwidth(0x44a, "CYRILLIC SMALL LETTER HARD SIGN");
  print_wcwidth(0x44b, "CYRILLIC SMALL LETTER YERU");
  print_wcwidth(0x44c, "CYRILLIC SMALL LETTER SOFT SIGN");
  print_wcwidth(0x44d, "CYRILLIC SMALL LETTER E");
  print_wcwidth(0x44e, "CYRILLIC SMALL LETTER YU");
  print_wcwidth(0x44f, "CYRILLIC SMALL LETTER YA");
  print_wcwidth(0x451, "CYRILLIC SMALL LETTER IO");
  print_wcwidth(0x2010, "HYPHEN");
  print_wcwidth(0x2013, "EN DASH");
  print_wcwidth(0x2014, "EM DASH");
  print_wcwidth(0x2015, "HORIZONTAL BAR");
  print_wcwidth(0x2016, "DOUBLE VERTICAL LINE");
  print_wcwidth(0x2018, "LEFT SINGLE QUOTATION MARK");
  print_wcwidth(0x2019, "RIGHT SINGLE QUOTATION MARK");
  print_wcwidth(0x201c, "LEFT DOUBLE QUOTATION MARK");
  print_wcwidth(0x201d, "RIGHT DOUBLE QUOTATION MARK");
  print_wcwidth(0x2020, "DAGGER");
  print_wcwidth(0x2021, "DOUBLE DAGGER");
  print_wcwidth(0x2022, "BULLET");
  print_wcwidth(0x2024, "ONE DOT LEADER");
  print_wcwidth(0x2025, "TWO DOT LEADER");
  print_wcwidth(0x2026, "HORIZONTAL ELLIPSIS");
  print_wcwidth(0x2027, "HYPHENATION POINT");
  print_wcwidth(0x2030, "PER MILLE SIGN");
  print_wcwidth(0x2032, "PRIME");
  print_wcwidth(0x2033, "DOUBLE PRIME");
  print_wcwidth(0x2035, "REVERSED PRIME");
  print_wcwidth(0x203b, "REFERENCE MARK");
  print_wcwidth(0x203e, "OVERLINE");
  print_wcwidth(0x2074, "SUPERSCRIPT FOUR");
  print_wcwidth(0x207f, "SUPERSCRIPT LATIN SMALL LETTER N");
  print_wcwidth(0x2081, "SUBSCRIPT ONE");
  print_wcwidth(0x2082, "SUBSCRIPT TWO");
  print_wcwidth(0x2083, "SUBSCRIPT THREE");
  print_wcwidth(0x2084, "SUBSCRIPT FOUR");
  print_wcwidth(0x20ac, "EURO SIGN");
  print_wcwidth(0x2103, "DEGREE CELSIUS");
  print_wcwidth(0x2105, "CARE OF");
  print_wcwidth(0x2109, "DEGREE FAHRENHEIT");
  print_wcwidth(0x2113, "SCRIPT SMALL L");
  print_wcwidth(0x2116, "NUMERO SIGN");
  print_wcwidth(0x2121, "TELEPHONE SIGN");
  print_wcwidth(0x2122, "TRADE MARK SIGN");
  print_wcwidth(0x2126, "OHM SIGN");
  print_wcwidth(0x212b, "ANGSTROM SIGN");
  print_wcwidth(0x2153, "VULGAR FRACTION ONE THIRD");
  print_wcwidth(0x2154, "VULGAR FRACTION TWO THIRDS");
  print_wcwidth(0x215b, "VULGAR FRACTION ONE EIGHTH");
  print_wcwidth(0x215c, "VULGAR FRACTION THREE EIGHTHS");
  print_wcwidth(0x215d, "VULGAR FRACTION FIVE EIGHTHS");
  print_wcwidth(0x215e, "VULGAR FRACTION SEVEN EIGHTHS");
  print_wcwidth(0x2160, "ROMAN NUMERAL ONE");
  print_wcwidth(0x2161, "ROMAN NUMERAL TWO");
  print_wcwidth(0x2162, "ROMAN NUMERAL THREE");
  print_wcwidth(0x2163, "ROMAN NUMERAL FOUR");
  print_wcwidth(0x2164, "ROMAN NUMERAL FIVE");
  print_wcwidth(0x2165, "ROMAN NUMERAL SIX");
  print_wcwidth(0x2166, "ROMAN NUMERAL SEVEN");
  print_wcwidth(0x2167, "ROMAN NUMERAL EIGHT");
  print_wcwidth(0x2168, "ROMAN NUMERAL NINE");
  print_wcwidth(0x2169, "ROMAN NUMERAL TEN");
  print_wcwidth(0x216a, "ROMAN NUMERAL ELEVEN");
  print_wcwidth(0x216b, "ROMAN NUMERAL TWELVE");
  print_wcwidth(0x2170, "SMALL ROMAN NUMERAL ONE");
  print_wcwidth(0x2171, "SMALL ROMAN NUMERAL TWO");
  print_wcwidth(0x2172, "SMALL ROMAN NUMERAL THREE");
  print_wcwidth(0x2173, "SMALL ROMAN NUMERAL FOUR");
  print_wcwidth(0x2174, "SMALL ROMAN NUMERAL FIVE");
  print_wcwidth(0x2175, "SMALL ROMAN NUMERAL SIX");
  print_wcwidth(0x2176, "SMALL ROMAN NUMERAL SEVEN");
  print_wcwidth(0x2177, "SMALL ROMAN NUMERAL EIGHT");
  print_wcwidth(0x2178, "SMALL ROMAN NUMERAL NINE");
  print_wcwidth(0x2179, "SMALL ROMAN NUMERAL TEN");
  print_wcwidth(0x2189, "VULGAR FRACTION ZERO THIRDS");
  print_wcwidth(0x2190, "LEFTWARDS ARROW");
  print_wcwidth(0x2191, "UPWARDS ARROW");
  print_wcwidth(0x2192, "RIGHTWARDS ARROW");
  print_wcwidth(0x2193, "DOWNWARDS ARROW");
  print_wcwidth(0x2194, "LEFT RIGHT ARROW");
  print_wcwidth(0x2195, "UP DOWN ARROW");
  print_wcwidth(0x2196, "NORTH WEST ARROW");
  print_wcwidth(0x2197, "NORTH EAST ARROW");
  print_wcwidth(0x2198, "SOUTH EAST ARROW");
  print_wcwidth(0x2199, "SOUTH WEST ARROW");
  print_wcwidth(0x21b8, "NORTH WEST ARROW TO LONG BAR");
  print_wcwidth(0x21b9, "LEFTWARDS ARROW TO BAR OVER RIGHTWARDS ARROW TO BAR");
  print_wcwidth(0x21d2, "RIGHTWARDS DOUBLE ARROW");
  print_wcwidth(0x21d4, "LEFT RIGHT DOUBLE ARROW");
  print_wcwidth(0x21e7, "UPWARDS WHITE ARROW");
  print_wcwidth(0x2200, "FOR ALL");
  print_wcwidth(0x2202, "PARTIAL DIFFERENTIAL");
  print_wcwidth(0x2203, "THERE EXISTS");
  print_wcwidth(0x2207, "NABLA");
  print_wcwidth(0x2208, "ELEMENT OF");
  print_wcwidth(0x220b, "CONTAINS AS MEMBER");
  print_wcwidth(0x220f, "N-ARY PRODUCT");
  print_wcwidth(0x2211, "N-ARY SUMMATION");
  print_wcwidth(0x2215, "DIVISION SLASH");
  print_wcwidth(0x221a, "SQUARE ROOT");
  print_wcwidth(0x221d, "PROPORTIONAL TO");
  print_wcwidth(0x221e, "INFINITY");
  print_wcwidth(0x221f, "RIGHT ANGLE");
  print_wcwidth(0x2220, "ANGLE");
  print_wcwidth(0x2223, "DIVIDES");
  print_wcwidth(0x2225, "PARALLEL TO");
  print_wcwidth(0x2227, "LOGICAL AND");
  print_wcwidth(0x2228, "LOGICAL OR");
  print_wcwidth(0x2229, "INTERSECTION");
  print_wcwidth(0x222a, "UNION");
  print_wcwidth(0x222b, "INTEGRAL");
  print_wcwidth(0x222c, "DOUBLE INTEGRAL");
  print_wcwidth(0x222e, "CONTOUR INTEGRAL");
  print_wcwidth(0x2234, "THEREFORE");
  print_wcwidth(0x2235, "BECAUSE");
  print_wcwidth(0x2236, "RATIO");
  print_wcwidth(0x2237, "PROPORTION");
  print_wcwidth(0x223c, "TILDE OPERATOR");
  print_wcwidth(0x223d, "REVERSED TILDE");
  print_wcwidth(0x2248, "ALMOST EQUAL TO");
  print_wcwidth(0x224c, "ALL EQUAL TO");
  print_wcwidth(0x2252, "APPROXIMATELY EQUAL TO OR THE IMAGE OF");
  print_wcwidth(0x2260, "NOT EQUAL TO");
  print_wcwidth(0x2261, "IDENTICAL TO");
  print_wcwidth(0x2264, "LESS-THAN OR EQUAL TO");
  print_wcwidth(0x2265, "GREATER-THAN OR EQUAL TO");
  print_wcwidth(0x2266, "LESS-THAN OVER EQUAL TO");
  print_wcwidth(0x2267, "GREATER-THAN OVER EQUAL TO");
  print_wcwidth(0x226a, "MUCH LESS-THAN");
  print_wcwidth(0x226b, "MUCH GREATER-THAN");
  print_wcwidth(0x226e, "NOT LESS-THAN");
  print_wcwidth(0x226f, "NOT GREATER-THAN");
  print_wcwidth(0x2282, "SUBSET OF");
  print_wcwidth(0x2283, "SUPERSET OF");
  print_wcwidth(0x2286, "SUBSET OF OR EQUAL TO");
  print_wcwidth(0x2287, "SUPERSET OF OR EQUAL TO");
  print_wcwidth(0x2295, "CIRCLED PLUS");
  print_wcwidth(0x2299, "CIRCLED DOT OPERATOR");
  print_wcwidth(0x22a5, "UP TACK");
  print_wcwidth(0x22bf, "RIGHT TRIANGLE");
  print_wcwidth(0x2312, "ARC");
  print_wcwidth(0x2460, "CIRCLED DIGIT ONE");
  print_wcwidth(0x2461, "CIRCLED DIGIT TWO");
  print_wcwidth(0x2462, "CIRCLED DIGIT THREE");
  print_wcwidth(0x2463, "CIRCLED DIGIT FOUR");
  print_wcwidth(0x2464, "CIRCLED DIGIT FIVE");
  print_wcwidth(0x2465, "CIRCLED DIGIT SIX");
  print_wcwidth(0x2466, "CIRCLED DIGIT SEVEN");
  print_wcwidth(0x2467, "CIRCLED DIGIT EIGHT");
  print_wcwidth(0x2468, "CIRCLED DIGIT NINE");
  print_wcwidth(0x2469, "CIRCLED NUMBER TEN");
  print_wcwidth(0x246a, "CIRCLED NUMBER ELEVEN");
  print_wcwidth(0x246b, "CIRCLED NUMBER TWELVE");
  print_wcwidth(0x246c, "CIRCLED NUMBER THIRTEEN");
  print_wcwidth(0x246d, "CIRCLED NUMBER FOURTEEN");
  print_wcwidth(0x246e, "CIRCLED NUMBER FIFTEEN");
  print_wcwidth(0x246f, "CIRCLED NUMBER SIXTEEN");
  print_wcwidth(0x2470, "CIRCLED NUMBER SEVENTEEN");
  print_wcwidth(0x2471, "CIRCLED NUMBER EIGHTEEN");
  print_wcwidth(0x2472, "CIRCLED NUMBER NINETEEN");
  print_wcwidth(0x2473, "CIRCLED NUMBER TWENTY");
  print_wcwidth(0x2474, "PARENTHESIZED DIGIT ONE");
  print_wcwidth(0x2475, "PARENTHESIZED DIGIT TWO");
  print_wcwidth(0x2476, "PARENTHESIZED DIGIT THREE");
  print_wcwidth(0x2477, "PARENTHESIZED DIGIT FOUR");
  print_wcwidth(0x2478, "PARENTHESIZED DIGIT FIVE");
  print_wcwidth(0x2479, "PARENTHESIZED DIGIT SIX");
  print_wcwidth(0x247a, "PARENTHESIZED DIGIT SEVEN");
  print_wcwidth(0x247b, "PARENTHESIZED DIGIT EIGHT");
  print_wcwidth(0x247c, "PARENTHESIZED DIGIT NINE");
  print_wcwidth(0x247d, "PARENTHESIZED NUMBER TEN");
  print_wcwidth(0x247e, "PARENTHESIZED NUMBER ELEVEN");
  print_wcwidth(0x247f, "PARENTHESIZED NUMBER TWELVE");
  print_wcwidth(0x2480, "PARENTHESIZED NUMBER THIRTEEN");
  print_wcwidth(0x2481, "PARENTHESIZED NUMBER FOURTEEN");
  print_wcwidth(0x2482, "PARENTHESIZED NUMBER FIFTEEN");
  print_wcwidth(0x2483, "PARENTHESIZED NUMBER SIXTEEN");
  print_wcwidth(0x2484, "PARENTHESIZED NUMBER SEVENTEEN");
  print_wcwidth(0x2485, "PARENTHESIZED NUMBER EIGHTEEN");
  print_wcwidth(0x2486, "PARENTHESIZED NUMBER NINETEEN");
  print_wcwidth(0x2487, "PARENTHESIZED NUMBER TWENTY");
  print_wcwidth(0x2488, "DIGIT ONE FULL STOP");
  print_wcwidth(0x2489, "DIGIT TWO FULL STOP");
  print_wcwidth(0x248a, "DIGIT THREE FULL STOP");
  print_wcwidth(0x248b, "DIGIT FOUR FULL STOP");
  print_wcwidth(0x248c, "DIGIT FIVE FULL STOP");
  print_wcwidth(0x248d, "DIGIT SIX FULL STOP");
  print_wcwidth(0x248e, "DIGIT SEVEN FULL STOP");
  print_wcwidth(0x248f, "DIGIT EIGHT FULL STOP");
  print_wcwidth(0x2490, "DIGIT NINE FULL STOP");
  print_wcwidth(0x2491, "NUMBER TEN FULL STOP");
  print_wcwidth(0x2492, "NUMBER ELEVEN FULL STOP");
  print_wcwidth(0x2493, "NUMBER TWELVE FULL STOP");
  print_wcwidth(0x2494, "NUMBER THIRTEEN FULL STOP");
  print_wcwidth(0x2495, "NUMBER FOURTEEN FULL STOP");
  print_wcwidth(0x2496, "NUMBER FIFTEEN FULL STOP");
  print_wcwidth(0x2497, "NUMBER SIXTEEN FULL STOP");
  print_wcwidth(0x2498, "NUMBER SEVENTEEN FULL STOP");
  print_wcwidth(0x2499, "NUMBER EIGHTEEN FULL STOP");
  print_wcwidth(0x249a, "NUMBER NINETEEN FULL STOP");
  print_wcwidth(0x249b, "NUMBER TWENTY FULL STOP");
  print_wcwidth(0x249c, "PARENTHESIZED LATIN SMALL LETTER A");
  print_wcwidth(0x249d, "PARENTHESIZED LATIN SMALL LETTER B");
  print_wcwidth(0x249e, "PARENTHESIZED LATIN SMALL LETTER C");
  print_wcwidth(0x249f, "PARENTHESIZED LATIN SMALL LETTER D");
  print_wcwidth(0x24a0, "PARENTHESIZED LATIN SMALL LETTER E");
  print_wcwidth(0x24a1, "PARENTHESIZED LATIN SMALL LETTER F");
  print_wcwidth(0x24a2, "PARENTHESIZED LATIN SMALL LETTER G");
  print_wcwidth(0x24a3, "PARENTHESIZED LATIN SMALL LETTER H");
  print_wcwidth(0x24a4, "PARENTHESIZED LATIN SMALL LETTER I");
  print_wcwidth(0x24a5, "PARENTHESIZED LATIN SMALL LETTER J");
  print_wcwidth(0x24a6, "PARENTHESIZED LATIN SMALL LETTER K");
  print_wcwidth(0x24a7, "PARENTHESIZED LATIN SMALL LETTER L");
  print_wcwidth(0x24a8, "PARENTHESIZED LATIN SMALL LETTER M");
  print_wcwidth(0x24a9, "PARENTHESIZED LATIN SMALL LETTER N");
  print_wcwidth(0x24aa, "PARENTHESIZED LATIN SMALL LETTER O");
  print_wcwidth(0x24ab, "PARENTHESIZED LATIN SMALL LETTER P");
  print_wcwidth(0x24ac, "PARENTHESIZED LATIN SMALL LETTER Q");
  print_wcwidth(0x24ad, "PARENTHESIZED LATIN SMALL LETTER R");
  print_wcwidth(0x24ae, "PARENTHESIZED LATIN SMALL LETTER S");
  print_wcwidth(0x24af, "PARENTHESIZED LATIN SMALL LETTER T");
  print_wcwidth(0x24b0, "PARENTHESIZED LATIN SMALL LETTER U");
  print_wcwidth(0x24b1, "PARENTHESIZED LATIN SMALL LETTER V");
  print_wcwidth(0x24b2, "PARENTHESIZED LATIN SMALL LETTER W");
  print_wcwidth(0x24b3, "PARENTHESIZED LATIN SMALL LETTER X");
  print_wcwidth(0x24b4, "PARENTHESIZED LATIN SMALL LETTER Y");
  print_wcwidth(0x24b5, "PARENTHESIZED LATIN SMALL LETTER Z");
  print_wcwidth(0x24b6, "CIRCLED LATIN CAPITAL LETTER A");
  print_wcwidth(0x24b7, "CIRCLED LATIN CAPITAL LETTER B");
  print_wcwidth(0x24b8, "CIRCLED LATIN CAPITAL LETTER C");
  print_wcwidth(0x24b9, "CIRCLED LATIN CAPITAL LETTER D");
  print_wcwidth(0x24ba, "CIRCLED LATIN CAPITAL LETTER E");
  print_wcwidth(0x24bb, "CIRCLED LATIN CAPITAL LETTER F");
  print_wcwidth(0x24bc, "CIRCLED LATIN CAPITAL LETTER G");
  print_wcwidth(0x24bd, "CIRCLED LATIN CAPITAL LETTER H");
  print_wcwidth(0x24be, "CIRCLED LATIN CAPITAL LETTER I");
  print_wcwidth(0x24bf, "CIRCLED LATIN CAPITAL LETTER J");
  print_wcwidth(0x24c0, "CIRCLED LATIN CAPITAL LETTER K");
  print_wcwidth(0x24c1, "CIRCLED LATIN CAPITAL LETTER L");
  print_wcwidth(0x24c2, "CIRCLED LATIN CAPITAL LETTER M");
  print_wcwidth(0x24c3, "CIRCLED LATIN CAPITAL LETTER N");
  print_wcwidth(0x24c4, "CIRCLED LATIN CAPITAL LETTER O");
  print_wcwidth(0x24c5, "CIRCLED LATIN CAPITAL LETTER P");
  print_wcwidth(0x24c6, "CIRCLED LATIN CAPITAL LETTER Q");
  print_wcwidth(0x24c7, "CIRCLED LATIN CAPITAL LETTER R");
  print_wcwidth(0x24c8, "CIRCLED LATIN CAPITAL LETTER S");
  print_wcwidth(0x24c9, "CIRCLED LATIN CAPITAL LETTER T");
  print_wcwidth(0x24ca, "CIRCLED LATIN CAPITAL LETTER U");
  print_wcwidth(0x24cb, "CIRCLED LATIN CAPITAL LETTER V");
  print_wcwidth(0x24cc, "CIRCLED LATIN CAPITAL LETTER W");
  print_wcwidth(0x24cd, "CIRCLED LATIN CAPITAL LETTER X");
  print_wcwidth(0x24ce, "CIRCLED LATIN CAPITAL LETTER Y");
  print_wcwidth(0x24cf, "CIRCLED LATIN CAPITAL LETTER Z");
  print_wcwidth(0x24d0, "CIRCLED LATIN SMALL LETTER A");
  print_wcwidth(0x24d1, "CIRCLED LATIN SMALL LETTER B");
  print_wcwidth(0x24d2, "CIRCLED LATIN SMALL LETTER C");
  print_wcwidth(0x24d3, "CIRCLED LATIN SMALL LETTER D");
  print_wcwidth(0x24d4, "CIRCLED LATIN SMALL LETTER E");
  print_wcwidth(0x24d5, "CIRCLED LATIN SMALL LETTER F");
  print_wcwidth(0x24d6, "CIRCLED LATIN SMALL LETTER G");
  print_wcwidth(0x24d7, "CIRCLED LATIN SMALL LETTER H");
  print_wcwidth(0x24d8, "CIRCLED LATIN SMALL LETTER I");
  print_wcwidth(0x24d9, "CIRCLED LATIN SMALL LETTER J");
  print_wcwidth(0x24da, "CIRCLED LATIN SMALL LETTER K");
  print_wcwidth(0x24db, "CIRCLED LATIN SMALL LETTER L");
  print_wcwidth(0x24dc, "CIRCLED LATIN SMALL LETTER M");
  print_wcwidth(0x24dd, "CIRCLED LATIN SMALL LETTER N");
  print_wcwidth(0x24de, "CIRCLED LATIN SMALL LETTER O");
  print_wcwidth(0x24df, "CIRCLED LATIN SMALL LETTER P");
  print_wcwidth(0x24e0, "CIRCLED LATIN SMALL LETTER Q");
  print_wcwidth(0x24e1, "CIRCLED LATIN SMALL LETTER R");
  print_wcwidth(0x24e2, "CIRCLED LATIN SMALL LETTER S");
  print_wcwidth(0x24e3, "CIRCLED LATIN SMALL LETTER T");
  print_wcwidth(0x24e4, "CIRCLED LATIN SMALL LETTER U");
  print_wcwidth(0x24e5, "CIRCLED LATIN SMALL LETTER V");
  print_wcwidth(0x24e6, "CIRCLED LATIN SMALL LETTER W");
  print_wcwidth(0x24e7, "CIRCLED LATIN SMALL LETTER X");
  print_wcwidth(0x24e8, "CIRCLED LATIN SMALL LETTER Y");
  print_wcwidth(0x24e9, "CIRCLED LATIN SMALL LETTER Z");
  print_wcwidth(0x24eb, "NEGATIVE CIRCLED NUMBER ELEVEN");
  print_wcwidth(0x24ec, "NEGATIVE CIRCLED NUMBER TWELVE");
  print_wcwidth(0x24ed, "NEGATIVE CIRCLED NUMBER THIRTEEN");
  print_wcwidth(0x24ee, "NEGATIVE CIRCLED NUMBER FOURTEEN");
  print_wcwidth(0x24ef, "NEGATIVE CIRCLED NUMBER FIFTEEN");
  print_wcwidth(0x24f0, "NEGATIVE CIRCLED NUMBER SIXTEEN");
  print_wcwidth(0x24f1, "NEGATIVE CIRCLED NUMBER SEVENTEEN");
  print_wcwidth(0x24f2, "NEGATIVE CIRCLED NUMBER EIGHTEEN");
  print_wcwidth(0x24f3, "NEGATIVE CIRCLED NUMBER NINETEEN");
  print_wcwidth(0x24f4, "NEGATIVE CIRCLED NUMBER TWENTY");
  print_wcwidth(0x24f5, "DOUBLE CIRCLED DIGIT ONE");
  print_wcwidth(0x24f6, "DOUBLE CIRCLED DIGIT TWO");
  print_wcwidth(0x24f7, "DOUBLE CIRCLED DIGIT THREE");
  print_wcwidth(0x24f8, "DOUBLE CIRCLED DIGIT FOUR");
  print_wcwidth(0x24f9, "DOUBLE CIRCLED DIGIT FIVE");
  print_wcwidth(0x24fa, "DOUBLE CIRCLED DIGIT SIX");
  print_wcwidth(0x24fb, "DOUBLE CIRCLED DIGIT SEVEN");
  print_wcwidth(0x24fc, "DOUBLE CIRCLED DIGIT EIGHT");
  print_wcwidth(0x24fd, "DOUBLE CIRCLED DIGIT NINE");
  print_wcwidth(0x24fe, "DOUBLE CIRCLED NUMBER TEN");
  print_wcwidth(0x24ff, "NEGATIVE CIRCLED DIGIT ZERO");
  print_wcwidth(0x2500, "BOX DRAWINGS LIGHT HORIZONTAL");
  print_wcwidth(0x2501, "BOX DRAWINGS HEAVY HORIZONTAL");
  print_wcwidth(0x2502, "BOX DRAWINGS LIGHT VERTICAL");
  print_wcwidth(0x2503, "BOX DRAWINGS HEAVY VERTICAL");
  print_wcwidth(0x2504, "BOX DRAWINGS LIGHT TRIPLE DASH HORIZONTAL");
  print_wcwidth(0x2505, "BOX DRAWINGS HEAVY TRIPLE DASH HORIZONTAL");
  print_wcwidth(0x2506, "BOX DRAWINGS LIGHT TRIPLE DASH VERTICAL");
  print_wcwidth(0x2507, "BOX DRAWINGS HEAVY TRIPLE DASH VERTICAL");
  print_wcwidth(0x2508, "BOX DRAWINGS LIGHT QUADRUPLE DASH HORIZONTAL");
  print_wcwidth(0x2509, "BOX DRAWINGS HEAVY QUADRUPLE DASH HORIZONTAL");
  print_wcwidth(0x250a, "BOX DRAWINGS LIGHT QUADRUPLE DASH VERTICAL");
  print_wcwidth(0x250b, "BOX DRAWINGS HEAVY QUADRUPLE DASH VERTICAL");
  print_wcwidth(0x250c, "BOX DRAWINGS LIGHT DOWN AND RIGHT");
  print_wcwidth(0x250d, "BOX DRAWINGS DOWN LIGHT AND RIGHT HEAVY");
  print_wcwidth(0x250e, "BOX DRAWINGS DOWN HEAVY AND RIGHT LIGHT");
  print_wcwidth(0x250f, "BOX DRAWINGS HEAVY DOWN AND RIGHT");
  print_wcwidth(0x2510, "BOX DRAWINGS LIGHT DOWN AND LEFT");
  print_wcwidth(0x2511, "BOX DRAWINGS DOWN LIGHT AND LEFT HEAVY");
  print_wcwidth(0x2512, "BOX DRAWINGS DOWN HEAVY AND LEFT LIGHT");
  print_wcwidth(0x2513, "BOX DRAWINGS HEAVY DOWN AND LEFT");
  print_wcwidth(0x2514, "BOX DRAWINGS LIGHT UP AND RIGHT");
  print_wcwidth(0x2515, "BOX DRAWINGS UP LIGHT AND RIGHT HEAVY");
  print_wcwidth(0x2516, "BOX DRAWINGS UP HEAVY AND RIGHT LIGHT");
  print_wcwidth(0x2517, "BOX DRAWINGS HEAVY UP AND RIGHT");
  print_wcwidth(0x2518, "BOX DRAWINGS LIGHT UP AND LEFT");
  print_wcwidth(0x2519, "BOX DRAWINGS UP LIGHT AND LEFT HEAVY");
  print_wcwidth(0x251a, "BOX DRAWINGS UP HEAVY AND LEFT LIGHT");
  print_wcwidth(0x251b, "BOX DRAWINGS HEAVY UP AND LEFT");
  print_wcwidth(0x251c, "BOX DRAWINGS LIGHT VERTICAL AND RIGHT");
  print_wcwidth(0x251d, "BOX DRAWINGS VERTICAL LIGHT AND RIGHT HEAVY");
  print_wcwidth(0x251e, "BOX DRAWINGS UP HEAVY AND RIGHT DOWN LIGHT");
  print_wcwidth(0x251f, "BOX DRAWINGS DOWN HEAVY AND RIGHT UP LIGHT");
  print_wcwidth(0x2520, "BOX DRAWINGS VERTICAL HEAVY AND RIGHT LIGHT");
  print_wcwidth(0x2521, "BOX DRAWINGS DOWN LIGHT AND RIGHT UP HEAVY");
  print_wcwidth(0x2522, "BOX DRAWINGS UP LIGHT AND RIGHT DOWN HEAVY");
  print_wcwidth(0x2523, "BOX DRAWINGS HEAVY VERTICAL AND RIGHT");
  print_wcwidth(0x2524, "BOX DRAWINGS LIGHT VERTICAL AND LEFT");
  print_wcwidth(0x2525, "BOX DRAWINGS VERTICAL LIGHT AND LEFT HEAVY");
  print_wcwidth(0x2526, "BOX DRAWINGS UP HEAVY AND LEFT DOWN LIGHT");
  print_wcwidth(0x2527, "BOX DRAWINGS DOWN HEAVY AND LEFT UP LIGHT");
  print_wcwidth(0x2528, "BOX DRAWINGS VERTICAL HEAVY AND LEFT LIGHT");
  print_wcwidth(0x2529, "BOX DRAWINGS DOWN LIGHT AND LEFT UP HEAVY");
  print_wcwidth(0x252a, "BOX DRAWINGS UP LIGHT AND LEFT DOWN HEAVY");
  print_wcwidth(0x252b, "BOX DRAWINGS HEAVY VERTICAL AND LEFT");
  print_wcwidth(0x252c, "BOX DRAWINGS LIGHT DOWN AND HORIZONTAL");
  print_wcwidth(0x252d, "BOX DRAWINGS LEFT HEAVY AND RIGHT DOWN LIGHT");
  print_wcwidth(0x252e, "BOX DRAWINGS RIGHT HEAVY AND LEFT DOWN LIGHT");
  print_wcwidth(0x252f, "BOX DRAWINGS DOWN LIGHT AND HORIZONTAL HEAVY");
  print_wcwidth(0x2530, "BOX DRAWINGS DOWN HEAVY AND HORIZONTAL LIGHT");
  print_wcwidth(0x2531, "BOX DRAWINGS RIGHT LIGHT AND LEFT DOWN HEAVY");
  print_wcwidth(0x2532, "BOX DRAWINGS LEFT LIGHT AND RIGHT DOWN HEAVY");
  print_wcwidth(0x2533, "BOX DRAWINGS HEAVY DOWN AND HORIZONTAL");
  print_wcwidth(0x2534, "BOX DRAWINGS LIGHT UP AND HORIZONTAL");
  print_wcwidth(0x2535, "BOX DRAWINGS LEFT HEAVY AND RIGHT UP LIGHT");
  print_wcwidth(0x2536, "BOX DRAWINGS RIGHT HEAVY AND LEFT UP LIGHT");
  print_wcwidth(0x2537, "BOX DRAWINGS UP LIGHT AND HORIZONTAL HEAVY");
  print_wcwidth(0x2538, "BOX DRAWINGS UP HEAVY AND HORIZONTAL LIGHT");
  print_wcwidth(0x2539, "BOX DRAWINGS RIGHT LIGHT AND LEFT UP HEAVY");
  print_wcwidth(0x253a, "BOX DRAWINGS LEFT LIGHT AND RIGHT UP HEAVY");
  print_wcwidth(0x253b, "BOX DRAWINGS HEAVY UP AND HORIZONTAL");
  print_wcwidth(0x253c, "BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL");
  print_wcwidth(0x253d, "BOX DRAWINGS LEFT HEAVY AND RIGHT VERTICAL LIGHT");
  print_wcwidth(0x253e, "BOX DRAWINGS RIGHT HEAVY AND LEFT VERTICAL LIGHT");
  print_wcwidth(0x253f, "BOX DRAWINGS VERTICAL LIGHT AND HORIZONTAL HEAVY");
  print_wcwidth(0x2540, "BOX DRAWINGS UP HEAVY AND DOWN HORIZONTAL LIGHT");
  print_wcwidth(0x2541, "BOX DRAWINGS DOWN HEAVY AND UP HORIZONTAL LIGHT");
  print_wcwidth(0x2542, "BOX DRAWINGS VERTICAL HEAVY AND HORIZONTAL LIGHT");
  print_wcwidth(0x2543, "BOX DRAWINGS LEFT UP HEAVY AND RIGHT DOWN LIGHT");
  print_wcwidth(0x2544, "BOX DRAWINGS RIGHT UP HEAVY AND LEFT DOWN LIGHT");
  print_wcwidth(0x2545, "BOX DRAWINGS LEFT DOWN HEAVY AND RIGHT UP LIGHT");
  print_wcwidth(0x2546, "BOX DRAWINGS RIGHT DOWN HEAVY AND LEFT UP LIGHT");
  print_wcwidth(0x2547, "BOX DRAWINGS DOWN LIGHT AND UP HORIZONTAL HEAVY");
  print_wcwidth(0x2548, "BOX DRAWINGS UP LIGHT AND DOWN HORIZONTAL HEAVY");
  print_wcwidth(0x2549, "BOX DRAWINGS RIGHT LIGHT AND LEFT VERTICAL HEAVY");
  print_wcwidth(0x254a, "BOX DRAWINGS LEFT LIGHT AND RIGHT VERTICAL HEAVY");
  print_wcwidth(0x254b, "BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL");
  print_wcwidth(0x2550, "BOX DRAWINGS DOUBLE HORIZONTAL");
  print_wcwidth(0x2551, "BOX DRAWINGS DOUBLE VERTICAL");
  print_wcwidth(0x2552, "BOX DRAWINGS DOWN SINGLE AND RIGHT DOUBLE");
  print_wcwidth(0x2553, "BOX DRAWINGS DOWN DOUBLE AND RIGHT SINGLE");
  print_wcwidth(0x2554, "BOX DRAWINGS DOUBLE DOWN AND RIGHT");
  print_wcwidth(0x2555, "BOX DRAWINGS DOWN SINGLE AND LEFT DOUBLE");
  print_wcwidth(0x2556, "BOX DRAWINGS DOWN DOUBLE AND LEFT SINGLE");
  print_wcwidth(0x2557, "BOX DRAWINGS DOUBLE DOWN AND LEFT");
  print_wcwidth(0x2558, "BOX DRAWINGS UP SINGLE AND RIGHT DOUBLE");
  print_wcwidth(0x2559, "BOX DRAWINGS UP DOUBLE AND RIGHT SINGLE");
  print_wcwidth(0x255a, "BOX DRAWINGS DOUBLE UP AND RIGHT");
  print_wcwidth(0x255b, "BOX DRAWINGS UP SINGLE AND LEFT DOUBLE");
  print_wcwidth(0x255c, "BOX DRAWINGS UP DOUBLE AND LEFT SINGLE");
  print_wcwidth(0x255d, "BOX DRAWINGS DOUBLE UP AND LEFT");
  print_wcwidth(0x255e, "BOX DRAWINGS VERTICAL SINGLE AND RIGHT DOUBLE");
  print_wcwidth(0x255f, "BOX DRAWINGS VERTICAL DOUBLE AND RIGHT SINGLE");
  print_wcwidth(0x2560, "BOX DRAWINGS DOUBLE VERTICAL AND RIGHT");
  print_wcwidth(0x2561, "BOX DRAWINGS VERTICAL SINGLE AND LEFT DOUBLE");
  print_wcwidth(0x2562, "BOX DRAWINGS VERTICAL DOUBLE AND LEFT SINGLE");
  print_wcwidth(0x2563, "BOX DRAWINGS DOUBLE VERTICAL AND LEFT");
  print_wcwidth(0x2564, "BOX DRAWINGS DOWN SINGLE AND HORIZONTAL DOUBLE");
  print_wcwidth(0x2565, "BOX DRAWINGS DOWN DOUBLE AND HORIZONTAL SINGLE");
  print_wcwidth(0x2566, "BOX DRAWINGS DOUBLE DOWN AND HORIZONTAL");
  print_wcwidth(0x2567, "BOX DRAWINGS UP SINGLE AND HORIZONTAL DOUBLE");
  print_wcwidth(0x2568, "BOX DRAWINGS UP DOUBLE AND HORIZONTAL SINGLE");
  print_wcwidth(0x2569, "BOX DRAWINGS DOUBLE UP AND HORIZONTAL");
  print_wcwidth(0x256a, "BOX DRAWINGS VERTICAL SINGLE AND HORIZONTAL DOUBLE");
  print_wcwidth(0x256b, "BOX DRAWINGS VERTICAL DOUBLE AND HORIZONTAL SINGLE");
  print_wcwidth(0x256c, "BOX DRAWINGS DOUBLE VERTICAL AND HORIZONTAL");
  print_wcwidth(0x256d, "BOX DRAWINGS LIGHT ARC DOWN AND RIGHT");
  print_wcwidth(0x256e, "BOX DRAWINGS LIGHT ARC DOWN AND LEFT");
  print_wcwidth(0x256f, "BOX DRAWINGS LIGHT ARC UP AND LEFT");
  print_wcwidth(0x2570, "BOX DRAWINGS LIGHT ARC UP AND RIGHT");
  print_wcwidth(0x2571, "BOX DRAWINGS LIGHT DIAGONAL UPPER RIGHT TO LOWER LEFT");
  print_wcwidth(0x2572, "BOX DRAWINGS LIGHT DIAGONAL UPPER LEFT TO LOWER RIGHT");
  print_wcwidth(0x2573, "BOX DRAWINGS LIGHT DIAGONAL CROSS");
  print_wcwidth(0x2580, "UPPER HALF BLOCK");
  print_wcwidth(0x2581, "LOWER ONE EIGHTH BLOCK");
  print_wcwidth(0x2582, "LOWER ONE QUARTER BLOCK");
  print_wcwidth(0x2583, "LOWER THREE EIGHTHS BLOCK");
  print_wcwidth(0x2584, "LOWER HALF BLOCK");
  print_wcwidth(0x2585, "LOWER FIVE EIGHTHS BLOCK");
  print_wcwidth(0x2586, "LOWER THREE QUARTERS BLOCK");
  print_wcwidth(0x2587, "LOWER SEVEN EIGHTHS BLOCK");
  print_wcwidth(0x2588, "FULL BLOCK");
  print_wcwidth(0x2589, "LEFT SEVEN EIGHTHS BLOCK");
  print_wcwidth(0x258a, "LEFT THREE QUARTERS BLOCK");
  print_wcwidth(0x258b, "LEFT FIVE EIGHTHS BLOCK");
  print_wcwidth(0x258c, "LEFT HALF BLOCK");
  print_wcwidth(0x258d, "LEFT THREE EIGHTHS BLOCK");
  print_wcwidth(0x258e, "LEFT ONE QUARTER BLOCK");
  print_wcwidth(0x258f, "LEFT ONE EIGHTH BLOCK");
  print_wcwidth(0x2592, "MEDIUM SHADE");
  print_wcwidth(0x2593, "DARK SHADE");
  print_wcwidth(0x2594, "UPPER ONE EIGHTH BLOCK");
  print_wcwidth(0x2595, "RIGHT ONE EIGHTH BLOCK");
  print_wcwidth(0x25a0, "BLACK SQUARE");
  print_wcwidth(0x25a1, "WHITE SQUARE");
  print_wcwidth(0x25a3, "WHITE SQUARE CONTAINING BLACK SMALL SQUARE");
  print_wcwidth(0x25a4, "SQUARE WITH HORIZONTAL FILL");
  print_wcwidth(0x25a5, "SQUARE WITH VERTICAL FILL");
  print_wcwidth(0x25a6, "SQUARE WITH ORTHOGONAL CROSSHATCH FILL");
  print_wcwidth(0x25a7, "SQUARE WITH UPPER LEFT TO LOWER RIGHT FILL");
  print_wcwidth(0x25a8, "SQUARE WITH UPPER RIGHT TO LOWER LEFT FILL");
  print_wcwidth(0x25a9, "SQUARE WITH DIAGONAL CROSSHATCH FILL");
  print_wcwidth(0x25b2, "BLACK UP-POINTING TRIANGLE");
  print_wcwidth(0x25b3, "WHITE UP-POINTING TRIANGLE");
  print_wcwidth(0x25b6, "BLACK RIGHT-POINTING TRIANGLE");
  print_wcwidth(0x25b7, "WHITE RIGHT-POINTING TRIANGLE");
  print_wcwidth(0x25bc, "BLACK DOWN-POINTING TRIANGLE");
  print_wcwidth(0x25bd, "WHITE DOWN-POINTING TRIANGLE");
  print_wcwidth(0x25c0, "BLACK LEFT-POINTING TRIANGLE");
  print_wcwidth(0x25c1, "WHITE LEFT-POINTING TRIANGLE");
  print_wcwidth(0x25c6, "BLACK DIAMOND");
  print_wcwidth(0x25c7, "WHITE DIAMOND");
  print_wcwidth(0x25c8, "WHITE DIAMOND CONTAINING BLACK SMALL DIAMOND");
  print_wcwidth(0x25cb, "WHITE CIRCLE");
  print_wcwidth(0x25ce, "BULLSEYE");
  print_wcwidth(0x25cf, "BLACK CIRCLE");
  print_wcwidth(0x25d0, "CIRCLE WITH LEFT HALF BLACK");
  print_wcwidth(0x25d1, "CIRCLE WITH RIGHT HALF BLACK");
  print_wcwidth(0x25e2, "BLACK LOWER RIGHT TRIANGLE");
  print_wcwidth(0x25e3, "BLACK LOWER LEFT TRIANGLE");
  print_wcwidth(0x25e4, "BLACK UPPER LEFT TRIANGLE");
  print_wcwidth(0x25e5, "BLACK UPPER RIGHT TRIANGLE");
  print_wcwidth(0x25ef, "LARGE CIRCLE");
  print_wcwidth(0x2605, "BLACK STAR");
  print_wcwidth(0x2606, "WHITE STAR");
  print_wcwidth(0x2609, "SUN");
  print_wcwidth(0x260e, "BLACK TELEPHONE");
  print_wcwidth(0x260f, "WHITE TELEPHONE");
  print_wcwidth(0x2614, "UMBRELLA WITH RAIN DROPS");
  print_wcwidth(0x2615, "HOT BEVERAGE");
  print_wcwidth(0x261c, "WHITE LEFT POINTING INDEX");
  print_wcwidth(0x261e, "WHITE RIGHT POINTING INDEX");
  print_wcwidth(0x2640, "FEMALE SIGN");
  print_wcwidth(0x2642, "MALE SIGN");
  print_wcwidth(0x2660, "BLACK SPADE SUIT");
  print_wcwidth(0x2661, "WHITE HEART SUIT");
  print_wcwidth(0x2663, "BLACK CLUB SUIT");
  print_wcwidth(0x2664, "WHITE SPADE SUIT");
  print_wcwidth(0x2665, "BLACK HEART SUIT");
  print_wcwidth(0x2667, "WHITE CLUB SUIT");
  print_wcwidth(0x2668, "HOT SPRINGS");
  print_wcwidth(0x2669, "QUARTER NOTE");
  print_wcwidth(0x266a, "EIGHTH NOTE");
  print_wcwidth(0x266c, "BEAMED SIXTEENTH NOTES");
  print_wcwidth(0x266d, "MUSIC FLAT SIGN");
  print_wcwidth(0x266f, "MUSIC SHARP SIGN");
  print_wcwidth(0x269e, "THREE LINES CONVERGING RIGHT");
  print_wcwidth(0x269f, "THREE LINES CONVERGING LEFT");
  print_wcwidth(0x26be, "BASEBALL");
  print_wcwidth(0x26bf, "SQUARED KEY");
  print_wcwidth(0x26c4, "SNOWMAN WITHOUT SNOW");
  print_wcwidth(0x26c5, "SUN BEHIND CLOUD");
  print_wcwidth(0x26c6, "RAIN");
  print_wcwidth(0x26c7, "BLACK SNOWMAN");
  print_wcwidth(0x26c8, "THUNDER CLOUD AND RAIN");
  print_wcwidth(0x26c9, "TURNED WHITE SHOGI PIECE");
  print_wcwidth(0x26ca, "TURNED BLACK SHOGI PIECE");
  print_wcwidth(0x26cb, "WHITE DIAMOND IN SQUARE");
  print_wcwidth(0x26cc, "CROSSING LANES");
  print_wcwidth(0x26cd, "DISABLED CAR");
  print_wcwidth(0x26cf, "PICK");
  print_wcwidth(0x26d0, "CAR SLIDING");
  print_wcwidth(0x26d1, "HELMET WITH WHITE CROSS");
  print_wcwidth(0x26d2, "CIRCLED CROSSING LANES");
  print_wcwidth(0x26d3, "CHAINS");
  print_wcwidth(0x26d4, "NO ENTRY");
  print_wcwidth(0x26d5, "ALTERNATE ONE-WAY LEFT WAY TRAFFIC");
  print_wcwidth(0x26d6, "BLACK TWO-WAY LEFT WAY TRAFFIC");
  print_wcwidth(0x26d7, "WHITE TWO-WAY LEFT WAY TRAFFIC");
  print_wcwidth(0x26d8, "BLACK LEFT LANE MERGE");
  print_wcwidth(0x26d9, "WHITE LEFT LANE MERGE");
  print_wcwidth(0x26da, "DRIVE SLOW SIGN");
  print_wcwidth(0x26db, "HEAVY WHITE DOWN-POINTING TRIANGLE");
  print_wcwidth(0x26dc, "LEFT CLOSED ENTRY");
  print_wcwidth(0x26dd, "SQUARED SALTIRE");
  print_wcwidth(0x26de, "FALLING DIAGONAL IN WHITE CIRCLE IN BLACK SQUARE");
  print_wcwidth(0x26df, "BLACK TRUCK");
  print_wcwidth(0x26e0, "RESTRICTED LEFT ENTRY-1");
  print_wcwidth(0x26e1, "RESTRICTED LEFT ENTRY-2");
  print_wcwidth(0x26e3, "HEAVY CIRCLE WITH STROKE AND TWO DOTS ABOVE");
  print_wcwidth(0x26e8, "BLACK CROSS ON SHIELD");
  print_wcwidth(0x26e9, "SHINTO SHRINE");
  print_wcwidth(0x26ea, "CHURCH");
  print_wcwidth(0x26eb, "CASTLE");
  print_wcwidth(0x26ec, "HISTORIC SITE");
  print_wcwidth(0x26ed, "GEAR WITHOUT HUB");
  print_wcwidth(0x26ee, "GEAR WITH HANDLES");
  print_wcwidth(0x26ef, "MAP SYMBOL FOR LIGHTHOUSE");
  print_wcwidth(0x26f0, "MOUNTAIN");
  print_wcwidth(0x26f1, "UMBRELLA ON GROUND");
  print_wcwidth(0x26f2, "FOUNTAIN");
  print_wcwidth(0x26f3, "FLAG IN HOLE");
  print_wcwidth(0x26f4, "FERRY");
  print_wcwidth(0x26f5, "SAILBOAT");
  print_wcwidth(0x26f6, "SQUARE FOUR CORNERS");
  print_wcwidth(0x26f7, "SKIER");
  print_wcwidth(0x26f8, "ICE SKATE");
  print_wcwidth(0x26f9, "PERSON WITH BALL");
  print_wcwidth(0x26fa, "TENT");
  print_wcwidth(0x26fb, "JAPANESE BANK SYMBOL");
  print_wcwidth(0x26fc, "HEADSTONE GRAVEYARD SYMBOL");
  print_wcwidth(0x26fd, "FUEL PUMP");
  print_wcwidth(0x26fe, "CUP ON BLACK SQUARE");
  print_wcwidth(0x26ff, "WHITE FLAG WITH HORIZONTAL MIDDLE BLACK STRIPE");
  print_wcwidth(0x273d, "HEAVY TEARDROP-SPOKED ASTERISK");
  print_wcwidth(0x2757, "HEAVY EXCLAMATION MARK SYMBOL");
  print_wcwidth(0x2776, "DINGBAT NEGATIVE CIRCLED DIGIT ONE");
  print_wcwidth(0x2777, "DINGBAT NEGATIVE CIRCLED DIGIT TWO");
  print_wcwidth(0x2778, "DINGBAT NEGATIVE CIRCLED DIGIT THREE");
  print_wcwidth(0x2779, "DINGBAT NEGATIVE CIRCLED DIGIT FOUR");
  print_wcwidth(0x277a, "DINGBAT NEGATIVE CIRCLED DIGIT FIVE");
  print_wcwidth(0x277b, "DINGBAT NEGATIVE CIRCLED DIGIT SIX");
  print_wcwidth(0x277c, "DINGBAT NEGATIVE CIRCLED DIGIT SEVEN");
  print_wcwidth(0x277d, "DINGBAT NEGATIVE CIRCLED DIGIT EIGHT");
  print_wcwidth(0x277e, "DINGBAT NEGATIVE CIRCLED DIGIT NINE");
  print_wcwidth(0x277f, "DINGBAT NEGATIVE CIRCLED NUMBER TEN");
  print_wcwidth(0x2b55, "HEAVY LARGE CIRCLE");
  print_wcwidth(0x2b56, "HEAVY OVAL WITH OVAL INSIDE");
  print_wcwidth(0x2b57, "HEAVY CIRCLE WITH CIRCLE INSIDE");
  print_wcwidth(0x2b58, "HEAVY CIRCLE");
  print_wcwidth(0x2b59, "HEAVY CIRCLED SALTIRE");
  print_wcwidth(0x3248, "CIRCLED NUMBER TEN ON BLACK SQUARE");
  print_wcwidth(0x3249, "CIRCLED NUMBER TWENTY ON BLACK SQUARE");
  print_wcwidth(0x324a, "CIRCLED NUMBER THIRTY ON BLACK SQUARE");
  print_wcwidth(0x324b, "CIRCLED NUMBER FORTY ON BLACK SQUARE");
  print_wcwidth(0x324c, "CIRCLED NUMBER FIFTY ON BLACK SQUARE");
  print_wcwidth(0x324d, "CIRCLED NUMBER SIXTY ON BLACK SQUARE");
  print_wcwidth(0x324e, "CIRCLED NUMBER SEVENTY ON BLACK SQUARE");
  print_wcwidth(0x324f, "CIRCLED NUMBER EIGHTY ON BLACK SQUARE");
  print_wcwidth(0xfffd, "REPLACEMENT CHARACTER");
  print_wcwidth(0x1f100, "DIGIT ZERO FULL STOP");
  print_wcwidth(0x1f101, "DIGIT ZERO COMMA");
  print_wcwidth(0x1f102, "DIGIT ONE COMMA");
  print_wcwidth(0x1f103, "DIGIT TWO COMMA");
  print_wcwidth(0x1f104, "DIGIT THREE COMMA");
  print_wcwidth(0x1f105, "DIGIT FOUR COMMA");
  print_wcwidth(0x1f106, "DIGIT FIVE COMMA");
  print_wcwidth(0x1f107, "DIGIT SIX COMMA");
  print_wcwidth(0x1f108, "DIGIT SEVEN COMMA");
  print_wcwidth(0x1f109, "DIGIT EIGHT COMMA");
  print_wcwidth(0x1f10a, "DIGIT NINE COMMA");
  print_wcwidth(0x1f110, "PARENTHESIZED LATIN CAPITAL LETTER A");
  print_wcwidth(0x1f111, "PARENTHESIZED LATIN CAPITAL LETTER B");
  print_wcwidth(0x1f112, "PARENTHESIZED LATIN CAPITAL LETTER C");
  print_wcwidth(0x1f113, "PARENTHESIZED LATIN CAPITAL LETTER D");
  print_wcwidth(0x1f114, "PARENTHESIZED LATIN CAPITAL LETTER E");
  print_wcwidth(0x1f115, "PARENTHESIZED LATIN CAPITAL LETTER F");
  print_wcwidth(0x1f116, "PARENTHESIZED LATIN CAPITAL LETTER G");
  print_wcwidth(0x1f117, "PARENTHESIZED LATIN CAPITAL LETTER H");
  print_wcwidth(0x1f118, "PARENTHESIZED LATIN CAPITAL LETTER I");
  print_wcwidth(0x1f119, "PARENTHESIZED LATIN CAPITAL LETTER J");
  print_wcwidth(0x1f11a, "PARENTHESIZED LATIN CAPITAL LETTER K");
  print_wcwidth(0x1f11b, "PARENTHESIZED LATIN CAPITAL LETTER L");
  print_wcwidth(0x1f11c, "PARENTHESIZED LATIN CAPITAL LETTER M");
  print_wcwidth(0x1f11d, "PARENTHESIZED LATIN CAPITAL LETTER N");
  print_wcwidth(0x1f11e, "PARENTHESIZED LATIN CAPITAL LETTER O");
  print_wcwidth(0x1f11f, "PARENTHESIZED LATIN CAPITAL LETTER P");
  print_wcwidth(0x1f120, "PARENTHESIZED LATIN CAPITAL LETTER Q");
  print_wcwidth(0x1f121, "PARENTHESIZED LATIN CAPITAL LETTER R");
  print_wcwidth(0x1f122, "PARENTHESIZED LATIN CAPITAL LETTER S");
  print_wcwidth(0x1f123, "PARENTHESIZED LATIN CAPITAL LETTER T");
  print_wcwidth(0x1f124, "PARENTHESIZED LATIN CAPITAL LETTER U");
  print_wcwidth(0x1f125, "PARENTHESIZED LATIN CAPITAL LETTER V");
  print_wcwidth(0x1f126, "PARENTHESIZED LATIN CAPITAL LETTER W");
  print_wcwidth(0x1f127, "PARENTHESIZED LATIN CAPITAL LETTER X");
  print_wcwidth(0x1f128, "PARENTHESIZED LATIN CAPITAL LETTER Y");
  print_wcwidth(0x1f129, "PARENTHESIZED LATIN CAPITAL LETTER Z");
  print_wcwidth(0x1f12a, "TORTOISE SHELL BRACKETED LATIN CAPITAL LETTER S");
  print_wcwidth(0x1f12b, "CIRCLED ITALIC LATIN CAPITAL LETTER C");
  print_wcwidth(0x1f12c, "CIRCLED ITALIC LATIN CAPITAL LETTER R");
  print_wcwidth(0x1f12d, "CIRCLED CD");
  print_wcwidth(0x1f130, "SQUARED LATIN CAPITAL LETTER A");
  print_wcwidth(0x1f131, "SQUARED LATIN CAPITAL LETTER B");
  print_wcwidth(0x1f132, "SQUARED LATIN CAPITAL LETTER C");
  print_wcwidth(0x1f133, "SQUARED LATIN CAPITAL LETTER D");
  print_wcwidth(0x1f134, "SQUARED LATIN CAPITAL LETTER E");
  print_wcwidth(0x1f135, "SQUARED LATIN CAPITAL LETTER F");
  print_wcwidth(0x1f136, "SQUARED LATIN CAPITAL LETTER G");
  print_wcwidth(0x1f137, "SQUARED LATIN CAPITAL LETTER H");
  print_wcwidth(0x1f138, "SQUARED LATIN CAPITAL LETTER I");
  print_wcwidth(0x1f139, "SQUARED LATIN CAPITAL LETTER J");
  print_wcwidth(0x1f13a, "SQUARED LATIN CAPITAL LETTER K");
  print_wcwidth(0x1f13b, "SQUARED LATIN CAPITAL LETTER L");
  print_wcwidth(0x1f13c, "SQUARED LATIN CAPITAL LETTER M");
  print_wcwidth(0x1f13d, "SQUARED LATIN CAPITAL LETTER N");
  print_wcwidth(0x1f13e, "SQUARED LATIN CAPITAL LETTER O");
  print_wcwidth(0x1f13f, "SQUARED LATIN CAPITAL LETTER P");
  print_wcwidth(0x1f140, "SQUARED LATIN CAPITAL LETTER Q");
  print_wcwidth(0x1f141, "SQUARED LATIN CAPITAL LETTER R");
  print_wcwidth(0x1f142, "SQUARED LATIN CAPITAL LETTER S");
  print_wcwidth(0x1f143, "SQUARED LATIN CAPITAL LETTER T");
  print_wcwidth(0x1f144, "SQUARED LATIN CAPITAL LETTER U");
  print_wcwidth(0x1f145, "SQUARED LATIN CAPITAL LETTER V");
  print_wcwidth(0x1f146, "SQUARED LATIN CAPITAL LETTER W");
  print_wcwidth(0x1f147, "SQUARED LATIN CAPITAL LETTER X");
  print_wcwidth(0x1f148, "SQUARED LATIN CAPITAL LETTER Y");
  print_wcwidth(0x1f149, "SQUARED LATIN CAPITAL LETTER Z");
  print_wcwidth(0x1f14a, "SQUARED HV");
  print_wcwidth(0x1f14b, "SQUARED MV");
  print_wcwidth(0x1f14c, "SQUARED SD");
  print_wcwidth(0x1f14d, "SQUARED SS");
  print_wcwidth(0x1f14e, "SQUARED PPV");
  print_wcwidth(0x1f14f, "SQUARED WC");
  print_wcwidth(0x1f150, "NEGATIVE CIRCLED LATIN CAPITAL LETTER A");
  print_wcwidth(0x1f151, "NEGATIVE CIRCLED LATIN CAPITAL LETTER B");
  print_wcwidth(0x1f152, "NEGATIVE CIRCLED LATIN CAPITAL LETTER C");
  print_wcwidth(0x1f153, "NEGATIVE CIRCLED LATIN CAPITAL LETTER D");
  print_wcwidth(0x1f154, "NEGATIVE CIRCLED LATIN CAPITAL LETTER E");
  print_wcwidth(0x1f155, "NEGATIVE CIRCLED LATIN CAPITAL LETTER F");
  print_wcwidth(0x1f156, "NEGATIVE CIRCLED LATIN CAPITAL LETTER G");
  print_wcwidth(0x1f157, "NEGATIVE CIRCLED LATIN CAPITAL LETTER H");
  print_wcwidth(0x1f158, "NEGATIVE CIRCLED LATIN CAPITAL LETTER I");
  print_wcwidth(0x1f159, "NEGATIVE CIRCLED LATIN CAPITAL LETTER J");
  print_wcwidth(0x1f15a, "NEGATIVE CIRCLED LATIN CAPITAL LETTER K");
  print_wcwidth(0x1f15b, "NEGATIVE CIRCLED LATIN CAPITAL LETTER L");
  print_wcwidth(0x1f15c, "NEGATIVE CIRCLED LATIN CAPITAL LETTER M");
  print_wcwidth(0x1f15d, "NEGATIVE CIRCLED LATIN CAPITAL LETTER N");
  print_wcwidth(0x1f15e, "NEGATIVE CIRCLED LATIN CAPITAL LETTER O");
  print_wcwidth(0x1f15f, "NEGATIVE CIRCLED LATIN CAPITAL LETTER P");
  print_wcwidth(0x1f160, "NEGATIVE CIRCLED LATIN CAPITAL LETTER Q");
  print_wcwidth(0x1f161, "NEGATIVE CIRCLED LATIN CAPITAL LETTER R");
  print_wcwidth(0x1f162, "NEGATIVE CIRCLED LATIN CAPITAL LETTER S");
  print_wcwidth(0x1f163, "NEGATIVE CIRCLED LATIN CAPITAL LETTER T");
  print_wcwidth(0x1f164, "NEGATIVE CIRCLED LATIN CAPITAL LETTER U");
  print_wcwidth(0x1f165, "NEGATIVE CIRCLED LATIN CAPITAL LETTER V");
  print_wcwidth(0x1f166, "NEGATIVE CIRCLED LATIN CAPITAL LETTER W");
  print_wcwidth(0x1f167, "NEGATIVE CIRCLED LATIN CAPITAL LETTER X");
  print_wcwidth(0x1f168, "NEGATIVE CIRCLED LATIN CAPITAL LETTER Y");
  print_wcwidth(0x1f169, "NEGATIVE CIRCLED LATIN CAPITAL LETTER Z");
  print_wcwidth(0x1f170, "NEGATIVE SQUARED LATIN CAPITAL LETTER A");
  print_wcwidth(0x1f171, "NEGATIVE SQUARED LATIN CAPITAL LETTER B");
  print_wcwidth(0x1f172, "NEGATIVE SQUARED LATIN CAPITAL LETTER C");
  print_wcwidth(0x1f173, "NEGATIVE SQUARED LATIN CAPITAL LETTER D");
  print_wcwidth(0x1f174, "NEGATIVE SQUARED LATIN CAPITAL LETTER E");
  print_wcwidth(0x1f175, "NEGATIVE SQUARED LATIN CAPITAL LETTER F");
  print_wcwidth(0x1f176, "NEGATIVE SQUARED LATIN CAPITAL LETTER G");
  print_wcwidth(0x1f177, "NEGATIVE SQUARED LATIN CAPITAL LETTER H");
  print_wcwidth(0x1f178, "NEGATIVE SQUARED LATIN CAPITAL LETTER I");
  print_wcwidth(0x1f179, "NEGATIVE SQUARED LATIN CAPITAL LETTER J");
  print_wcwidth(0x1f17a, "NEGATIVE SQUARED LATIN CAPITAL LETTER K");
  print_wcwidth(0x1f17b, "NEGATIVE SQUARED LATIN CAPITAL LETTER L");
  print_wcwidth(0x1f17c, "NEGATIVE SQUARED LATIN CAPITAL LETTER M");
  print_wcwidth(0x1f17d, "NEGATIVE SQUARED LATIN CAPITAL LETTER N");
  print_wcwidth(0x1f17e, "NEGATIVE SQUARED LATIN CAPITAL LETTER O");
  print_wcwidth(0x1f17f, "NEGATIVE SQUARED LATIN CAPITAL LETTER P");
  print_wcwidth(0x1f180, "NEGATIVE SQUARED LATIN CAPITAL LETTER Q");
  print_wcwidth(0x1f181, "NEGATIVE SQUARED LATIN CAPITAL LETTER R");
  print_wcwidth(0x1f182, "NEGATIVE SQUARED LATIN CAPITAL LETTER S");
  print_wcwidth(0x1f183, "NEGATIVE SQUARED LATIN CAPITAL LETTER T");
  print_wcwidth(0x1f184, "NEGATIVE SQUARED LATIN CAPITAL LETTER U");
  print_wcwidth(0x1f185, "NEGATIVE SQUARED LATIN CAPITAL LETTER V");
  print_wcwidth(0x1f186, "NEGATIVE SQUARED LATIN CAPITAL LETTER W");
  print_wcwidth(0x1f187, "NEGATIVE SQUARED LATIN CAPITAL LETTER X");
  print_wcwidth(0x1f188, "NEGATIVE SQUARED LATIN CAPITAL LETTER Y");
  print_wcwidth(0x1f189, "NEGATIVE SQUARED LATIN CAPITAL LETTER Z");
  print_wcwidth(0x1f18a, "CROSSED NEGATIVE SQUARED LATIN CAPITAL LETTER P");
  print_wcwidth(0x1f18b, "NEGATIVE SQUARED IC");
  print_wcwidth(0x1f18c, "NEGATIVE SQUARED PA");
  print_wcwidth(0x1f18d, "NEGATIVE SQUARED SA");
  print_wcwidth(0x1f18e, "NEGATIVE SQUARED AB");
  print_wcwidth(0x1f18f, "NEGATIVE SQUARED WC");
  print_wcwidth(0x1f190, "SQUARE DJ");
  print_wcwidth(0x1f191, "SQUARED CL");
  print_wcwidth(0x1f192, "SQUARED COOL");
  print_wcwidth(0x1f193, "SQUARED FREE");
  print_wcwidth(0x1f194, "SQUARED ID");
  print_wcwidth(0x1f195, "SQUARED NEW");
  print_wcwidth(0x1f196, "SQUARED NG");
  print_wcwidth(0x1f197, "SQUARED OK");
  print_wcwidth(0x1f198, "SQUARED SOS");
  print_wcwidth(0x1f199, "SQUARED UP WITH EXCLAMATION MARK");
  print_wcwidth(0x1f19a, "SQUARED VS");
  return 0;
}
