#define _XOPEN_SOURCE
#include <stdio.h>
#include <locale.h>
#include <wchar.h>

void print_wcwidth(wchar_t c, char *str)
{
  printf("wcwidth('[%lc]') == %d, codepoint [%x], %s\n", c, wcwidth(c), c, str);
}
int main()
{
  setlocale(LC_CTYPE, "");
  print_wcwidth(0xa1, "INVERTED EXCLAMATION MARK");
  print_wcwidth(0xa4, "CURRENCY SIGN");
  print_wcwidth(0xa7, "SECTION SIGN");
  print_wcwidth(0xa8, "DIAERESIS");
  print_wcwidth(0xa9, "COPYRIGHT SIGN");
  print_wcwidth(0xaa, "FEMININE ORDINAL INDICATOR");
  print_wcwidth(0xad, "SOFT HYPHEN");
  print_wcwidth(0xae, "REGISTERED SIGN");
  print_wcwidth(0xb0, "DEGREE SIGN");
  print_wcwidth(0xb1, "PLUS-MINUS SIGN");
  print_wcwidth(0xb2, "SUPERSCRIPT TWO");
  print_wcwidth(0xb3, "SUPERSCRIPT THREE");
  print_wcwidth(0xb4, "ACUTE ACCENT");
  print_wcwidth(0xb6, "PILCROW SIGN");
  print_wcwidth(0xb7, "MIDDLE DOT");
  print_wcwidth(0xb8, "CEDILLA");
  print_wcwidth(0xb9, "SUPERSCRIPT ONE");
  print_wcwidth(0xba, "MASCULINE ORDINAL INDICATOR");
  print_wcwidth(0xbc, "VULGAR FRACTION ONE QUARTER");
  print_wcwidth(0xbd, "VULGAR FRACTION ONE HALF");
  print_wcwidth(0xbe, "VULGAR FRACTION THREE QUARTERS");
  print_wcwidth(0xbf, "INVERTED QUESTION MARK");
  print_wcwidth(0xc6, "LATIN CAPITAL LETTER AE");
  print_wcwidth(0xd0, "LATIN CAPITAL LETTER ETH");
  print_wcwidth(0xd7, "MULTIPLICATION SIGN");
  print_wcwidth(0xd8, "LATIN CAPITAL LETTER O WITH STROKE");
  print_wcwidth(0xde, "LATIN CAPITAL LETTER THORN");
  print_wcwidth(0xdf, "LATIN SMALL LETTER SHARP S");
  print_wcwidth(0xe0, "LATIN SMALL LETTER A WITH GRAVE");
  print_wcwidth(0xe1, "LATIN SMALL LETTER A WITH ACUTE");
  print_wcwidth(0xe6, "LATIN SMALL LETTER AE");
  print_wcwidth(0xe8, "LATIN SMALL LETTER E WITH GRAVE");
  print_wcwidth(0xe9, "LATIN SMALL LETTER E WITH ACUTE");
  print_wcwidth(0xea, "LATIN SMALL LETTER E WITH CIRCUMFLEX");
  print_wcwidth(0xec, "LATIN SMALL LETTER I WITH GRAVE");
  print_wcwidth(0xed, "LATIN SMALL LETTER I WITH ACUTE");
  print_wcwidth(0xf0, "LATIN SMALL LETTER ETH");
  print_wcwidth(0xf2, "LATIN SMALL LETTER O WITH GRAVE");
  print_wcwidth(0xf3, "LATIN SMALL LETTER O WITH ACUTE");
  print_wcwidth(0xf7, "DIVISION SIGN");
  print_wcwidth(0xf8, "LATIN SMALL LETTER O WITH STROKE");
  print_wcwidth(0xf9, "LATIN SMALL LETTER U WITH GRAVE");
  print_wcwidth(0xfa, "LATIN SMALL LETTER U WITH ACUTE");
  print_wcwidth(0xfc, "LATIN SMALL LETTER U WITH DIAERESIS");
  print_wcwidth(0xfe, "LATIN SMALL LETTER THORN");
  print_wcwidth(0x101, "LATIN SMALL LETTER A WITH MACRON");
  print_wcwidth(0x111, "LATIN SMALL LETTER D WITH STROKE");
  print_wcwidth(0x113, "LATIN SMALL LETTER E WITH MACRON");
  print_wcwidth(0x11b, "LATIN SMALL LETTER E WITH CARON");
  print_wcwidth(0x126, "LATIN CAPITAL LETTER H WITH STROKE");
  print_wcwidth(0x127, "LATIN SMALL LETTER H WITH STROKE");
  print_wcwidth(0x12b, "LATIN SMALL LETTER I WITH MACRON");
  print_wcwidth(0x131, "LATIN SMALL LETTER DOTLESS I");
  print_wcwidth(0x132, "LATIN CAPITAL LIGATURE IJ");
  print_wcwidth(0x133, "LATIN SMALL LIGATURE IJ");
  print_wcwidth(0x138, "LATIN SMALL LETTER KRA");
  print_wcwidth(0x13f, "LATIN CAPITAL LETTER L WITH MIDDLE DOT");
  print_wcwidth(0x140, "LATIN SMALL LETTER L WITH MIDDLE DOT");
  print_wcwidth(0x141, "LATIN CAPITAL LETTER L WITH STROKE");
  print_wcwidth(0x142, "LATIN SMALL LETTER L WITH STROKE");
  print_wcwidth(0x144, "LATIN SMALL LETTER N WITH ACUTE");
  print_wcwidth(0x148, "LATIN SMALL LETTER N WITH CARON");
  print_wcwidth(0x149, "LATIN SMALL LETTER N PRECEDED BY APOSTROPHE");
  print_wcwidth(0x14a, "LATIN CAPITAL LETTER ENG");
  print_wcwidth(0x14b, "LATIN SMALL LETTER ENG");
  print_wcwidth(0x14d, "LATIN SMALL LETTER O WITH MACRON");
  print_wcwidth(0x152, "LATIN CAPITAL LIGATURE OE");
  print_wcwidth(0x153, "LATIN SMALL LIGATURE OE");
  print_wcwidth(0x166, "LATIN CAPITAL LETTER T WITH STROKE");
  print_wcwidth(0x167, "LATIN SMALL LETTER T WITH STROKE");
  print_wcwidth(0x16b, "LATIN SMALL LETTER U WITH MACRON");
  print_wcwidth(0x1ce, "LATIN SMALL LETTER A WITH CARON");
  print_wcwidth(0x1d0, "LATIN SMALL LETTER I WITH CARON");
  print_wcwidth(0x1d2, "LATIN SMALL LETTER O WITH CARON");
  print_wcwidth(0x1d4, "LATIN SMALL LETTER U WITH CARON");
  print_wcwidth(0x1d6, "LATIN SMALL LETTER U WITH DIAERESIS AND MACRON");
  print_wcwidth(0x1d8, "LATIN SMALL LETTER U WITH DIAERESIS AND ACUTE");
  print_wcwidth(0x1da, "LATIN SMALL LETTER U WITH DIAERESIS AND CARON");
  print_wcwidth(0x1dc, "LATIN SMALL LETTER U WITH DIAERESIS AND GRAVE");
  print_wcwidth(0x251, "LATIN SMALL LETTER ALPHA");
  print_wcwidth(0x261, "LATIN SMALL LETTER SCRIPT G");
  print_wcwidth(0x2c4, "MODIFIER LETTER UP ARROWHEAD");
  print_wcwidth(0x2c7, "CARON");
  print_wcwidth(0x2c9, "MODIFIER LETTER MACRON");
  print_wcwidth(0x2ca, "MODIFIER LETTER ACUTE ACCENT");
  print_wcwidth(0x2cb, "MODIFIER LETTER GRAVE ACCENT");
  print_wcwidth(0x2cd, "MODIFIER LETTER LOW MACRON");
  print_wcwidth(0x2d0, "MODIFIER LETTER TRIANGULAR COLON");
  print_wcwidth(0x2d8, "BREVE");
  print_wcwidth(0x2d9, "DOT ABOVE");
  print_wcwidth(0x2da, "RING ABOVE");
  print_wcwidth(0x2db, "OGONEK");
  print_wcwidth(0x2dd, "DOUBLE ACUTE ACCENT");
  print_wcwidth(0x2df, "MODIFIER LETTER CROSS ACCENT");
  print_wcwidth(0x391, "GREEK CAPITAL LETTER ALPHA");
  print_wcwidth(0x392, "GREEK CAPITAL LETTER BETA");
  print_wcwidth(0x393, "GREEK CAPITAL LETTER GAMMA");
  print_wcwidth(0x394, "GREEK CAPITAL LETTER DELTA");
  print_wcwidth(0x395, "GREEK CAPITAL LETTER EPSILON");
  print_wcwidth(0x396, "GREEK CAPITAL LETTER ZETA");
  print_wcwidth(0x397, "GREEK CAPITAL LETTER ETA");
  print_wcwidth(0x398, "GREEK CAPITAL LETTER THETA");
  print_wcwidth(0x399, "GREEK CAPITAL LETTER IOTA");
  print_wcwidth(0x39a, "GREEK CAPITAL LETTER KAPPA");
  print_wcwidth(0x39b, "GREEK CAPITAL LETTER LAMDA");
  print_wcwidth(0x39c, "GREEK CAPITAL LETTER MU");
  print_wcwidth(0x39d, "GREEK CAPITAL LETTER NU");
  print_wcwidth(0x39e, "GREEK CAPITAL LETTER XI");
  print_wcwidth(0x39f, "GREEK CAPITAL LETTER OMICRON");
  print_wcwidth(0x3a0, "GREEK CAPITAL LETTER PI");
  print_wcwidth(0x3a1, "GREEK CAPITAL LETTER RHO");
  print_wcwidth(0x3a3, "GREEK CAPITAL LETTER SIGMA");
  print_wcwidth(0x3a4, "GREEK CAPITAL LETTER TAU");
  print_wcwidth(0x3a5, "GREEK CAPITAL LETTER UPSILON");
  print_wcwidth(0x3a6, "GREEK CAPITAL LETTER PHI");
  print_wcwidth(0x3a7, "GREEK CAPITAL LETTER CHI");
  print_wcwidth(0x3a8, "GREEK CAPITAL LETTER PSI");
  print_wcwidth(0x3a9, "GREEK CAPITAL LETTER OMEGA");
  print_wcwidth(0x3b1, "GREEK SMALL LETTER ALPHA");
  print_wcwidth(0x3b2, "GREEK SMALL LETTER BETA");
  print_wcwidth(0x3b3, "GREEK SMALL LETTER GAMMA");
  print_wcwidth(0x3b4, "GREEK SMALL LETTER DELTA");
  print_wcwidth(0x3b5, "GREEK SMALL LETTER EPSILON");
  print_wcwidth(0x3b6, "GREEK SMALL LETTER ZETA");
  print_wcwidth(0x3b7, "GREEK SMALL LETTER ETA");
  print_wcwidth(0x3b8, "GREEK SMALL LETTER THETA");
  print_wcwidth(0x3b9, "GREEK SMALL LETTER IOTA");
  print_wcwidth(0x3ba, "GREEK SMALL LETTER KAPPA");
  print_wcwidth(0x3bb, "GREEK SMALL LETTER LAMDA");
  print_wcwidth(0x3bc, "GREEK SMALL LETTER MU");
  print_wcwidth(0x3bd, "GREEK SMALL LETTER NU");
  print_wcwidth(0x3be, "GREEK SMALL LETTER XI");
  print_wcwidth(0x3bf, "GREEK SMALL LETTER OMICRON");
  print_wcwidth(0x3c0, "GREEK SMALL LETTER PI");
  print_wcwidth(0x3c1, "GREEK SMALL LETTER RHO");
  print_wcwidth(0x3c3, "GREEK SMALL LETTER SIGMA");
  print_wcwidth(0x3c4, "GREEK SMALL LETTER TAU");
  print_wcwidth(0x3c5, "GREEK SMALL LETTER UPSILON");
  print_wcwidth(0x3c6, "GREEK SMALL LETTER PHI");
  print_wcwidth(0x3c7, "GREEK SMALL LETTER CHI");
  print_wcwidth(0x3c8, "GREEK SMALL LETTER PSI");
  print_wcwidth(0x3c9, "GREEK SMALL LETTER OMEGA");
  print_wcwidth(0x401, "CYRILLIC CAPITAL LETTER IO");
  print_wcwidth(0x410, "CYRILLIC CAPITAL LETTER A");
  print_wcwidth(0x411, "CYRILLIC CAPITAL LETTER BE");
  print_wcwidth(0x412, "CYRILLIC CAPITAL LETTER VE");
  print_wcwidth(0x413, "CYRILLIC CAPITAL LETTER GHE");
  print_wcwidth(0x414, "CYRILLIC CAPITAL LETTER DE");
  print_wcwidth(0x415, "CYRILLIC CAPITAL LETTER IE");
  print_wcwidth(0x416, "CYRILLIC CAPITAL LETTER ZHE");
  print_wcwidth(0x417, "CYRILLIC CAPITAL LETTER ZE");
  print_wcwidth(0x418, "CYRILLIC CAPITAL LETTER I");
  print_wcwidth(0x419, "CYRILLIC CAPITAL LETTER SHORT I");
  print_wcwidth(0x41a, "CYRILLIC CAPITAL LETTER KA");
  print_wcwidth(0x41b, "CYRILLIC CAPITAL LETTER EL");
  print_wcwidth(0x41c, "CYRILLIC CAPITAL LETTER EM");
  print_wcwidth(0x41d, "CYRILLIC CAPITAL LETTER EN");
  print_wcwidth(0x41e, "CYRILLIC CAPITAL LETTER O");
  print_wcwidth(0x41f, "CYRILLIC CAPITAL LETTER PE");
  print_wcwidth(0x420, "CYRILLIC CAPITAL LETTER ER");
  print_wcwidth(0x421, "CYRILLIC CAPITAL LETTER ES");
  print_wcwidth(0x422, "CYRILLIC CAPITAL LETTER TE");
  print_wcwidth(0x423, "CYRILLIC CAPITAL LETTER U");
  print_wcwidth(0x424, "CYRILLIC CAPITAL LETTER EF");
  print_wcwidth(0x425, "CYRILLIC CAPITAL LETTER HA");
  print_wcwidth(0x426, "CYRILLIC CAPITAL LETTER TSE");
  print_wcwidth(0x427, "CYRILLIC CAPITAL LETTER CHE");
  print_wcwidth(0x428, "CYRILLIC CAPITAL LETTER SHA");
  print_wcwidth(0x429, "CYRILLIC CAPITAL LETTER SHCHA");
  print_wcwidth(0x42a, "CYRILLIC CAPITAL LETTER HARD SIGN");
  print_wcwidth(0x42b, "CYRILLIC CAPITAL LETTER YERU");
  print_wcwidth(0x42c, "CYRILLIC CAPITAL LETTER SOFT SIGN");
  print_wcwidth(0x42d, "CYRILLIC CAPITAL LETTER E");
  print_wcwidth(0x42e, "CYRILLIC CAPITAL LETTER YU");
  print_wcwidth(0x42f, "CYRILLIC CAPITAL LETTER YA");
  print_wcwidth(0x430, "CYRILLIC SMALL LETTER A");
  print_wcwidth(0x431, "CYRILLIC SMALL LETTER BE");
  print_wcwidth(0x432, "CYRILLIC SMALL LETTER VE");
  print_wcwidth(0x433, "CYRILLIC SMALL LETTER GHE");
  print_wcwidth(0x434, "CYRILLIC SMALL LETTER DE");
  print_wcwidth(0x435, "CYRILLIC SMALL LETTER IE");
  print_wcwidth(0x436, "CYRILLIC SMALL LETTER ZHE");
  print_wcwidth(0x437, "CYRILLIC SMALL LETTER ZE");
  print_wcwidth(0x438, "CYRILLIC SMALL LETTER I");
  print_wcwidth(0x439, "CYRILLIC SMALL LETTER SHORT I");
  print_wcwidth(0x43a, "CYRILLIC SMALL LETTER KA");
  print_wcwidth(0x43b, "CYRILLIC SMALL LETTER EL");
  print_wcwidth(0x43c, "CYRILLIC SMALL LETTER EM");
  print_wcwidth(0x43d, "CYRILLIC SMALL LETTER EN");
  print_wcwidth(0x43e, "CYRILLIC SMALL LETTER O");
  print_wcwidth(0x43f, "CYRILLIC SMALL LETTER PE");
  print_wcwidth(0x440, "CYRILLIC SMALL LETTER ER");
  print_wcwidth(0x441, "CYRILLIC SMALL LETTER ES");
  print_wcwidth(0x442, "CYRILLIC SMALL LETTER TE");
  print_wcwidth(0x443, "CYRILLIC SMALL LETTER U");
  print_wcwidth(0x444, "CYRILLIC SMALL LETTER EF");
  print_wcwidth(0x445, "CYRILLIC SMALL LETTER HA");
  print_wcwidth(0x446, "CYRILLIC SMALL LETTER TSE");
  print_wcwidth(0x447, "CYRILLIC SMALL LETTER CHE");
  print_wcwidth(0x448, "CYRILLIC SMALL LETTER SHA");
  print_wcwidth(0x449, "CYRILLIC SMALL LETTER SHCHA");
  print_wcwidth(0x44a, "CYRILLIC SMALL LETTER HARD SIGN");
  print_wcwidth(0x44b, "CYRILLIC SMALL LETTER YERU");
  print_wcwidth(0x44c, "CYRILLIC SMALL LETTER SOFT SIGN");
  print_wcwidth(0x44d, "CYRILLIC SMALL LETTER E");
  print_wcwidth(0x44e, "CYRILLIC SMALL LETTER YU");
  print_wcwidth(0x44f, "CYRILLIC SMALL LETTER YA");
  print_wcwidth(0x451, "CYRILLIC SMALL LETTER IO");
  print_wcwidth(0x2010, "HYPHEN");
  print_wcwidth(0x2013, "EN DASH");
  print_wcwidth(0x2014, "EM DASH");
  print_wcwidth(0x2015, "HORIZONTAL BAR");
  print_wcwidth(0x2016, "DOUBLE VERTICAL LINE");
  print_wcwidth(0x2018, "LEFT SINGLE QUOTATION MARK");
  print_wcwidth(0x2019, "RIGHT SINGLE QUOTATION MARK");
  print_wcwidth(0x201c, "LEFT DOUBLE QUOTATION MARK");
  print_wcwidth(0x201d, "RIGHT DOUBLE QUOTATION MARK");
  print_wcwidth(0x2020, "DAGGER");
  print_wcwidth(0x2021, "DOUBLE DAGGER");
  print_wcwidth(0x2022, "BULLET");
  print_wcwidth(0x2024, "ONE DOT LEADER");
  print_wcwidth(0x2025, "TWO DOT LEADER");
  print_wcwidth(0x2026, "HORIZONTAL ELLIPSIS");
  print_wcwidth(0x2027, "HYPHENATION POINT");
  print_wcwidth(0x2030, "PER MILLE SIGN");
  print_wcwidth(0x2032, "PRIME");
  print_wcwidth(0x2033, "DOUBLE PRIME");
  print_wcwidth(0x2035, "REVERSED PRIME");
  print_wcwidth(0x203b, "REFERENCE MARK");
  print_wcwidth(0x203c, "DOUBLE EXCLAMATION MARK");
  print_wcwidth(0x203e, "OVERLINE");
  print_wcwidth(0x2049, "EXCLAMATION QUESTION MARK");
  print_wcwidth(0x2074, "SUPERSCRIPT FOUR");
  print_wcwidth(0x207f, "SUPERSCRIPT LATIN SMALL LETTER N");
  print_wcwidth(0x2081, "SUBSCRIPT ONE");
  print_wcwidth(0x2082, "SUBSCRIPT TWO");
  print_wcwidth(0x2083, "SUBSCRIPT THREE");
  print_wcwidth(0x2084, "SUBSCRIPT FOUR");
  print_wcwidth(0x20ac, "EURO SIGN");
  print_wcwidth(0x2103, "DEGREE CELSIUS");
  print_wcwidth(0x2105, "CARE OF");
  print_wcwidth(0x2109, "DEGREE FAHRENHEIT");
  print_wcwidth(0x2113, "SCRIPT SMALL L");
  print_wcwidth(0x2116, "NUMERO SIGN");
  print_wcwidth(0x2121, "TELEPHONE SIGN");
  print_wcwidth(0x2122, "TRADE MARK SIGN");
  print_wcwidth(0x2126, "OHM SIGN");
  print_wcwidth(0x212b, "ANGSTROM SIGN");
  print_wcwidth(0x2139, "INFORMATION SOURCE");
  print_wcwidth(0x2153, "VULGAR FRACTION ONE THIRD");
  print_wcwidth(0x2154, "VULGAR FRACTION TWO THIRDS");
  print_wcwidth(0x215b, "VULGAR FRACTION ONE EIGHTH");
  print_wcwidth(0x215c, "VULGAR FRACTION THREE EIGHTHS");
  print_wcwidth(0x215d, "VULGAR FRACTION FIVE EIGHTHS");
  print_wcwidth(0x215e, "VULGAR FRACTION SEVEN EIGHTHS");
  print_wcwidth(0x2160, "ROMAN NUMERAL ONE");
  print_wcwidth(0x2161, "ROMAN NUMERAL TWO");
  print_wcwidth(0x2162, "ROMAN NUMERAL THREE");
  print_wcwidth(0x2163, "ROMAN NUMERAL FOUR");
  print_wcwidth(0x2164, "ROMAN NUMERAL FIVE");
  print_wcwidth(0x2165, "ROMAN NUMERAL SIX");
  print_wcwidth(0x2166, "ROMAN NUMERAL SEVEN");
  print_wcwidth(0x2167, "ROMAN NUMERAL EIGHT");
  print_wcwidth(0x2168, "ROMAN NUMERAL NINE");
  print_wcwidth(0x2169, "ROMAN NUMERAL TEN");
  print_wcwidth(0x216a, "ROMAN NUMERAL ELEVEN");
  print_wcwidth(0x216b, "ROMAN NUMERAL TWELVE");
  print_wcwidth(0x2170, "SMALL ROMAN NUMERAL ONE");
  print_wcwidth(0x2171, "SMALL ROMAN NUMERAL TWO");
  print_wcwidth(0x2172, "SMALL ROMAN NUMERAL THREE");
  print_wcwidth(0x2173, "SMALL ROMAN NUMERAL FOUR");
  print_wcwidth(0x2174, "SMALL ROMAN NUMERAL FIVE");
  print_wcwidth(0x2175, "SMALL ROMAN NUMERAL SIX");
  print_wcwidth(0x2176, "SMALL ROMAN NUMERAL SEVEN");
  print_wcwidth(0x2177, "SMALL ROMAN NUMERAL EIGHT");
  print_wcwidth(0x2178, "SMALL ROMAN NUMERAL NINE");
  print_wcwidth(0x2179, "SMALL ROMAN NUMERAL TEN");
  print_wcwidth(0x2189, "VULGAR FRACTION ZERO THIRDS");
  print_wcwidth(0x2190, "LEFTWARDS ARROW");
  print_wcwidth(0x2191, "UPWARDS ARROW");
  print_wcwidth(0x2192, "RIGHTWARDS ARROW");
  print_wcwidth(0x2193, "DOWNWARDS ARROW");
  print_wcwidth(0x2194, "LEFT RIGHT ARROW");
  print_wcwidth(0x2195, "UP DOWN ARROW");
  print_wcwidth(0x2196, "NORTH WEST ARROW");
  print_wcwidth(0x2197, "NORTH EAST ARROW");
  print_wcwidth(0x2198, "SOUTH EAST ARROW");
  print_wcwidth(0x2199, "SOUTH WEST ARROW");
  print_wcwidth(0x21a9, "LEFTWARDS ARROW WITH HOOK");
  print_wcwidth(0x21aa, "RIGHTWARDS ARROW WITH HOOK");
  print_wcwidth(0x21b8, "NORTH WEST ARROW TO LONG BAR");
  print_wcwidth(0x21b9, "LEFTWARDS ARROW TO BAR OVER RIGHTWARDS ARROW TO BAR");
  print_wcwidth(0x21d2, "RIGHTWARDS DOUBLE ARROW");
  print_wcwidth(0x21d4, "LEFT RIGHT DOUBLE ARROW");
  print_wcwidth(0x21e7, "UPWARDS WHITE ARROW");
  print_wcwidth(0x2200, "FOR ALL");
  print_wcwidth(0x2202, "PARTIAL DIFFERENTIAL");
  print_wcwidth(0x2203, "THERE EXISTS");
  print_wcwidth(0x2207, "NABLA");
  print_wcwidth(0x2208, "ELEMENT OF");
  print_wcwidth(0x220b, "CONTAINS AS MEMBER");
  print_wcwidth(0x220f, "N-ARY PRODUCT");
  print_wcwidth(0x2211, "N-ARY SUMMATION");
  print_wcwidth(0x2215, "DIVISION SLASH");
  print_wcwidth(0x221a, "SQUARE ROOT");
  print_wcwidth(0x221d, "PROPORTIONAL TO");
  print_wcwidth(0x221e, "INFINITY");
  print_wcwidth(0x221f, "RIGHT ANGLE");
  print_wcwidth(0x2220, "ANGLE");
  print_wcwidth(0x2223, "DIVIDES");
  print_wcwidth(0x2225, "PARALLEL TO");
  print_wcwidth(0x2227, "LOGICAL AND");
  print_wcwidth(0x2228, "LOGICAL OR");
  print_wcwidth(0x2229, "INTERSECTION");
  print_wcwidth(0x222a, "UNION");
  print_wcwidth(0x222b, "INTEGRAL");
  print_wcwidth(0x222c, "DOUBLE INTEGRAL");
  print_wcwidth(0x222e, "CONTOUR INTEGRAL");
  print_wcwidth(0x2234, "THEREFORE");
  print_wcwidth(0x2235, "BECAUSE");
  print_wcwidth(0x2236, "RATIO");
  print_wcwidth(0x2237, "PROPORTION");
  print_wcwidth(0x223c, "TILDE OPERATOR");
  print_wcwidth(0x223d, "REVERSED TILDE");
  print_wcwidth(0x2248, "ALMOST EQUAL TO");
  print_wcwidth(0x224c, "ALL EQUAL TO");
  print_wcwidth(0x2252, "APPROXIMATELY EQUAL TO OR THE IMAGE OF");
  print_wcwidth(0x2260, "NOT EQUAL TO");
  print_wcwidth(0x2261, "IDENTICAL TO");
  print_wcwidth(0x2264, "LESS-THAN OR EQUAL TO");
  print_wcwidth(0x2265, "GREATER-THAN OR EQUAL TO");
  print_wcwidth(0x2266, "LESS-THAN OVER EQUAL TO");
  print_wcwidth(0x2267, "GREATER-THAN OVER EQUAL TO");
  print_wcwidth(0x226a, "MUCH LESS-THAN");
  print_wcwidth(0x226b, "MUCH GREATER-THAN");
  print_wcwidth(0x226e, "NOT LESS-THAN");
  print_wcwidth(0x226f, "NOT GREATER-THAN");
  print_wcwidth(0x2282, "SUBSET OF");
  print_wcwidth(0x2283, "SUPERSET OF");
  print_wcwidth(0x2286, "SUBSET OF OR EQUAL TO");
  print_wcwidth(0x2287, "SUPERSET OF OR EQUAL TO");
  print_wcwidth(0x2295, "CIRCLED PLUS");
  print_wcwidth(0x2299, "CIRCLED DOT OPERATOR");
  print_wcwidth(0x22a5, "UP TACK");
  print_wcwidth(0x22bf, "RIGHT TRIANGLE");
  print_wcwidth(0x2312, "ARC");
  print_wcwidth(0x231a, "WATCH");
  print_wcwidth(0x231b, "HOURGLASS");
  print_wcwidth(0x2328, "KEYBOARD");
  print_wcwidth(0x23cf, "EJECT SYMBOL");
  print_wcwidth(0x23e9, "BLACK RIGHT-POINTING DOUBLE TRIANGLE");
  print_wcwidth(0x23ea, "BLACK LEFT-POINTING DOUBLE TRIANGLE");
  print_wcwidth(0x23eb, "BLACK UP-POINTING DOUBLE TRIANGLE");
  print_wcwidth(0x23ec, "BLACK DOWN-POINTING DOUBLE TRIANGLE");
  print_wcwidth(0x23ed, "BLACK RIGHT-POINTING DOUBLE TRIANGLE WITH VERTICAL BAR");
  print_wcwidth(0x23ee, "BLACK LEFT-POINTING DOUBLE TRIANGLE WITH VERTICAL BAR");
  print_wcwidth(0x23ef, "BLACK RIGHT-POINTING TRIANGLE WITH DOUBLE VERTICAL BAR");
  print_wcwidth(0x23f0, "ALARM CLOCK");
  print_wcwidth(0x23f1, "STOPWATCH");
  print_wcwidth(0x23f2, "TIMER CLOCK");
  print_wcwidth(0x23f3, "HOURGLASS WITH FLOWING SAND");
  print_wcwidth(0x23f8, "DOUBLE VERTICAL BAR");
  print_wcwidth(0x23f9, "BLACK SQUARE FOR STOP");
  print_wcwidth(0x23fa, "BLACK CIRCLE FOR RECORD");
  print_wcwidth(0x2460, "CIRCLED DIGIT ONE");
  print_wcwidth(0x2461, "CIRCLED DIGIT TWO");
  print_wcwidth(0x2462, "CIRCLED DIGIT THREE");
  print_wcwidth(0x2463, "CIRCLED DIGIT FOUR");
  print_wcwidth(0x2464, "CIRCLED DIGIT FIVE");
  print_wcwidth(0x2465, "CIRCLED DIGIT SIX");
  print_wcwidth(0x2466, "CIRCLED DIGIT SEVEN");
  print_wcwidth(0x2467, "CIRCLED DIGIT EIGHT");
  print_wcwidth(0x2468, "CIRCLED DIGIT NINE");
  print_wcwidth(0x2469, "CIRCLED NUMBER TEN");
  print_wcwidth(0x246a, "CIRCLED NUMBER ELEVEN");
  print_wcwidth(0x246b, "CIRCLED NUMBER TWELVE");
  print_wcwidth(0x246c, "CIRCLED NUMBER THIRTEEN");
  print_wcwidth(0x246d, "CIRCLED NUMBER FOURTEEN");
  print_wcwidth(0x246e, "CIRCLED NUMBER FIFTEEN");
  print_wcwidth(0x246f, "CIRCLED NUMBER SIXTEEN");
  print_wcwidth(0x2470, "CIRCLED NUMBER SEVENTEEN");
  print_wcwidth(0x2471, "CIRCLED NUMBER EIGHTEEN");
  print_wcwidth(0x2472, "CIRCLED NUMBER NINETEEN");
  print_wcwidth(0x2473, "CIRCLED NUMBER TWENTY");
  print_wcwidth(0x2474, "PARENTHESIZED DIGIT ONE");
  print_wcwidth(0x2475, "PARENTHESIZED DIGIT TWO");
  print_wcwidth(0x2476, "PARENTHESIZED DIGIT THREE");
  print_wcwidth(0x2477, "PARENTHESIZED DIGIT FOUR");
  print_wcwidth(0x2478, "PARENTHESIZED DIGIT FIVE");
  print_wcwidth(0x2479, "PARENTHESIZED DIGIT SIX");
  print_wcwidth(0x247a, "PARENTHESIZED DIGIT SEVEN");
  print_wcwidth(0x247b, "PARENTHESIZED DIGIT EIGHT");
  print_wcwidth(0x247c, "PARENTHESIZED DIGIT NINE");
  print_wcwidth(0x247d, "PARENTHESIZED NUMBER TEN");
  print_wcwidth(0x247e, "PARENTHESIZED NUMBER ELEVEN");
  print_wcwidth(0x247f, "PARENTHESIZED NUMBER TWELVE");
  print_wcwidth(0x2480, "PARENTHESIZED NUMBER THIRTEEN");
  print_wcwidth(0x2481, "PARENTHESIZED NUMBER FOURTEEN");
  print_wcwidth(0x2482, "PARENTHESIZED NUMBER FIFTEEN");
  print_wcwidth(0x2483, "PARENTHESIZED NUMBER SIXTEEN");
  print_wcwidth(0x2484, "PARENTHESIZED NUMBER SEVENTEEN");
  print_wcwidth(0x2485, "PARENTHESIZED NUMBER EIGHTEEN");
  print_wcwidth(0x2486, "PARENTHESIZED NUMBER NINETEEN");
  print_wcwidth(0x2487, "PARENTHESIZED NUMBER TWENTY");
  print_wcwidth(0x2488, "DIGIT ONE FULL STOP");
  print_wcwidth(0x2489, "DIGIT TWO FULL STOP");
  print_wcwidth(0x248a, "DIGIT THREE FULL STOP");
  print_wcwidth(0x248b, "DIGIT FOUR FULL STOP");
  print_wcwidth(0x248c, "DIGIT FIVE FULL STOP");
  print_wcwidth(0x248d, "DIGIT SIX FULL STOP");
  print_wcwidth(0x248e, "DIGIT SEVEN FULL STOP");
  print_wcwidth(0x248f, "DIGIT EIGHT FULL STOP");
  print_wcwidth(0x2490, "DIGIT NINE FULL STOP");
  print_wcwidth(0x2491, "NUMBER TEN FULL STOP");
  print_wcwidth(0x2492, "NUMBER ELEVEN FULL STOP");
  print_wcwidth(0x2493, "NUMBER TWELVE FULL STOP");
  print_wcwidth(0x2494, "NUMBER THIRTEEN FULL STOP");
  print_wcwidth(0x2495, "NUMBER FOURTEEN FULL STOP");
  print_wcwidth(0x2496, "NUMBER FIFTEEN FULL STOP");
  print_wcwidth(0x2497, "NUMBER SIXTEEN FULL STOP");
  print_wcwidth(0x2498, "NUMBER SEVENTEEN FULL STOP");
  print_wcwidth(0x2499, "NUMBER EIGHTEEN FULL STOP");
  print_wcwidth(0x249a, "NUMBER NINETEEN FULL STOP");
  print_wcwidth(0x249b, "NUMBER TWENTY FULL STOP");
  print_wcwidth(0x249c, "PARENTHESIZED LATIN SMALL LETTER A");
  print_wcwidth(0x249d, "PARENTHESIZED LATIN SMALL LETTER B");
  print_wcwidth(0x249e, "PARENTHESIZED LATIN SMALL LETTER C");
  print_wcwidth(0x249f, "PARENTHESIZED LATIN SMALL LETTER D");
  print_wcwidth(0x24a0, "PARENTHESIZED LATIN SMALL LETTER E");
  print_wcwidth(0x24a1, "PARENTHESIZED LATIN SMALL LETTER F");
  print_wcwidth(0x24a2, "PARENTHESIZED LATIN SMALL LETTER G");
  print_wcwidth(0x24a3, "PARENTHESIZED LATIN SMALL LETTER H");
  print_wcwidth(0x24a4, "PARENTHESIZED LATIN SMALL LETTER I");
  print_wcwidth(0x24a5, "PARENTHESIZED LATIN SMALL LETTER J");
  print_wcwidth(0x24a6, "PARENTHESIZED LATIN SMALL LETTER K");
  print_wcwidth(0x24a7, "PARENTHESIZED LATIN SMALL LETTER L");
  print_wcwidth(0x24a8, "PARENTHESIZED LATIN SMALL LETTER M");
  print_wcwidth(0x24a9, "PARENTHESIZED LATIN SMALL LETTER N");
  print_wcwidth(0x24aa, "PARENTHESIZED LATIN SMALL LETTER O");
  print_wcwidth(0x24ab, "PARENTHESIZED LATIN SMALL LETTER P");
  print_wcwidth(0x24ac, "PARENTHESIZED LATIN SMALL LETTER Q");
  print_wcwidth(0x24ad, "PARENTHESIZED LATIN SMALL LETTER R");
  print_wcwidth(0x24ae, "PARENTHESIZED LATIN SMALL LETTER S");
  print_wcwidth(0x24af, "PARENTHESIZED LATIN SMALL LETTER T");
  print_wcwidth(0x24b0, "PARENTHESIZED LATIN SMALL LETTER U");
  print_wcwidth(0x24b1, "PARENTHESIZED LATIN SMALL LETTER V");
  print_wcwidth(0x24b2, "PARENTHESIZED LATIN SMALL LETTER W");
  print_wcwidth(0x24b3, "PARENTHESIZED LATIN SMALL LETTER X");
  print_wcwidth(0x24b4, "PARENTHESIZED LATIN SMALL LETTER Y");
  print_wcwidth(0x24b5, "PARENTHESIZED LATIN SMALL LETTER Z");
  print_wcwidth(0x24b6, "CIRCLED LATIN CAPITAL LETTER A");
  print_wcwidth(0x24b7, "CIRCLED LATIN CAPITAL LETTER B");
  print_wcwidth(0x24b8, "CIRCLED LATIN CAPITAL LETTER C");
  print_wcwidth(0x24b9, "CIRCLED LATIN CAPITAL LETTER D");
  print_wcwidth(0x24ba, "CIRCLED LATIN CAPITAL LETTER E");
  print_wcwidth(0x24bb, "CIRCLED LATIN CAPITAL LETTER F");
  print_wcwidth(0x24bc, "CIRCLED LATIN CAPITAL LETTER G");
  print_wcwidth(0x24bd, "CIRCLED LATIN CAPITAL LETTER H");
  print_wcwidth(0x24be, "CIRCLED LATIN CAPITAL LETTER I");
  print_wcwidth(0x24bf, "CIRCLED LATIN CAPITAL LETTER J");
  print_wcwidth(0x24c0, "CIRCLED LATIN CAPITAL LETTER K");
  print_wcwidth(0x24c1, "CIRCLED LATIN CAPITAL LETTER L");
  print_wcwidth(0x24c2, "CIRCLED LATIN CAPITAL LETTER M");
  print_wcwidth(0x24c3, "CIRCLED LATIN CAPITAL LETTER N");
  print_wcwidth(0x24c4, "CIRCLED LATIN CAPITAL LETTER O");
  print_wcwidth(0x24c5, "CIRCLED LATIN CAPITAL LETTER P");
  print_wcwidth(0x24c6, "CIRCLED LATIN CAPITAL LETTER Q");
  print_wcwidth(0x24c7, "CIRCLED LATIN CAPITAL LETTER R");
  print_wcwidth(0x24c8, "CIRCLED LATIN CAPITAL LETTER S");
  print_wcwidth(0x24c9, "CIRCLED LATIN CAPITAL LETTER T");
  print_wcwidth(0x24ca, "CIRCLED LATIN CAPITAL LETTER U");
  print_wcwidth(0x24cb, "CIRCLED LATIN CAPITAL LETTER V");
  print_wcwidth(0x24cc, "CIRCLED LATIN CAPITAL LETTER W");
  print_wcwidth(0x24cd, "CIRCLED LATIN CAPITAL LETTER X");
  print_wcwidth(0x24ce, "CIRCLED LATIN CAPITAL LETTER Y");
  print_wcwidth(0x24cf, "CIRCLED LATIN CAPITAL LETTER Z");
  print_wcwidth(0x24d0, "CIRCLED LATIN SMALL LETTER A");
  print_wcwidth(0x24d1, "CIRCLED LATIN SMALL LETTER B");
  print_wcwidth(0x24d2, "CIRCLED LATIN SMALL LETTER C");
  print_wcwidth(0x24d3, "CIRCLED LATIN SMALL LETTER D");
  print_wcwidth(0x24d4, "CIRCLED LATIN SMALL LETTER E");
  print_wcwidth(0x24d5, "CIRCLED LATIN SMALL LETTER F");
  print_wcwidth(0x24d6, "CIRCLED LATIN SMALL LETTER G");
  print_wcwidth(0x24d7, "CIRCLED LATIN SMALL LETTER H");
  print_wcwidth(0x24d8, "CIRCLED LATIN SMALL LETTER I");
  print_wcwidth(0x24d9, "CIRCLED LATIN SMALL LETTER J");
  print_wcwidth(0x24da, "CIRCLED LATIN SMALL LETTER K");
  print_wcwidth(0x24db, "CIRCLED LATIN SMALL LETTER L");
  print_wcwidth(0x24dc, "CIRCLED LATIN SMALL LETTER M");
  print_wcwidth(0x24dd, "CIRCLED LATIN SMALL LETTER N");
  print_wcwidth(0x24de, "CIRCLED LATIN SMALL LETTER O");
  print_wcwidth(0x24df, "CIRCLED LATIN SMALL LETTER P");
  print_wcwidth(0x24e0, "CIRCLED LATIN SMALL LETTER Q");
  print_wcwidth(0x24e1, "CIRCLED LATIN SMALL LETTER R");
  print_wcwidth(0x24e2, "CIRCLED LATIN SMALL LETTER S");
  print_wcwidth(0x24e3, "CIRCLED LATIN SMALL LETTER T");
  print_wcwidth(0x24e4, "CIRCLED LATIN SMALL LETTER U");
  print_wcwidth(0x24e5, "CIRCLED LATIN SMALL LETTER V");
  print_wcwidth(0x24e6, "CIRCLED LATIN SMALL LETTER W");
  print_wcwidth(0x24e7, "CIRCLED LATIN SMALL LETTER X");
  print_wcwidth(0x24e8, "CIRCLED LATIN SMALL LETTER Y");
  print_wcwidth(0x24e9, "CIRCLED LATIN SMALL LETTER Z");
  print_wcwidth(0x24eb, "NEGATIVE CIRCLED NUMBER ELEVEN");
  print_wcwidth(0x24ec, "NEGATIVE CIRCLED NUMBER TWELVE");
  print_wcwidth(0x24ed, "NEGATIVE CIRCLED NUMBER THIRTEEN");
  print_wcwidth(0x24ee, "NEGATIVE CIRCLED NUMBER FOURTEEN");
  print_wcwidth(0x24ef, "NEGATIVE CIRCLED NUMBER FIFTEEN");
  print_wcwidth(0x24f0, "NEGATIVE CIRCLED NUMBER SIXTEEN");
  print_wcwidth(0x24f1, "NEGATIVE CIRCLED NUMBER SEVENTEEN");
  print_wcwidth(0x24f2, "NEGATIVE CIRCLED NUMBER EIGHTEEN");
  print_wcwidth(0x24f3, "NEGATIVE CIRCLED NUMBER NINETEEN");
  print_wcwidth(0x24f4, "NEGATIVE CIRCLED NUMBER TWENTY");
  print_wcwidth(0x24f5, "DOUBLE CIRCLED DIGIT ONE");
  print_wcwidth(0x24f6, "DOUBLE CIRCLED DIGIT TWO");
  print_wcwidth(0x24f7, "DOUBLE CIRCLED DIGIT THREE");
  print_wcwidth(0x24f8, "DOUBLE CIRCLED DIGIT FOUR");
  print_wcwidth(0x24f9, "DOUBLE CIRCLED DIGIT FIVE");
  print_wcwidth(0x24fa, "DOUBLE CIRCLED DIGIT SIX");
  print_wcwidth(0x24fb, "DOUBLE CIRCLED DIGIT SEVEN");
  print_wcwidth(0x24fc, "DOUBLE CIRCLED DIGIT EIGHT");
  print_wcwidth(0x24fd, "DOUBLE CIRCLED DIGIT NINE");
  print_wcwidth(0x24fe, "DOUBLE CIRCLED NUMBER TEN");
  print_wcwidth(0x24ff, "NEGATIVE CIRCLED DIGIT ZERO");
  print_wcwidth(0x2500, "BOX DRAWINGS LIGHT HORIZONTAL");
  print_wcwidth(0x2501, "BOX DRAWINGS HEAVY HORIZONTAL");
  print_wcwidth(0x2502, "BOX DRAWINGS LIGHT VERTICAL");
  print_wcwidth(0x2503, "BOX DRAWINGS HEAVY VERTICAL");
  print_wcwidth(0x2504, "BOX DRAWINGS LIGHT TRIPLE DASH HORIZONTAL");
  print_wcwidth(0x2505, "BOX DRAWINGS HEAVY TRIPLE DASH HORIZONTAL");
  print_wcwidth(0x2506, "BOX DRAWINGS LIGHT TRIPLE DASH VERTICAL");
  print_wcwidth(0x2507, "BOX DRAWINGS HEAVY TRIPLE DASH VERTICAL");
  print_wcwidth(0x2508, "BOX DRAWINGS LIGHT QUADRUPLE DASH HORIZONTAL");
  print_wcwidth(0x2509, "BOX DRAWINGS HEAVY QUADRUPLE DASH HORIZONTAL");
  print_wcwidth(0x250a, "BOX DRAWINGS LIGHT QUADRUPLE DASH VERTICAL");
  print_wcwidth(0x250b, "BOX DRAWINGS HEAVY QUADRUPLE DASH VERTICAL");
  print_wcwidth(0x250c, "BOX DRAWINGS LIGHT DOWN AND RIGHT");
  print_wcwidth(0x250d, "BOX DRAWINGS DOWN LIGHT AND RIGHT HEAVY");
  print_wcwidth(0x250e, "BOX DRAWINGS DOWN HEAVY AND RIGHT LIGHT");
  print_wcwidth(0x250f, "BOX DRAWINGS HEAVY DOWN AND RIGHT");
  print_wcwidth(0x2510, "BOX DRAWINGS LIGHT DOWN AND LEFT");
  print_wcwidth(0x2511, "BOX DRAWINGS DOWN LIGHT AND LEFT HEAVY");
  print_wcwidth(0x2512, "BOX DRAWINGS DOWN HEAVY AND LEFT LIGHT");
  print_wcwidth(0x2513, "BOX DRAWINGS HEAVY DOWN AND LEFT");
  print_wcwidth(0x2514, "BOX DRAWINGS LIGHT UP AND RIGHT");
  print_wcwidth(0x2515, "BOX DRAWINGS UP LIGHT AND RIGHT HEAVY");
  print_wcwidth(0x2516, "BOX DRAWINGS UP HEAVY AND RIGHT LIGHT");
  print_wcwidth(0x2517, "BOX DRAWINGS HEAVY UP AND RIGHT");
  print_wcwidth(0x2518, "BOX DRAWINGS LIGHT UP AND LEFT");
  print_wcwidth(0x2519, "BOX DRAWINGS UP LIGHT AND LEFT HEAVY");
  print_wcwidth(0x251a, "BOX DRAWINGS UP HEAVY AND LEFT LIGHT");
  print_wcwidth(0x251b, "BOX DRAWINGS HEAVY UP AND LEFT");
  print_wcwidth(0x251c, "BOX DRAWINGS LIGHT VERTICAL AND RIGHT");
  print_wcwidth(0x251d, "BOX DRAWINGS VERTICAL LIGHT AND RIGHT HEAVY");
  print_wcwidth(0x251e, "BOX DRAWINGS UP HEAVY AND RIGHT DOWN LIGHT");
  print_wcwidth(0x251f, "BOX DRAWINGS DOWN HEAVY AND RIGHT UP LIGHT");
  print_wcwidth(0x2520, "BOX DRAWINGS VERTICAL HEAVY AND RIGHT LIGHT");
  print_wcwidth(0x2521, "BOX DRAWINGS DOWN LIGHT AND RIGHT UP HEAVY");
  print_wcwidth(0x2522, "BOX DRAWINGS UP LIGHT AND RIGHT DOWN HEAVY");
  print_wcwidth(0x2523, "BOX DRAWINGS HEAVY VERTICAL AND RIGHT");
  print_wcwidth(0x2524, "BOX DRAWINGS LIGHT VERTICAL AND LEFT");
  print_wcwidth(0x2525, "BOX DRAWINGS VERTICAL LIGHT AND LEFT HEAVY");
  print_wcwidth(0x2526, "BOX DRAWINGS UP HEAVY AND LEFT DOWN LIGHT");
  print_wcwidth(0x2527, "BOX DRAWINGS DOWN HEAVY AND LEFT UP LIGHT");
  print_wcwidth(0x2528, "BOX DRAWINGS VERTICAL HEAVY AND LEFT LIGHT");
  print_wcwidth(0x2529, "BOX DRAWINGS DOWN LIGHT AND LEFT UP HEAVY");
  print_wcwidth(0x252a, "BOX DRAWINGS UP LIGHT AND LEFT DOWN HEAVY");
  print_wcwidth(0x252b, "BOX DRAWINGS HEAVY VERTICAL AND LEFT");
  print_wcwidth(0x252c, "BOX DRAWINGS LIGHT DOWN AND HORIZONTAL");
  print_wcwidth(0x252d, "BOX DRAWINGS LEFT HEAVY AND RIGHT DOWN LIGHT");
  print_wcwidth(0x252e, "BOX DRAWINGS RIGHT HEAVY AND LEFT DOWN LIGHT");
  print_wcwidth(0x252f, "BOX DRAWINGS DOWN LIGHT AND HORIZONTAL HEAVY");
  print_wcwidth(0x2530, "BOX DRAWINGS DOWN HEAVY AND HORIZONTAL LIGHT");
  print_wcwidth(0x2531, "BOX DRAWINGS RIGHT LIGHT AND LEFT DOWN HEAVY");
  print_wcwidth(0x2532, "BOX DRAWINGS LEFT LIGHT AND RIGHT DOWN HEAVY");
  print_wcwidth(0x2533, "BOX DRAWINGS HEAVY DOWN AND HORIZONTAL");
  print_wcwidth(0x2534, "BOX DRAWINGS LIGHT UP AND HORIZONTAL");
  print_wcwidth(0x2535, "BOX DRAWINGS LEFT HEAVY AND RIGHT UP LIGHT");
  print_wcwidth(0x2536, "BOX DRAWINGS RIGHT HEAVY AND LEFT UP LIGHT");
  print_wcwidth(0x2537, "BOX DRAWINGS UP LIGHT AND HORIZONTAL HEAVY");
  print_wcwidth(0x2538, "BOX DRAWINGS UP HEAVY AND HORIZONTAL LIGHT");
  print_wcwidth(0x2539, "BOX DRAWINGS RIGHT LIGHT AND LEFT UP HEAVY");
  print_wcwidth(0x253a, "BOX DRAWINGS LEFT LIGHT AND RIGHT UP HEAVY");
  print_wcwidth(0x253b, "BOX DRAWINGS HEAVY UP AND HORIZONTAL");
  print_wcwidth(0x253c, "BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL");
  print_wcwidth(0x253d, "BOX DRAWINGS LEFT HEAVY AND RIGHT VERTICAL LIGHT");
  print_wcwidth(0x253e, "BOX DRAWINGS RIGHT HEAVY AND LEFT VERTICAL LIGHT");
  print_wcwidth(0x253f, "BOX DRAWINGS VERTICAL LIGHT AND HORIZONTAL HEAVY");
  print_wcwidth(0x2540, "BOX DRAWINGS UP HEAVY AND DOWN HORIZONTAL LIGHT");
  print_wcwidth(0x2541, "BOX DRAWINGS DOWN HEAVY AND UP HORIZONTAL LIGHT");
  print_wcwidth(0x2542, "BOX DRAWINGS VERTICAL HEAVY AND HORIZONTAL LIGHT");
  print_wcwidth(0x2543, "BOX DRAWINGS LEFT UP HEAVY AND RIGHT DOWN LIGHT");
  print_wcwidth(0x2544, "BOX DRAWINGS RIGHT UP HEAVY AND LEFT DOWN LIGHT");
  print_wcwidth(0x2545, "BOX DRAWINGS LEFT DOWN HEAVY AND RIGHT UP LIGHT");
  print_wcwidth(0x2546, "BOX DRAWINGS RIGHT DOWN HEAVY AND LEFT UP LIGHT");
  print_wcwidth(0x2547, "BOX DRAWINGS DOWN LIGHT AND UP HORIZONTAL HEAVY");
  print_wcwidth(0x2548, "BOX DRAWINGS UP LIGHT AND DOWN HORIZONTAL HEAVY");
  print_wcwidth(0x2549, "BOX DRAWINGS RIGHT LIGHT AND LEFT VERTICAL HEAVY");
  print_wcwidth(0x254a, "BOX DRAWINGS LEFT LIGHT AND RIGHT VERTICAL HEAVY");
  print_wcwidth(0x254b, "BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL");
  print_wcwidth(0x2550, "BOX DRAWINGS DOUBLE HORIZONTAL");
  print_wcwidth(0x2551, "BOX DRAWINGS DOUBLE VERTICAL");
  print_wcwidth(0x2552, "BOX DRAWINGS DOWN SINGLE AND RIGHT DOUBLE");
  print_wcwidth(0x2553, "BOX DRAWINGS DOWN DOUBLE AND RIGHT SINGLE");
  print_wcwidth(0x2554, "BOX DRAWINGS DOUBLE DOWN AND RIGHT");
  print_wcwidth(0x2555, "BOX DRAWINGS DOWN SINGLE AND LEFT DOUBLE");
  print_wcwidth(0x2556, "BOX DRAWINGS DOWN DOUBLE AND LEFT SINGLE");
  print_wcwidth(0x2557, "BOX DRAWINGS DOUBLE DOWN AND LEFT");
  print_wcwidth(0x2558, "BOX DRAWINGS UP SINGLE AND RIGHT DOUBLE");
  print_wcwidth(0x2559, "BOX DRAWINGS UP DOUBLE AND RIGHT SINGLE");
  print_wcwidth(0x255a, "BOX DRAWINGS DOUBLE UP AND RIGHT");
  print_wcwidth(0x255b, "BOX DRAWINGS UP SINGLE AND LEFT DOUBLE");
  print_wcwidth(0x255c, "BOX DRAWINGS UP DOUBLE AND LEFT SINGLE");
  print_wcwidth(0x255d, "BOX DRAWINGS DOUBLE UP AND LEFT");
  print_wcwidth(0x255e, "BOX DRAWINGS VERTICAL SINGLE AND RIGHT DOUBLE");
  print_wcwidth(0x255f, "BOX DRAWINGS VERTICAL DOUBLE AND RIGHT SINGLE");
  print_wcwidth(0x2560, "BOX DRAWINGS DOUBLE VERTICAL AND RIGHT");
  print_wcwidth(0x2561, "BOX DRAWINGS VERTICAL SINGLE AND LEFT DOUBLE");
  print_wcwidth(0x2562, "BOX DRAWINGS VERTICAL DOUBLE AND LEFT SINGLE");
  print_wcwidth(0x2563, "BOX DRAWINGS DOUBLE VERTICAL AND LEFT");
  print_wcwidth(0x2564, "BOX DRAWINGS DOWN SINGLE AND HORIZONTAL DOUBLE");
  print_wcwidth(0x2565, "BOX DRAWINGS DOWN DOUBLE AND HORIZONTAL SINGLE");
  print_wcwidth(0x2566, "BOX DRAWINGS DOUBLE DOWN AND HORIZONTAL");
  print_wcwidth(0x2567, "BOX DRAWINGS UP SINGLE AND HORIZONTAL DOUBLE");
  print_wcwidth(0x2568, "BOX DRAWINGS UP DOUBLE AND HORIZONTAL SINGLE");
  print_wcwidth(0x2569, "BOX DRAWINGS DOUBLE UP AND HORIZONTAL");
  print_wcwidth(0x256a, "BOX DRAWINGS VERTICAL SINGLE AND HORIZONTAL DOUBLE");
  print_wcwidth(0x256b, "BOX DRAWINGS VERTICAL DOUBLE AND HORIZONTAL SINGLE");
  print_wcwidth(0x256c, "BOX DRAWINGS DOUBLE VERTICAL AND HORIZONTAL");
  print_wcwidth(0x256d, "BOX DRAWINGS LIGHT ARC DOWN AND RIGHT");
  print_wcwidth(0x256e, "BOX DRAWINGS LIGHT ARC DOWN AND LEFT");
  print_wcwidth(0x256f, "BOX DRAWINGS LIGHT ARC UP AND LEFT");
  print_wcwidth(0x2570, "BOX DRAWINGS LIGHT ARC UP AND RIGHT");
  print_wcwidth(0x2571, "BOX DRAWINGS LIGHT DIAGONAL UPPER RIGHT TO LOWER LEFT");
  print_wcwidth(0x2572, "BOX DRAWINGS LIGHT DIAGONAL UPPER LEFT TO LOWER RIGHT");
  print_wcwidth(0x2573, "BOX DRAWINGS LIGHT DIAGONAL CROSS");
  print_wcwidth(0x2580, "UPPER HALF BLOCK");
  print_wcwidth(0x2581, "LOWER ONE EIGHTH BLOCK");
  print_wcwidth(0x2582, "LOWER ONE QUARTER BLOCK");
  print_wcwidth(0x2583, "LOWER THREE EIGHTHS BLOCK");
  print_wcwidth(0x2584, "LOWER HALF BLOCK");
  print_wcwidth(0x2585, "LOWER FIVE EIGHTHS BLOCK");
  print_wcwidth(0x2586, "LOWER THREE QUARTERS BLOCK");
  print_wcwidth(0x2587, "LOWER SEVEN EIGHTHS BLOCK");
  print_wcwidth(0x2588, "FULL BLOCK");
  print_wcwidth(0x2589, "LEFT SEVEN EIGHTHS BLOCK");
  print_wcwidth(0x258a, "LEFT THREE QUARTERS BLOCK");
  print_wcwidth(0x258b, "LEFT FIVE EIGHTHS BLOCK");
  print_wcwidth(0x258c, "LEFT HALF BLOCK");
  print_wcwidth(0x258d, "LEFT THREE EIGHTHS BLOCK");
  print_wcwidth(0x258e, "LEFT ONE QUARTER BLOCK");
  print_wcwidth(0x258f, "LEFT ONE EIGHTH BLOCK");
  print_wcwidth(0x2592, "MEDIUM SHADE");
  print_wcwidth(0x2593, "DARK SHADE");
  print_wcwidth(0x2594, "UPPER ONE EIGHTH BLOCK");
  print_wcwidth(0x2595, "RIGHT ONE EIGHTH BLOCK");
  print_wcwidth(0x25a0, "BLACK SQUARE");
  print_wcwidth(0x25a1, "WHITE SQUARE");
  print_wcwidth(0x25a3, "WHITE SQUARE CONTAINING BLACK SMALL SQUARE");
  print_wcwidth(0x25a4, "SQUARE WITH HORIZONTAL FILL");
  print_wcwidth(0x25a5, "SQUARE WITH VERTICAL FILL");
  print_wcwidth(0x25a6, "SQUARE WITH ORTHOGONAL CROSSHATCH FILL");
  print_wcwidth(0x25a7, "SQUARE WITH UPPER LEFT TO LOWER RIGHT FILL");
  print_wcwidth(0x25a8, "SQUARE WITH UPPER RIGHT TO LOWER LEFT FILL");
  print_wcwidth(0x25a9, "SQUARE WITH DIAGONAL CROSSHATCH FILL");
  print_wcwidth(0x25aa, "BLACK SMALL SQUARE");
  print_wcwidth(0x25ab, "WHITE SMALL SQUARE");
  print_wcwidth(0x25b2, "BLACK UP-POINTING TRIANGLE");
  print_wcwidth(0x25b3, "WHITE UP-POINTING TRIANGLE");
  print_wcwidth(0x25b6, "BLACK RIGHT-POINTING TRIANGLE");
  print_wcwidth(0x25b7, "WHITE RIGHT-POINTING TRIANGLE");
  print_wcwidth(0x25bc, "BLACK DOWN-POINTING TRIANGLE");
  print_wcwidth(0x25bd, "WHITE DOWN-POINTING TRIANGLE");
  print_wcwidth(0x25c0, "BLACK LEFT-POINTING TRIANGLE");
  print_wcwidth(0x25c1, "WHITE LEFT-POINTING TRIANGLE");
  print_wcwidth(0x25c6, "BLACK DIAMOND");
  print_wcwidth(0x25c7, "WHITE DIAMOND");
  print_wcwidth(0x25c8, "WHITE DIAMOND CONTAINING BLACK SMALL DIAMOND");
  print_wcwidth(0x25cb, "WHITE CIRCLE");
  print_wcwidth(0x25ce, "BULLSEYE");
  print_wcwidth(0x25cf, "BLACK CIRCLE");
  print_wcwidth(0x25d0, "CIRCLE WITH LEFT HALF BLACK");
  print_wcwidth(0x25d1, "CIRCLE WITH RIGHT HALF BLACK");
  print_wcwidth(0x25e2, "BLACK LOWER RIGHT TRIANGLE");
  print_wcwidth(0x25e3, "BLACK LOWER LEFT TRIANGLE");
  print_wcwidth(0x25e4, "BLACK UPPER LEFT TRIANGLE");
  print_wcwidth(0x25e5, "BLACK UPPER RIGHT TRIANGLE");
  print_wcwidth(0x25ef, "LARGE CIRCLE");
  print_wcwidth(0x25fb, "WHITE MEDIUM SQUARE");
  print_wcwidth(0x25fc, "BLACK MEDIUM SQUARE");
  print_wcwidth(0x25fd, "WHITE MEDIUM SMALL SQUARE");
  print_wcwidth(0x25fe, "BLACK MEDIUM SMALL SQUARE");
  print_wcwidth(0x2600, "BLACK SUN WITH RAYS");
  print_wcwidth(0x2601, "CLOUD");
  print_wcwidth(0x2602, "UMBRELLA");
  print_wcwidth(0x2603, "SNOWMAN");
  print_wcwidth(0x2604, "COMET");
  print_wcwidth(0x2605, "BLACK STAR");
  print_wcwidth(0x2606, "WHITE STAR");
  print_wcwidth(0x2609, "SUN");
  print_wcwidth(0x260e, "BLACK TELEPHONE");
  print_wcwidth(0x260f, "WHITE TELEPHONE");
  print_wcwidth(0x2611, "BALLOT BOX WITH CHECK");
  print_wcwidth(0x2614, "UMBRELLA WITH RAIN DROPS");
  print_wcwidth(0x2615, "HOT BEVERAGE");
  print_wcwidth(0x2618, "SHAMROCK");
  print_wcwidth(0x261c, "WHITE LEFT POINTING INDEX");
  print_wcwidth(0x261d, "WHITE UP POINTING INDEX");
  print_wcwidth(0x261e, "WHITE RIGHT POINTING INDEX");
  print_wcwidth(0x2620, "SKULL AND CROSSBONES");
  print_wcwidth(0x2622, "RADIOACTIVE SIGN");
  print_wcwidth(0x2623, "BIOHAZARD SIGN");
  print_wcwidth(0x2626, "ORTHODOX CROSS");
  print_wcwidth(0x262a, "STAR AND CRESCENT");
  print_wcwidth(0x262e, "PEACE SYMBOL");
  print_wcwidth(0x262f, "YIN YANG");
  print_wcwidth(0x2638, "WHEEL OF DHARMA");
  print_wcwidth(0x2639, "WHITE FROWNING FACE");
  print_wcwidth(0x263a, "WHITE SMILING FACE");
  print_wcwidth(0x2640, "FEMALE SIGN");
  print_wcwidth(0x2642, "MALE SIGN");
  print_wcwidth(0x2648, "ARIES");
  print_wcwidth(0x2649, "TAURUS");
  print_wcwidth(0x264a, "GEMINI");
  print_wcwidth(0x264b, "CANCER");
  print_wcwidth(0x264c, "LEO");
  print_wcwidth(0x264d, "VIRGO");
  print_wcwidth(0x264e, "LIBRA");
  print_wcwidth(0x264f, "SCORPIUS");
  print_wcwidth(0x2650, "SAGITTARIUS");
  print_wcwidth(0x2651, "CAPRICORN");
  print_wcwidth(0x2652, "AQUARIUS");
  print_wcwidth(0x2653, "PISCES");
  print_wcwidth(0x2660, "BLACK SPADE SUIT");
  print_wcwidth(0x2661, "WHITE HEART SUIT");
  print_wcwidth(0x2663, "BLACK CLUB SUIT");
  print_wcwidth(0x2664, "WHITE SPADE SUIT");
  print_wcwidth(0x2665, "BLACK HEART SUIT");
  print_wcwidth(0x2666, "BLACK DIAMOND SUIT");
  print_wcwidth(0x2667, "WHITE CLUB SUIT");
  print_wcwidth(0x2668, "HOT SPRINGS");
  print_wcwidth(0x2669, "QUARTER NOTE");
  print_wcwidth(0x266a, "EIGHTH NOTE");
  print_wcwidth(0x266c, "BEAMED SIXTEENTH NOTES");
  print_wcwidth(0x266d, "MUSIC FLAT SIGN");
  print_wcwidth(0x266f, "MUSIC SHARP SIGN");
  print_wcwidth(0x267b, "BLACK UNIVERSAL RECYCLING SYMBOL");
  print_wcwidth(0x267f, "WHEELCHAIR SYMBOL");
  print_wcwidth(0x2692, "HAMMER AND PICK");
  print_wcwidth(0x2693, "ANCHOR");
  print_wcwidth(0x2694, "CROSSED SWORDS");
  print_wcwidth(0x2696, "SCALES");
  print_wcwidth(0x2697, "ALEMBIC");
  print_wcwidth(0x2699, "GEAR");
  print_wcwidth(0x269b, "ATOM SYMBOL");
  print_wcwidth(0x269c, "FLEUR-DE-LIS");
  print_wcwidth(0x269e, "THREE LINES CONVERGING RIGHT");
  print_wcwidth(0x269f, "THREE LINES CONVERGING LEFT");
  print_wcwidth(0x26a0, "WARNING SIGN");
  print_wcwidth(0x26a1, "HIGH VOLTAGE SIGN");
  print_wcwidth(0x26aa, "MEDIUM WHITE CIRCLE");
  print_wcwidth(0x26ab, "MEDIUM BLACK CIRCLE");
  print_wcwidth(0x26b0, "COFFIN");
  print_wcwidth(0x26b1, "FUNERAL URN");
  print_wcwidth(0x26bd, "SOCCER BALL");
  print_wcwidth(0x26be, "BASEBALL");
  print_wcwidth(0x26bf, "SQUARED KEY");
  print_wcwidth(0x26c4, "SNOWMAN WITHOUT SNOW");
  print_wcwidth(0x26c5, "SUN BEHIND CLOUD");
  print_wcwidth(0x26c6, "RAIN");
  print_wcwidth(0x26c7, "BLACK SNOWMAN");
  print_wcwidth(0x26c8, "THUNDER CLOUD AND RAIN");
  print_wcwidth(0x26c9, "TURNED WHITE SHOGI PIECE");
  print_wcwidth(0x26ca, "TURNED BLACK SHOGI PIECE");
  print_wcwidth(0x26cb, "WHITE DIAMOND IN SQUARE");
  print_wcwidth(0x26cc, "CROSSING LANES");
  print_wcwidth(0x26cd, "DISABLED CAR");
  print_wcwidth(0x26ce, "OPHIUCHUS");
  print_wcwidth(0x26cf, "PICK");
  print_wcwidth(0x26d0, "CAR SLIDING");
  print_wcwidth(0x26d1, "HELMET WITH WHITE CROSS");
  print_wcwidth(0x26d2, "CIRCLED CROSSING LANES");
  print_wcwidth(0x26d3, "CHAINS");
  print_wcwidth(0x26d4, "NO ENTRY");
  print_wcwidth(0x26d5, "ALTERNATE ONE-WAY LEFT WAY TRAFFIC");
  print_wcwidth(0x26d6, "BLACK TWO-WAY LEFT WAY TRAFFIC");
  print_wcwidth(0x26d7, "WHITE TWO-WAY LEFT WAY TRAFFIC");
  print_wcwidth(0x26d8, "BLACK LEFT LANE MERGE");
  print_wcwidth(0x26d9, "WHITE LEFT LANE MERGE");
  print_wcwidth(0x26da, "DRIVE SLOW SIGN");
  print_wcwidth(0x26db, "HEAVY WHITE DOWN-POINTING TRIANGLE");
  print_wcwidth(0x26dc, "LEFT CLOSED ENTRY");
  print_wcwidth(0x26dd, "SQUARED SALTIRE");
  print_wcwidth(0x26de, "FALLING DIAGONAL IN WHITE CIRCLE IN BLACK SQUARE");
  print_wcwidth(0x26df, "BLACK TRUCK");
  print_wcwidth(0x26e0, "RESTRICTED LEFT ENTRY-1");
  print_wcwidth(0x26e1, "RESTRICTED LEFT ENTRY-2");
  print_wcwidth(0x26e3, "HEAVY CIRCLE WITH STROKE AND TWO DOTS ABOVE");
  print_wcwidth(0x26e8, "BLACK CROSS ON SHIELD");
  print_wcwidth(0x26e9, "SHINTO SHRINE");
  print_wcwidth(0x26ea, "CHURCH");
  print_wcwidth(0x26eb, "CASTLE");
  print_wcwidth(0x26ec, "HISTORIC SITE");
  print_wcwidth(0x26ed, "GEAR WITHOUT HUB");
  print_wcwidth(0x26ee, "GEAR WITH HANDLES");
  print_wcwidth(0x26ef, "MAP SYMBOL FOR LIGHTHOUSE");
  print_wcwidth(0x26f0, "MOUNTAIN");
  print_wcwidth(0x26f1, "UMBRELLA ON GROUND");
  print_wcwidth(0x26f2, "FOUNTAIN");
  print_wcwidth(0x26f3, "FLAG IN HOLE");
  print_wcwidth(0x26f4, "FERRY");
  print_wcwidth(0x26f5, "SAILBOAT");
  print_wcwidth(0x26f6, "SQUARE FOUR CORNERS");
  print_wcwidth(0x26f7, "SKIER");
  print_wcwidth(0x26f8, "ICE SKATE");
  print_wcwidth(0x26f9, "PERSON WITH BALL");
  print_wcwidth(0x26fa, "TENT");
  print_wcwidth(0x26fb, "JAPANESE BANK SYMBOL");
  print_wcwidth(0x26fc, "HEADSTONE GRAVEYARD SYMBOL");
  print_wcwidth(0x26fd, "FUEL PUMP");
  print_wcwidth(0x26fe, "CUP ON BLACK SQUARE");
  print_wcwidth(0x26ff, "WHITE FLAG WITH HORIZONTAL MIDDLE BLACK STRIPE");
  print_wcwidth(0x2702, "BLACK SCISSORS");
  print_wcwidth(0x2705, "WHITE HEAVY CHECK MARK");
  print_wcwidth(0x2708, "AIRPLANE");
  print_wcwidth(0x2709, "ENVELOPE");
  print_wcwidth(0x270a, "RAISED FIST");
  print_wcwidth(0x270b, "RAISED HAND");
  print_wcwidth(0x270c, "VICTORY HAND");
  print_wcwidth(0x270d, "WRITING HAND");
  print_wcwidth(0x270f, "PENCIL");
  print_wcwidth(0x2712, "BLACK NIB");
  print_wcwidth(0x2714, "HEAVY CHECK MARK");
  print_wcwidth(0x2716, "HEAVY MULTIPLICATION X");
  print_wcwidth(0x271d, "LATIN CROSS");
  print_wcwidth(0x2721, "STAR OF DAVID");
  print_wcwidth(0x2728, "SPARKLES");
  print_wcwidth(0x2733, "EIGHT SPOKED ASTERISK");
  print_wcwidth(0x2734, "EIGHT POINTED BLACK STAR");
  print_wcwidth(0x273d, "HEAVY TEARDROP-SPOKED ASTERISK");
  print_wcwidth(0x2744, "SNOWFLAKE");
  print_wcwidth(0x2747, "SPARKLE");
  print_wcwidth(0x274c, "CROSS MARK");
  print_wcwidth(0x274e, "NEGATIVE SQUARED CROSS MARK");
  print_wcwidth(0x2753, "BLACK QUESTION MARK ORNAMENT");
  print_wcwidth(0x2754, "WHITE QUESTION MARK ORNAMENT");
  print_wcwidth(0x2755, "WHITE EXCLAMATION MARK ORNAMENT");
  print_wcwidth(0x2757, "HEAVY EXCLAMATION MARK SYMBOL");
  print_wcwidth(0x2763, "HEAVY HEART EXCLAMATION MARK ORNAMENT");
  print_wcwidth(0x2764, "HEAVY BLACK HEART");
  print_wcwidth(0x2776, "DINGBAT NEGATIVE CIRCLED DIGIT ONE");
  print_wcwidth(0x2777, "DINGBAT NEGATIVE CIRCLED DIGIT TWO");
  print_wcwidth(0x2778, "DINGBAT NEGATIVE CIRCLED DIGIT THREE");
  print_wcwidth(0x2779, "DINGBAT NEGATIVE CIRCLED DIGIT FOUR");
  print_wcwidth(0x277a, "DINGBAT NEGATIVE CIRCLED DIGIT FIVE");
  print_wcwidth(0x277b, "DINGBAT NEGATIVE CIRCLED DIGIT SIX");
  print_wcwidth(0x277c, "DINGBAT NEGATIVE CIRCLED DIGIT SEVEN");
  print_wcwidth(0x277d, "DINGBAT NEGATIVE CIRCLED DIGIT EIGHT");
  print_wcwidth(0x277e, "DINGBAT NEGATIVE CIRCLED DIGIT NINE");
  print_wcwidth(0x277f, "DINGBAT NEGATIVE CIRCLED NUMBER TEN");
  print_wcwidth(0x2795, "HEAVY PLUS SIGN");
  print_wcwidth(0x2796, "HEAVY MINUS SIGN");
  print_wcwidth(0x2797, "HEAVY DIVISION SIGN");
  print_wcwidth(0x27a1, "BLACK RIGHTWARDS ARROW");
  print_wcwidth(0x27b0, "CURLY LOOP");
  print_wcwidth(0x27bf, "DOUBLE CURLY LOOP");
  print_wcwidth(0x2934, "ARROW POINTING RIGHTWARDS THEN CURVING UPWARDS");
  print_wcwidth(0x2935, "ARROW POINTING RIGHTWARDS THEN CURVING DOWNWARDS");
  print_wcwidth(0x2b05, "LEFTWARDS BLACK ARROW");
  print_wcwidth(0x2b06, "UPWARDS BLACK ARROW");
  print_wcwidth(0x2b07, "DOWNWARDS BLACK ARROW");
  print_wcwidth(0x2b1b, "BLACK LARGE SQUARE");
  print_wcwidth(0x2b1c, "WHITE LARGE SQUARE");
  print_wcwidth(0x2b50, "WHITE MEDIUM STAR");
  print_wcwidth(0x2b55, "HEAVY LARGE CIRCLE");
  print_wcwidth(0x2b56, "HEAVY OVAL WITH OVAL INSIDE");
  print_wcwidth(0x2b57, "HEAVY CIRCLE WITH CIRCLE INSIDE");
  print_wcwidth(0x2b58, "HEAVY CIRCLE");
  print_wcwidth(0x2b59, "HEAVY CIRCLED SALTIRE");
  print_wcwidth(0x3030, "WAVY DASH");
  print_wcwidth(0x303d, "PART ALTERNATION MARK");
  print_wcwidth(0x3248, "CIRCLED NUMBER TEN ON BLACK SQUARE");
  print_wcwidth(0x3249, "CIRCLED NUMBER TWENTY ON BLACK SQUARE");
  print_wcwidth(0x324a, "CIRCLED NUMBER THIRTY ON BLACK SQUARE");
  print_wcwidth(0x324b, "CIRCLED NUMBER FORTY ON BLACK SQUARE");
  print_wcwidth(0x324c, "CIRCLED NUMBER FIFTY ON BLACK SQUARE");
  print_wcwidth(0x324d, "CIRCLED NUMBER SIXTY ON BLACK SQUARE");
  print_wcwidth(0x324e, "CIRCLED NUMBER SEVENTY ON BLACK SQUARE");
  print_wcwidth(0x324f, "CIRCLED NUMBER EIGHTY ON BLACK SQUARE");
  print_wcwidth(0x3297, "CIRCLED IDEOGRAPH CONGRATULATION");
  print_wcwidth(0x3299, "CIRCLED IDEOGRAPH SECRET");
  print_wcwidth(0xfffd, "REPLACEMENT CHARACTER");
  print_wcwidth(0x1f004, "MAHJONG TILE RED DRAGON");
  print_wcwidth(0x1f0cf, "PLAYING CARD BLACK JOKER");
  print_wcwidth(0x1f100, "DIGIT ZERO FULL STOP");
  print_wcwidth(0x1f101, "DIGIT ZERO COMMA");
  print_wcwidth(0x1f102, "DIGIT ONE COMMA");
  print_wcwidth(0x1f103, "DIGIT TWO COMMA");
  print_wcwidth(0x1f104, "DIGIT THREE COMMA");
  print_wcwidth(0x1f105, "DIGIT FOUR COMMA");
  print_wcwidth(0x1f106, "DIGIT FIVE COMMA");
  print_wcwidth(0x1f107, "DIGIT SIX COMMA");
  print_wcwidth(0x1f108, "DIGIT SEVEN COMMA");
  print_wcwidth(0x1f109, "DIGIT EIGHT COMMA");
  print_wcwidth(0x1f10a, "DIGIT NINE COMMA");
  print_wcwidth(0x1f110, "PARENTHESIZED LATIN CAPITAL LETTER A");
  print_wcwidth(0x1f111, "PARENTHESIZED LATIN CAPITAL LETTER B");
  print_wcwidth(0x1f112, "PARENTHESIZED LATIN CAPITAL LETTER C");
  print_wcwidth(0x1f113, "PARENTHESIZED LATIN CAPITAL LETTER D");
  print_wcwidth(0x1f114, "PARENTHESIZED LATIN CAPITAL LETTER E");
  print_wcwidth(0x1f115, "PARENTHESIZED LATIN CAPITAL LETTER F");
  print_wcwidth(0x1f116, "PARENTHESIZED LATIN CAPITAL LETTER G");
  print_wcwidth(0x1f117, "PARENTHESIZED LATIN CAPITAL LETTER H");
  print_wcwidth(0x1f118, "PARENTHESIZED LATIN CAPITAL LETTER I");
  print_wcwidth(0x1f119, "PARENTHESIZED LATIN CAPITAL LETTER J");
  print_wcwidth(0x1f11a, "PARENTHESIZED LATIN CAPITAL LETTER K");
  print_wcwidth(0x1f11b, "PARENTHESIZED LATIN CAPITAL LETTER L");
  print_wcwidth(0x1f11c, "PARENTHESIZED LATIN CAPITAL LETTER M");
  print_wcwidth(0x1f11d, "PARENTHESIZED LATIN CAPITAL LETTER N");
  print_wcwidth(0x1f11e, "PARENTHESIZED LATIN CAPITAL LETTER O");
  print_wcwidth(0x1f11f, "PARENTHESIZED LATIN CAPITAL LETTER P");
  print_wcwidth(0x1f120, "PARENTHESIZED LATIN CAPITAL LETTER Q");
  print_wcwidth(0x1f121, "PARENTHESIZED LATIN CAPITAL LETTER R");
  print_wcwidth(0x1f122, "PARENTHESIZED LATIN CAPITAL LETTER S");
  print_wcwidth(0x1f123, "PARENTHESIZED LATIN CAPITAL LETTER T");
  print_wcwidth(0x1f124, "PARENTHESIZED LATIN CAPITAL LETTER U");
  print_wcwidth(0x1f125, "PARENTHESIZED LATIN CAPITAL LETTER V");
  print_wcwidth(0x1f126, "PARENTHESIZED LATIN CAPITAL LETTER W");
  print_wcwidth(0x1f127, "PARENTHESIZED LATIN CAPITAL LETTER X");
  print_wcwidth(0x1f128, "PARENTHESIZED LATIN CAPITAL LETTER Y");
  print_wcwidth(0x1f129, "PARENTHESIZED LATIN CAPITAL LETTER Z");
  print_wcwidth(0x1f12a, "TORTOISE SHELL BRACKETED LATIN CAPITAL LETTER S");
  print_wcwidth(0x1f12b, "CIRCLED ITALIC LATIN CAPITAL LETTER C");
  print_wcwidth(0x1f12c, "CIRCLED ITALIC LATIN CAPITAL LETTER R");
  print_wcwidth(0x1f12d, "CIRCLED CD");
  print_wcwidth(0x1f130, "SQUARED LATIN CAPITAL LETTER A");
  print_wcwidth(0x1f131, "SQUARED LATIN CAPITAL LETTER B");
  print_wcwidth(0x1f132, "SQUARED LATIN CAPITAL LETTER C");
  print_wcwidth(0x1f133, "SQUARED LATIN CAPITAL LETTER D");
  print_wcwidth(0x1f134, "SQUARED LATIN CAPITAL LETTER E");
  print_wcwidth(0x1f135, "SQUARED LATIN CAPITAL LETTER F");
  print_wcwidth(0x1f136, "SQUARED LATIN CAPITAL LETTER G");
  print_wcwidth(0x1f137, "SQUARED LATIN CAPITAL LETTER H");
  print_wcwidth(0x1f138, "SQUARED LATIN CAPITAL LETTER I");
  print_wcwidth(0x1f139, "SQUARED LATIN CAPITAL LETTER J");
  print_wcwidth(0x1f13a, "SQUARED LATIN CAPITAL LETTER K");
  print_wcwidth(0x1f13b, "SQUARED LATIN CAPITAL LETTER L");
  print_wcwidth(0x1f13c, "SQUARED LATIN CAPITAL LETTER M");
  print_wcwidth(0x1f13d, "SQUARED LATIN CAPITAL LETTER N");
  print_wcwidth(0x1f13e, "SQUARED LATIN CAPITAL LETTER O");
  print_wcwidth(0x1f13f, "SQUARED LATIN CAPITAL LETTER P");
  print_wcwidth(0x1f140, "SQUARED LATIN CAPITAL LETTER Q");
  print_wcwidth(0x1f141, "SQUARED LATIN CAPITAL LETTER R");
  print_wcwidth(0x1f142, "SQUARED LATIN CAPITAL LETTER S");
  print_wcwidth(0x1f143, "SQUARED LATIN CAPITAL LETTER T");
  print_wcwidth(0x1f144, "SQUARED LATIN CAPITAL LETTER U");
  print_wcwidth(0x1f145, "SQUARED LATIN CAPITAL LETTER V");
  print_wcwidth(0x1f146, "SQUARED LATIN CAPITAL LETTER W");
  print_wcwidth(0x1f147, "SQUARED LATIN CAPITAL LETTER X");
  print_wcwidth(0x1f148, "SQUARED LATIN CAPITAL LETTER Y");
  print_wcwidth(0x1f149, "SQUARED LATIN CAPITAL LETTER Z");
  print_wcwidth(0x1f14a, "SQUARED HV");
  print_wcwidth(0x1f14b, "SQUARED MV");
  print_wcwidth(0x1f14c, "SQUARED SD");
  print_wcwidth(0x1f14d, "SQUARED SS");
  print_wcwidth(0x1f14e, "SQUARED PPV");
  print_wcwidth(0x1f14f, "SQUARED WC");
  print_wcwidth(0x1f150, "NEGATIVE CIRCLED LATIN CAPITAL LETTER A");
  print_wcwidth(0x1f151, "NEGATIVE CIRCLED LATIN CAPITAL LETTER B");
  print_wcwidth(0x1f152, "NEGATIVE CIRCLED LATIN CAPITAL LETTER C");
  print_wcwidth(0x1f153, "NEGATIVE CIRCLED LATIN CAPITAL LETTER D");
  print_wcwidth(0x1f154, "NEGATIVE CIRCLED LATIN CAPITAL LETTER E");
  print_wcwidth(0x1f155, "NEGATIVE CIRCLED LATIN CAPITAL LETTER F");
  print_wcwidth(0x1f156, "NEGATIVE CIRCLED LATIN CAPITAL LETTER G");
  print_wcwidth(0x1f157, "NEGATIVE CIRCLED LATIN CAPITAL LETTER H");
  print_wcwidth(0x1f158, "NEGATIVE CIRCLED LATIN CAPITAL LETTER I");
  print_wcwidth(0x1f159, "NEGATIVE CIRCLED LATIN CAPITAL LETTER J");
  print_wcwidth(0x1f15a, "NEGATIVE CIRCLED LATIN CAPITAL LETTER K");
  print_wcwidth(0x1f15b, "NEGATIVE CIRCLED LATIN CAPITAL LETTER L");
  print_wcwidth(0x1f15c, "NEGATIVE CIRCLED LATIN CAPITAL LETTER M");
  print_wcwidth(0x1f15d, "NEGATIVE CIRCLED LATIN CAPITAL LETTER N");
  print_wcwidth(0x1f15e, "NEGATIVE CIRCLED LATIN CAPITAL LETTER O");
  print_wcwidth(0x1f15f, "NEGATIVE CIRCLED LATIN CAPITAL LETTER P");
  print_wcwidth(0x1f160, "NEGATIVE CIRCLED LATIN CAPITAL LETTER Q");
  print_wcwidth(0x1f161, "NEGATIVE CIRCLED LATIN CAPITAL LETTER R");
  print_wcwidth(0x1f162, "NEGATIVE CIRCLED LATIN CAPITAL LETTER S");
  print_wcwidth(0x1f163, "NEGATIVE CIRCLED LATIN CAPITAL LETTER T");
  print_wcwidth(0x1f164, "NEGATIVE CIRCLED LATIN CAPITAL LETTER U");
  print_wcwidth(0x1f165, "NEGATIVE CIRCLED LATIN CAPITAL LETTER V");
  print_wcwidth(0x1f166, "NEGATIVE CIRCLED LATIN CAPITAL LETTER W");
  print_wcwidth(0x1f167, "NEGATIVE CIRCLED LATIN CAPITAL LETTER X");
  print_wcwidth(0x1f168, "NEGATIVE CIRCLED LATIN CAPITAL LETTER Y");
  print_wcwidth(0x1f169, "NEGATIVE CIRCLED LATIN CAPITAL LETTER Z");
  print_wcwidth(0x1f170, "NEGATIVE SQUARED LATIN CAPITAL LETTER A");
  print_wcwidth(0x1f171, "NEGATIVE SQUARED LATIN CAPITAL LETTER B");
  print_wcwidth(0x1f172, "NEGATIVE SQUARED LATIN CAPITAL LETTER C");
  print_wcwidth(0x1f173, "NEGATIVE SQUARED LATIN CAPITAL LETTER D");
  print_wcwidth(0x1f174, "NEGATIVE SQUARED LATIN CAPITAL LETTER E");
  print_wcwidth(0x1f175, "NEGATIVE SQUARED LATIN CAPITAL LETTER F");
  print_wcwidth(0x1f176, "NEGATIVE SQUARED LATIN CAPITAL LETTER G");
  print_wcwidth(0x1f177, "NEGATIVE SQUARED LATIN CAPITAL LETTER H");
  print_wcwidth(0x1f178, "NEGATIVE SQUARED LATIN CAPITAL LETTER I");
  print_wcwidth(0x1f179, "NEGATIVE SQUARED LATIN CAPITAL LETTER J");
  print_wcwidth(0x1f17a, "NEGATIVE SQUARED LATIN CAPITAL LETTER K");
  print_wcwidth(0x1f17b, "NEGATIVE SQUARED LATIN CAPITAL LETTER L");
  print_wcwidth(0x1f17c, "NEGATIVE SQUARED LATIN CAPITAL LETTER M");
  print_wcwidth(0x1f17d, "NEGATIVE SQUARED LATIN CAPITAL LETTER N");
  print_wcwidth(0x1f17e, "NEGATIVE SQUARED LATIN CAPITAL LETTER O");
  print_wcwidth(0x1f17f, "NEGATIVE SQUARED LATIN CAPITAL LETTER P");
  print_wcwidth(0x1f180, "NEGATIVE SQUARED LATIN CAPITAL LETTER Q");
  print_wcwidth(0x1f181, "NEGATIVE SQUARED LATIN CAPITAL LETTER R");
  print_wcwidth(0x1f182, "NEGATIVE SQUARED LATIN CAPITAL LETTER S");
  print_wcwidth(0x1f183, "NEGATIVE SQUARED LATIN CAPITAL LETTER T");
  print_wcwidth(0x1f184, "NEGATIVE SQUARED LATIN CAPITAL LETTER U");
  print_wcwidth(0x1f185, "NEGATIVE SQUARED LATIN CAPITAL LETTER V");
  print_wcwidth(0x1f186, "NEGATIVE SQUARED LATIN CAPITAL LETTER W");
  print_wcwidth(0x1f187, "NEGATIVE SQUARED LATIN CAPITAL LETTER X");
  print_wcwidth(0x1f188, "NEGATIVE SQUARED LATIN CAPITAL LETTER Y");
  print_wcwidth(0x1f189, "NEGATIVE SQUARED LATIN CAPITAL LETTER Z");
  print_wcwidth(0x1f18a, "CROSSED NEGATIVE SQUARED LATIN CAPITAL LETTER P");
  print_wcwidth(0x1f18b, "NEGATIVE SQUARED IC");
  print_wcwidth(0x1f18c, "NEGATIVE SQUARED PA");
  print_wcwidth(0x1f18d, "NEGATIVE SQUARED SA");
  print_wcwidth(0x1f18e, "NEGATIVE SQUARED AB");
  print_wcwidth(0x1f18f, "NEGATIVE SQUARED WC");
  print_wcwidth(0x1f190, "SQUARE DJ");
  print_wcwidth(0x1f191, "SQUARED CL");
  print_wcwidth(0x1f192, "SQUARED COOL");
  print_wcwidth(0x1f193, "SQUARED FREE");
  print_wcwidth(0x1f194, "SQUARED ID");
  print_wcwidth(0x1f195, "SQUARED NEW");
  print_wcwidth(0x1f196, "SQUARED NG");
  print_wcwidth(0x1f197, "SQUARED OK");
  print_wcwidth(0x1f198, "SQUARED SOS");
  print_wcwidth(0x1f199, "SQUARED UP WITH EXCLAMATION MARK");
  print_wcwidth(0x1f19a, "SQUARED VS");
  print_wcwidth(0x1f201, "SQUARED KATAKANA KOKO");
  print_wcwidth(0x1f202, "SQUARED KATAKANA SA");
  print_wcwidth(0x1f21a, "SQUARED CJK UNIFIED IDEOGRAPH-7121");
  print_wcwidth(0x1f22f, "SQUARED CJK UNIFIED IDEOGRAPH-6307");
  print_wcwidth(0x1f232, "SQUARED CJK UNIFIED IDEOGRAPH-7981");
  print_wcwidth(0x1f233, "SQUARED CJK UNIFIED IDEOGRAPH-7A7A");
  print_wcwidth(0x1f234, "SQUARED CJK UNIFIED IDEOGRAPH-5408");
  print_wcwidth(0x1f235, "SQUARED CJK UNIFIED IDEOGRAPH-6E80");
  print_wcwidth(0x1f236, "SQUARED CJK UNIFIED IDEOGRAPH-6709");
  print_wcwidth(0x1f237, "SQUARED CJK UNIFIED IDEOGRAPH-6708");
  print_wcwidth(0x1f238, "SQUARED CJK UNIFIED IDEOGRAPH-7533");
  print_wcwidth(0x1f239, "SQUARED CJK UNIFIED IDEOGRAPH-5272");
  print_wcwidth(0x1f23a, "SQUARED CJK UNIFIED IDEOGRAPH-55B6");
  print_wcwidth(0x1f250, "CIRCLED IDEOGRAPH ADVANTAGE");
  print_wcwidth(0x1f251, "CIRCLED IDEOGRAPH ACCEPT");
  print_wcwidth(0x1f300, "CYCLONE");
  print_wcwidth(0x1f301, "FOGGY");
  print_wcwidth(0x1f302, "CLOSED UMBRELLA");
  print_wcwidth(0x1f303, "NIGHT WITH STARS");
  print_wcwidth(0x1f304, "SUNRISE OVER MOUNTAINS");
  print_wcwidth(0x1f305, "SUNRISE");
  print_wcwidth(0x1f306, "CITYSCAPE AT DUSK");
  print_wcwidth(0x1f307, "SUNSET OVER BUILDINGS");
  print_wcwidth(0x1f308, "RAINBOW");
  print_wcwidth(0x1f309, "BRIDGE AT NIGHT");
  print_wcwidth(0x1f30a, "WATER WAVE");
  print_wcwidth(0x1f30b, "VOLCANO");
  print_wcwidth(0x1f30c, "MILKY WAY");
  print_wcwidth(0x1f30d, "EARTH GLOBE EUROPE-AFRICA");
  print_wcwidth(0x1f30e, "EARTH GLOBE AMERICAS");
  print_wcwidth(0x1f30f, "EARTH GLOBE ASIA-AUSTRALIA");
  print_wcwidth(0x1f310, "GLOBE WITH MERIDIANS");
  print_wcwidth(0x1f311, "NEW MOON SYMBOL");
  print_wcwidth(0x1f312, "WAXING CRESCENT MOON SYMBOL");
  print_wcwidth(0x1f313, "FIRST QUARTER MOON SYMBOL");
  print_wcwidth(0x1f314, "WAXING GIBBOUS MOON SYMBOL");
  print_wcwidth(0x1f315, "FULL MOON SYMBOL");
  print_wcwidth(0x1f316, "WANING GIBBOUS MOON SYMBOL");
  print_wcwidth(0x1f317, "LAST QUARTER MOON SYMBOL");
  print_wcwidth(0x1f318, "WANING CRESCENT MOON SYMBOL");
  print_wcwidth(0x1f319, "CRESCENT MOON");
  print_wcwidth(0x1f31a, "NEW MOON WITH FACE");
  print_wcwidth(0x1f31b, "FIRST QUARTER MOON WITH FACE");
  print_wcwidth(0x1f31c, "LAST QUARTER MOON WITH FACE");
  print_wcwidth(0x1f31d, "FULL MOON WITH FACE");
  print_wcwidth(0x1f31e, "SUN WITH FACE");
  print_wcwidth(0x1f31f, "GLOWING STAR");
  print_wcwidth(0x1f320, "SHOOTING STAR");
  print_wcwidth(0x1f321, "THERMOMETER");
  print_wcwidth(0x1f324, "WHITE SUN WITH SMALL CLOUD");
  print_wcwidth(0x1f325, "WHITE SUN BEHIND CLOUD");
  print_wcwidth(0x1f326, "WHITE SUN BEHIND CLOUD WITH RAIN");
  print_wcwidth(0x1f327, "CLOUD WITH RAIN");
  print_wcwidth(0x1f328, "CLOUD WITH SNOW");
  print_wcwidth(0x1f329, "CLOUD WITH LIGHTNING");
  print_wcwidth(0x1f32a, "CLOUD WITH TORNADO");
  print_wcwidth(0x1f32b, "FOG");
  print_wcwidth(0x1f32c, "WIND BLOWING FACE");
  print_wcwidth(0x1f330, "CHESTNUT");
  print_wcwidth(0x1f331, "SEEDLING");
  print_wcwidth(0x1f332, "EVERGREEN TREE");
  print_wcwidth(0x1f333, "DECIDUOUS TREE");
  print_wcwidth(0x1f334, "PALM TREE");
  print_wcwidth(0x1f335, "CACTUS");
  print_wcwidth(0x1f336, "HOT PEPPER");
  print_wcwidth(0x1f337, "TULIP");
  print_wcwidth(0x1f338, "CHERRY BLOSSOM");
  print_wcwidth(0x1f339, "ROSE");
  print_wcwidth(0x1f33a, "HIBISCUS");
  print_wcwidth(0x1f33b, "SUNFLOWER");
  print_wcwidth(0x1f33c, "BLOSSOM");
  print_wcwidth(0x1f33d, "EAR OF MAIZE");
  print_wcwidth(0x1f33e, "EAR OF RICE");
  print_wcwidth(0x1f33f, "HERB");
  print_wcwidth(0x1f340, "FOUR LEAF CLOVER");
  print_wcwidth(0x1f341, "MAPLE LEAF");
  print_wcwidth(0x1f342, "FALLEN LEAF");
  print_wcwidth(0x1f343, "LEAF FLUTTERING IN WIND");
  print_wcwidth(0x1f344, "MUSHROOM");
  print_wcwidth(0x1f345, "TOMATO");
  print_wcwidth(0x1f346, "AUBERGINE");
  print_wcwidth(0x1f347, "GRAPES");
  print_wcwidth(0x1f348, "MELON");
  print_wcwidth(0x1f349, "WATERMELON");
  print_wcwidth(0x1f34a, "TANGERINE");
  print_wcwidth(0x1f34b, "LEMON");
  print_wcwidth(0x1f34c, "BANANA");
  print_wcwidth(0x1f34d, "PINEAPPLE");
  print_wcwidth(0x1f34e, "RED APPLE");
  print_wcwidth(0x1f34f, "GREEN APPLE");
  print_wcwidth(0x1f350, "PEAR");
  print_wcwidth(0x1f351, "PEACH");
  print_wcwidth(0x1f352, "CHERRIES");
  print_wcwidth(0x1f353, "STRAWBERRY");
  print_wcwidth(0x1f354, "HAMBURGER");
  print_wcwidth(0x1f355, "SLICE OF PIZZA");
  print_wcwidth(0x1f356, "MEAT ON BONE");
  print_wcwidth(0x1f357, "POULTRY LEG");
  print_wcwidth(0x1f358, "RICE CRACKER");
  print_wcwidth(0x1f359, "RICE BALL");
  print_wcwidth(0x1f35a, "COOKED RICE");
  print_wcwidth(0x1f35b, "CURRY AND RICE");
  print_wcwidth(0x1f35c, "STEAMING BOWL");
  print_wcwidth(0x1f35d, "SPAGHETTI");
  print_wcwidth(0x1f35e, "BREAD");
  print_wcwidth(0x1f35f, "FRENCH FRIES");
  print_wcwidth(0x1f360, "ROASTED SWEET POTATO");
  print_wcwidth(0x1f361, "DANGO");
  print_wcwidth(0x1f362, "ODEN");
  print_wcwidth(0x1f363, "SUSHI");
  print_wcwidth(0x1f364, "FRIED SHRIMP");
  print_wcwidth(0x1f365, "FISH CAKE WITH SWIRL DESIGN");
  print_wcwidth(0x1f366, "SOFT ICE CREAM");
  print_wcwidth(0x1f367, "SHAVED ICE");
  print_wcwidth(0x1f368, "ICE CREAM");
  print_wcwidth(0x1f369, "DOUGHNUT");
  print_wcwidth(0x1f36a, "COOKIE");
  print_wcwidth(0x1f36b, "CHOCOLATE BAR");
  print_wcwidth(0x1f36c, "CANDY");
  print_wcwidth(0x1f36d, "LOLLIPOP");
  print_wcwidth(0x1f36e, "CUSTARD");
  print_wcwidth(0x1f36f, "HONEY POT");
  print_wcwidth(0x1f370, "SHORTCAKE");
  print_wcwidth(0x1f371, "BENTO BOX");
  print_wcwidth(0x1f372, "POT OF FOOD");
  print_wcwidth(0x1f373, "COOKING");
  print_wcwidth(0x1f374, "FORK AND KNIFE");
  print_wcwidth(0x1f375, "TEACUP WITHOUT HANDLE");
  print_wcwidth(0x1f376, "SAKE BOTTLE AND CUP");
  print_wcwidth(0x1f377, "WINE GLASS");
  print_wcwidth(0x1f378, "COCKTAIL GLASS");
  print_wcwidth(0x1f379, "TROPICAL DRINK");
  print_wcwidth(0x1f37a, "BEER MUG");
  print_wcwidth(0x1f37b, "CLINKING BEER MUGS");
  print_wcwidth(0x1f37c, "BABY BOTTLE");
  print_wcwidth(0x1f37d, "FORK AND KNIFE WITH PLATE");
  print_wcwidth(0x1f380, "RIBBON");
  print_wcwidth(0x1f381, "WRAPPED PRESENT");
  print_wcwidth(0x1f382, "BIRTHDAY CAKE");
  print_wcwidth(0x1f383, "JACK-O-LANTERN");
  print_wcwidth(0x1f384, "CHRISTMAS TREE");
  print_wcwidth(0x1f385, "FATHER CHRISTMAS");
  print_wcwidth(0x1f386, "FIREWORKS");
  print_wcwidth(0x1f387, "FIREWORK SPARKLER");
  print_wcwidth(0x1f388, "BALLOON");
  print_wcwidth(0x1f389, "PARTY POPPER");
  print_wcwidth(0x1f38a, "CONFETTI BALL");
  print_wcwidth(0x1f38b, "TANABATA TREE");
  print_wcwidth(0x1f38c, "CROSSED FLAGS");
  print_wcwidth(0x1f38d, "PINE DECORATION");
  print_wcwidth(0x1f38e, "JAPANESE DOLLS");
  print_wcwidth(0x1f38f, "CARP STREAMER");
  print_wcwidth(0x1f390, "WIND CHIME");
  print_wcwidth(0x1f391, "MOON VIEWING CEREMONY");
  print_wcwidth(0x1f392, "SCHOOL SATCHEL");
  print_wcwidth(0x1f393, "GRADUATION CAP");
  print_wcwidth(0x1f396, "MILITARY MEDAL");
  print_wcwidth(0x1f397, "REMINDER RIBBON");
  print_wcwidth(0x1f399, "STUDIO MICROPHONE");
  print_wcwidth(0x1f39a, "LEVEL SLIDER");
  print_wcwidth(0x1f39b, "CONTROL KNOBS");
  print_wcwidth(0x1f39e, "FILM FRAMES");
  print_wcwidth(0x1f39f, "ADMISSION TICKETS");
  print_wcwidth(0x1f3a0, "CAROUSEL HORSE");
  print_wcwidth(0x1f3a1, "FERRIS WHEEL");
  print_wcwidth(0x1f3a2, "ROLLER COASTER");
  print_wcwidth(0x1f3a3, "FISHING POLE AND FISH");
  print_wcwidth(0x1f3a4, "MICROPHONE");
  print_wcwidth(0x1f3a5, "MOVIE CAMERA");
  print_wcwidth(0x1f3a6, "CINEMA");
  print_wcwidth(0x1f3a7, "HEADPHONE");
  print_wcwidth(0x1f3a8, "ARTIST PALETTE");
  print_wcwidth(0x1f3a9, "TOP HAT");
  print_wcwidth(0x1f3aa, "CIRCUS TENT");
  print_wcwidth(0x1f3ab, "TICKET");
  print_wcwidth(0x1f3ac, "CLAPPER BOARD");
  print_wcwidth(0x1f3ad, "PERFORMING ARTS");
  print_wcwidth(0x1f3ae, "VIDEO GAME");
  print_wcwidth(0x1f3af, "DIRECT HIT");
  print_wcwidth(0x1f3b0, "SLOT MACHINE");
  print_wcwidth(0x1f3b1, "BILLIARDS");
  print_wcwidth(0x1f3b2, "GAME DIE");
  print_wcwidth(0x1f3b3, "BOWLING");
  print_wcwidth(0x1f3b4, "FLOWER PLAYING CARDS");
  print_wcwidth(0x1f3b5, "MUSICAL NOTE");
  print_wcwidth(0x1f3b6, "MULTIPLE MUSICAL NOTES");
  print_wcwidth(0x1f3b7, "SAXOPHONE");
  print_wcwidth(0x1f3b8, "GUITAR");
  print_wcwidth(0x1f3b9, "MUSICAL KEYBOARD");
  print_wcwidth(0x1f3ba, "TRUMPET");
  print_wcwidth(0x1f3bb, "VIOLIN");
  print_wcwidth(0x1f3bc, "MUSICAL SCORE");
  print_wcwidth(0x1f3bd, "RUNNING SHIRT WITH SASH");
  print_wcwidth(0x1f3be, "TENNIS RACQUET AND BALL");
  print_wcwidth(0x1f3bf, "SKI AND SKI BOOT");
  print_wcwidth(0x1f3c0, "BASKETBALL AND HOOP");
  print_wcwidth(0x1f3c1, "CHEQUERED FLAG");
  print_wcwidth(0x1f3c2, "SNOWBOARDER");
  print_wcwidth(0x1f3c3, "RUNNER");
  print_wcwidth(0x1f3c4, "SURFER");
  print_wcwidth(0x1f3c5, "SPORTS MEDAL");
  print_wcwidth(0x1f3c6, "TROPHY");
  print_wcwidth(0x1f3c7, "HORSE RACING");
  print_wcwidth(0x1f3c8, "AMERICAN FOOTBALL");
  print_wcwidth(0x1f3c9, "RUGBY FOOTBALL");
  print_wcwidth(0x1f3ca, "SWIMMER");
  print_wcwidth(0x1f3cb, "WEIGHT LIFTER");
  print_wcwidth(0x1f3cc, "GOLFER");
  print_wcwidth(0x1f3cd, "RACING MOTORCYCLE");
  print_wcwidth(0x1f3ce, "RACING CAR");
  print_wcwidth(0x1f3d4, "SNOW CAPPED MOUNTAIN");
  print_wcwidth(0x1f3d5, "CAMPING");
  print_wcwidth(0x1f3d6, "BEACH WITH UMBRELLA");
  print_wcwidth(0x1f3d7, "BUILDING CONSTRUCTION");
  print_wcwidth(0x1f3d8, "HOUSE BUILDINGS");
  print_wcwidth(0x1f3d9, "CITYSCAPE");
  print_wcwidth(0x1f3da, "DERELICT HOUSE BUILDING");
  print_wcwidth(0x1f3db, "CLASSICAL BUILDING");
  print_wcwidth(0x1f3dc, "DESERT");
  print_wcwidth(0x1f3dd, "DESERT ISLAND");
  print_wcwidth(0x1f3de, "NATIONAL PARK");
  print_wcwidth(0x1f3df, "STADIUM");
  print_wcwidth(0x1f3e0, "HOUSE BUILDING");
  print_wcwidth(0x1f3e1, "HOUSE WITH GARDEN");
  print_wcwidth(0x1f3e2, "OFFICE BUILDING");
  print_wcwidth(0x1f3e3, "JAPANESE POST OFFICE");
  print_wcwidth(0x1f3e4, "EUROPEAN POST OFFICE");
  print_wcwidth(0x1f3e5, "HOSPITAL");
  print_wcwidth(0x1f3e6, "BANK");
  print_wcwidth(0x1f3e7, "AUTOMATED TELLER MACHINE");
  print_wcwidth(0x1f3e8, "HOTEL");
  print_wcwidth(0x1f3e9, "LOVE HOTEL");
  print_wcwidth(0x1f3ea, "CONVENIENCE STORE");
  print_wcwidth(0x1f3eb, "SCHOOL");
  print_wcwidth(0x1f3ec, "DEPARTMENT STORE");
  print_wcwidth(0x1f3ed, "FACTORY");
  print_wcwidth(0x1f3ee, "IZAKAYA LANTERN");
  print_wcwidth(0x1f3ef, "JAPANESE CASTLE");
  print_wcwidth(0x1f3f0, "EUROPEAN CASTLE");
  print_wcwidth(0x1f3f3, "WAVING WHITE FLAG");
  print_wcwidth(0x1f3f4, "WAVING BLACK FLAG");
  print_wcwidth(0x1f3f5, "ROSETTE");
  print_wcwidth(0x1f3f7, "LABEL");
  print_wcwidth(0x1f400, "RAT");
  print_wcwidth(0x1f401, "MOUSE");
  print_wcwidth(0x1f402, "OX");
  print_wcwidth(0x1f403, "WATER BUFFALO");
  print_wcwidth(0x1f404, "COW");
  print_wcwidth(0x1f405, "TIGER");
  print_wcwidth(0x1f406, "LEOPARD");
  print_wcwidth(0x1f407, "RABBIT");
  print_wcwidth(0x1f408, "CAT");
  print_wcwidth(0x1f409, "DRAGON");
  print_wcwidth(0x1f40a, "CROCODILE");
  print_wcwidth(0x1f40b, "WHALE");
  print_wcwidth(0x1f40c, "SNAIL");
  print_wcwidth(0x1f40d, "SNAKE");
  print_wcwidth(0x1f40e, "HORSE");
  print_wcwidth(0x1f40f, "RAM");
  print_wcwidth(0x1f410, "GOAT");
  print_wcwidth(0x1f411, "SHEEP");
  print_wcwidth(0x1f412, "MONKEY");
  print_wcwidth(0x1f413, "ROOSTER");
  print_wcwidth(0x1f414, "CHICKEN");
  print_wcwidth(0x1f415, "DOG");
  print_wcwidth(0x1f416, "PIG");
  print_wcwidth(0x1f417, "BOAR");
  print_wcwidth(0x1f418, "ELEPHANT");
  print_wcwidth(0x1f419, "OCTOPUS");
  print_wcwidth(0x1f41a, "SPIRAL SHELL");
  print_wcwidth(0x1f41b, "BUG");
  print_wcwidth(0x1f41c, "ANT");
  print_wcwidth(0x1f41d, "HONEYBEE");
  print_wcwidth(0x1f41e, "LADY BEETLE");
  print_wcwidth(0x1f41f, "FISH");
  print_wcwidth(0x1f420, "TROPICAL FISH");
  print_wcwidth(0x1f421, "BLOWFISH");
  print_wcwidth(0x1f422, "TURTLE");
  print_wcwidth(0x1f423, "HATCHING CHICK");
  print_wcwidth(0x1f424, "BABY CHICK");
  print_wcwidth(0x1f425, "FRONT-FACING BABY CHICK");
  print_wcwidth(0x1f426, "BIRD");
  print_wcwidth(0x1f427, "PENGUIN");
  print_wcwidth(0x1f428, "KOALA");
  print_wcwidth(0x1f429, "POODLE");
  print_wcwidth(0x1f42a, "DROMEDARY CAMEL");
  print_wcwidth(0x1f42b, "BACTRIAN CAMEL");
  print_wcwidth(0x1f42c, "DOLPHIN");
  print_wcwidth(0x1f42d, "MOUSE FACE");
  print_wcwidth(0x1f42e, "COW FACE");
  print_wcwidth(0x1f42f, "TIGER FACE");
  print_wcwidth(0x1f430, "RABBIT FACE");
  print_wcwidth(0x1f431, "CAT FACE");
  print_wcwidth(0x1f432, "DRAGON FACE");
  print_wcwidth(0x1f433, "SPOUTING WHALE");
  print_wcwidth(0x1f434, "HORSE FACE");
  print_wcwidth(0x1f435, "MONKEY FACE");
  print_wcwidth(0x1f436, "DOG FACE");
  print_wcwidth(0x1f437, "PIG FACE");
  print_wcwidth(0x1f438, "FROG FACE");
  print_wcwidth(0x1f439, "HAMSTER FACE");
  print_wcwidth(0x1f43a, "WOLF FACE");
  print_wcwidth(0x1f43b, "BEAR FACE");
  print_wcwidth(0x1f43c, "PANDA FACE");
  print_wcwidth(0x1f43d, "PIG NOSE");
  print_wcwidth(0x1f43e, "PAW PRINTS");
  print_wcwidth(0x1f43f, "CHIPMUNK");
  print_wcwidth(0x1f440, "EYES");
  print_wcwidth(0x1f441, "EYE");
  print_wcwidth(0x1f442, "EAR");
  print_wcwidth(0x1f443, "NOSE");
  print_wcwidth(0x1f444, "MOUTH");
  print_wcwidth(0x1f445, "TONGUE");
  print_wcwidth(0x1f446, "WHITE UP POINTING BACKHAND INDEX");
  print_wcwidth(0x1f447, "WHITE DOWN POINTING BACKHAND INDEX");
  print_wcwidth(0x1f448, "WHITE LEFT POINTING BACKHAND INDEX");
  print_wcwidth(0x1f449, "WHITE RIGHT POINTING BACKHAND INDEX");
  print_wcwidth(0x1f44a, "FISTED HAND SIGN");
  print_wcwidth(0x1f44b, "WAVING HAND SIGN");
  print_wcwidth(0x1f44c, "OK HAND SIGN");
  print_wcwidth(0x1f44d, "THUMBS UP SIGN");
  print_wcwidth(0x1f44e, "THUMBS DOWN SIGN");
  print_wcwidth(0x1f44f, "CLAPPING HANDS SIGN");
  print_wcwidth(0x1f450, "OPEN HANDS SIGN");
  print_wcwidth(0x1f451, "CROWN");
  print_wcwidth(0x1f452, "WOMANS HAT");
  print_wcwidth(0x1f453, "EYEGLASSES");
  print_wcwidth(0x1f454, "NECKTIE");
  print_wcwidth(0x1f455, "T-SHIRT");
  print_wcwidth(0x1f456, "JEANS");
  print_wcwidth(0x1f457, "DRESS");
  print_wcwidth(0x1f458, "KIMONO");
  print_wcwidth(0x1f459, "BIKINI");
  print_wcwidth(0x1f45a, "WOMANS CLOTHES");
  print_wcwidth(0x1f45b, "PURSE");
  print_wcwidth(0x1f45c, "HANDBAG");
  print_wcwidth(0x1f45d, "POUCH");
  print_wcwidth(0x1f45e, "MANS SHOE");
  print_wcwidth(0x1f45f, "ATHLETIC SHOE");
  print_wcwidth(0x1f460, "HIGH-HEELED SHOE");
  print_wcwidth(0x1f461, "WOMANS SANDAL");
  print_wcwidth(0x1f462, "WOMANS BOOTS");
  print_wcwidth(0x1f463, "FOOTPRINTS");
  print_wcwidth(0x1f464, "BUST IN SILHOUETTE");
  print_wcwidth(0x1f465, "BUSTS IN SILHOUETTE");
  print_wcwidth(0x1f466, "BOY");
  print_wcwidth(0x1f467, "GIRL");
  print_wcwidth(0x1f468, "MAN");
  print_wcwidth(0x1f469, "WOMAN");
  print_wcwidth(0x1f46a, "FAMILY");
  print_wcwidth(0x1f46b, "MAN AND WOMAN HOLDING HANDS");
  print_wcwidth(0x1f46c, "TWO MEN HOLDING HANDS");
  print_wcwidth(0x1f46d, "TWO WOMEN HOLDING HANDS");
  print_wcwidth(0x1f46e, "POLICE OFFICER");
  print_wcwidth(0x1f46f, "WOMAN WITH BUNNY EARS");
  print_wcwidth(0x1f470, "BRIDE WITH VEIL");
  print_wcwidth(0x1f471, "PERSON WITH BLOND HAIR");
  print_wcwidth(0x1f472, "MAN WITH GUA PI MAO");
  print_wcwidth(0x1f473, "MAN WITH TURBAN");
  print_wcwidth(0x1f474, "OLDER MAN");
  print_wcwidth(0x1f475, "OLDER WOMAN");
  print_wcwidth(0x1f476, "BABY");
  print_wcwidth(0x1f477, "CONSTRUCTION WORKER");
  print_wcwidth(0x1f478, "PRINCESS");
  print_wcwidth(0x1f479, "JAPANESE OGRE");
  print_wcwidth(0x1f47a, "JAPANESE GOBLIN");
  print_wcwidth(0x1f47b, "GHOST");
  print_wcwidth(0x1f47c, "BABY ANGEL");
  print_wcwidth(0x1f47d, "EXTRATERRESTRIAL ALIEN");
  print_wcwidth(0x1f47e, "ALIEN MONSTER");
  print_wcwidth(0x1f47f, "IMP");
  print_wcwidth(0x1f480, "SKULL");
  print_wcwidth(0x1f481, "INFORMATION DESK PERSON");
  print_wcwidth(0x1f482, "GUARDSMAN");
  print_wcwidth(0x1f483, "DANCER");
  print_wcwidth(0x1f484, "LIPSTICK");
  print_wcwidth(0x1f485, "NAIL POLISH");
  print_wcwidth(0x1f486, "FACE MASSAGE");
  print_wcwidth(0x1f487, "HAIRCUT");
  print_wcwidth(0x1f488, "BARBER POLE");
  print_wcwidth(0x1f489, "SYRINGE");
  print_wcwidth(0x1f48a, "PILL");
  print_wcwidth(0x1f48b, "KISS MARK");
  print_wcwidth(0x1f48c, "LOVE LETTER");
  print_wcwidth(0x1f48d, "RING");
  print_wcwidth(0x1f48e, "GEM STONE");
  print_wcwidth(0x1f48f, "KISS");
  print_wcwidth(0x1f490, "BOUQUET");
  print_wcwidth(0x1f491, "COUPLE WITH HEART");
  print_wcwidth(0x1f492, "WEDDING");
  print_wcwidth(0x1f493, "BEATING HEART");
  print_wcwidth(0x1f494, "BROKEN HEART");
  print_wcwidth(0x1f495, "TWO HEARTS");
  print_wcwidth(0x1f496, "SPARKLING HEART");
  print_wcwidth(0x1f497, "GROWING HEART");
  print_wcwidth(0x1f498, "HEART WITH ARROW");
  print_wcwidth(0x1f499, "BLUE HEART");
  print_wcwidth(0x1f49a, "GREEN HEART");
  print_wcwidth(0x1f49b, "YELLOW HEART");
  print_wcwidth(0x1f49c, "PURPLE HEART");
  print_wcwidth(0x1f49d, "HEART WITH RIBBON");
  print_wcwidth(0x1f49e, "REVOLVING HEARTS");
  print_wcwidth(0x1f49f, "HEART DECORATION");
  print_wcwidth(0x1f4a0, "DIAMOND SHAPE WITH A DOT INSIDE");
  print_wcwidth(0x1f4a1, "ELECTRIC LIGHT BULB");
  print_wcwidth(0x1f4a2, "ANGER SYMBOL");
  print_wcwidth(0x1f4a3, "BOMB");
  print_wcwidth(0x1f4a4, "SLEEPING SYMBOL");
  print_wcwidth(0x1f4a5, "COLLISION SYMBOL");
  print_wcwidth(0x1f4a6, "SPLASHING SWEAT SYMBOL");
  print_wcwidth(0x1f4a7, "DROPLET");
  print_wcwidth(0x1f4a8, "DASH SYMBOL");
  print_wcwidth(0x1f4a9, "PILE OF POO");
  print_wcwidth(0x1f4aa, "FLEXED BICEPS");
  print_wcwidth(0x1f4ab, "DIZZY SYMBOL");
  print_wcwidth(0x1f4ac, "SPEECH BALLOON");
  print_wcwidth(0x1f4ad, "THOUGHT BALLOON");
  print_wcwidth(0x1f4ae, "WHITE FLOWER");
  print_wcwidth(0x1f4af, "HUNDRED POINTS SYMBOL");
  print_wcwidth(0x1f4b0, "MONEY BAG");
  print_wcwidth(0x1f4b1, "CURRENCY EXCHANGE");
  print_wcwidth(0x1f4b2, "HEAVY DOLLAR SIGN");
  print_wcwidth(0x1f4b3, "CREDIT CARD");
  print_wcwidth(0x1f4b4, "BANKNOTE WITH YEN SIGN");
  print_wcwidth(0x1f4b5, "BANKNOTE WITH DOLLAR SIGN");
  print_wcwidth(0x1f4b6, "BANKNOTE WITH EURO SIGN");
  print_wcwidth(0x1f4b7, "BANKNOTE WITH POUND SIGN");
  print_wcwidth(0x1f4b8, "MONEY WITH WINGS");
  print_wcwidth(0x1f4b9, "CHART WITH UPWARDS TREND AND YEN SIGN");
  print_wcwidth(0x1f4ba, "SEAT");
  print_wcwidth(0x1f4bb, "PERSONAL COMPUTER");
  print_wcwidth(0x1f4bc, "BRIEFCASE");
  print_wcwidth(0x1f4bd, "MINIDISC");
  print_wcwidth(0x1f4be, "FLOPPY DISK");
  print_wcwidth(0x1f4bf, "OPTICAL DISC");
  print_wcwidth(0x1f4c0, "DVD");
  print_wcwidth(0x1f4c1, "FILE FOLDER");
  print_wcwidth(0x1f4c2, "OPEN FILE FOLDER");
  print_wcwidth(0x1f4c3, "PAGE WITH CURL");
  print_wcwidth(0x1f4c4, "PAGE FACING UP");
  print_wcwidth(0x1f4c5, "CALENDAR");
  print_wcwidth(0x1f4c6, "TEAR-OFF CALENDAR");
  print_wcwidth(0x1f4c7, "CARD INDEX");
  print_wcwidth(0x1f4c8, "CHART WITH UPWARDS TREND");
  print_wcwidth(0x1f4c9, "CHART WITH DOWNWARDS TREND");
  print_wcwidth(0x1f4ca, "BAR CHART");
  print_wcwidth(0x1f4cb, "CLIPBOARD");
  print_wcwidth(0x1f4cc, "PUSHPIN");
  print_wcwidth(0x1f4cd, "ROUND PUSHPIN");
  print_wcwidth(0x1f4ce, "PAPERCLIP");
  print_wcwidth(0x1f4cf, "STRAIGHT RULER");
  print_wcwidth(0x1f4d0, "TRIANGULAR RULER");
  print_wcwidth(0x1f4d1, "BOOKMARK TABS");
  print_wcwidth(0x1f4d2, "LEDGER");
  print_wcwidth(0x1f4d3, "NOTEBOOK");
  print_wcwidth(0x1f4d4, "NOTEBOOK WITH DECORATIVE COVER");
  print_wcwidth(0x1f4d5, "CLOSED BOOK");
  print_wcwidth(0x1f4d6, "OPEN BOOK");
  print_wcwidth(0x1f4d7, "GREEN BOOK");
  print_wcwidth(0x1f4d8, "BLUE BOOK");
  print_wcwidth(0x1f4d9, "ORANGE BOOK");
  print_wcwidth(0x1f4da, "BOOKS");
  print_wcwidth(0x1f4db, "NAME BADGE");
  print_wcwidth(0x1f4dc, "SCROLL");
  print_wcwidth(0x1f4dd, "MEMO");
  print_wcwidth(0x1f4de, "TELEPHONE RECEIVER");
  print_wcwidth(0x1f4df, "PAGER");
  print_wcwidth(0x1f4e0, "FAX MACHINE");
  print_wcwidth(0x1f4e1, "SATELLITE ANTENNA");
  print_wcwidth(0x1f4e2, "PUBLIC ADDRESS LOUDSPEAKER");
  print_wcwidth(0x1f4e3, "CHEERING MEGAPHONE");
  print_wcwidth(0x1f4e4, "OUTBOX TRAY");
  print_wcwidth(0x1f4e5, "INBOX TRAY");
  print_wcwidth(0x1f4e6, "PACKAGE");
  print_wcwidth(0x1f4e7, "E-MAIL SYMBOL");
  print_wcwidth(0x1f4e8, "INCOMING ENVELOPE");
  print_wcwidth(0x1f4e9, "ENVELOPE WITH DOWNWARDS ARROW ABOVE");
  print_wcwidth(0x1f4ea, "CLOSED MAILBOX WITH LOWERED FLAG");
  print_wcwidth(0x1f4eb, "CLOSED MAILBOX WITH RAISED FLAG");
  print_wcwidth(0x1f4ec, "OPEN MAILBOX WITH RAISED FLAG");
  print_wcwidth(0x1f4ed, "OPEN MAILBOX WITH LOWERED FLAG");
  print_wcwidth(0x1f4ee, "POSTBOX");
  print_wcwidth(0x1f4ef, "POSTAL HORN");
  print_wcwidth(0x1f4f0, "NEWSPAPER");
  print_wcwidth(0x1f4f1, "MOBILE PHONE");
  print_wcwidth(0x1f4f2, "MOBILE PHONE WITH RIGHTWARDS ARROW AT LEFT");
  print_wcwidth(0x1f4f3, "VIBRATION MODE");
  print_wcwidth(0x1f4f4, "MOBILE PHONE OFF");
  print_wcwidth(0x1f4f5, "NO MOBILE PHONES");
  print_wcwidth(0x1f4f6, "ANTENNA WITH BARS");
  print_wcwidth(0x1f4f7, "CAMERA");
  print_wcwidth(0x1f4f8, "CAMERA WITH FLASH");
  print_wcwidth(0x1f4f9, "VIDEO CAMERA");
  print_wcwidth(0x1f4fa, "TELEVISION");
  print_wcwidth(0x1f4fb, "RADIO");
  print_wcwidth(0x1f4fc, "VIDEOCASSETTE");
  print_wcwidth(0x1f4fd, "FILM PROJECTOR");
  print_wcwidth(0x1f500, "TWISTED RIGHTWARDS ARROWS");
  print_wcwidth(0x1f501, "CLOCKWISE RIGHTWARDS AND LEFTWARDS OPEN CIRCLE ARROWS");
  print_wcwidth(0x1f502, "CLOCKWISE RIGHTWARDS AND LEFTWARDS OPEN CIRCLE ARROWS WITH CIRCLED ONE OVERLAY");
  print_wcwidth(0x1f503, "CLOCKWISE DOWNWARDS AND UPWARDS OPEN CIRCLE ARROWS");
  print_wcwidth(0x1f504, "ANTICLOCKWISE DOWNWARDS AND UPWARDS OPEN CIRCLE ARROWS");
  print_wcwidth(0x1f505, "LOW BRIGHTNESS SYMBOL");
  print_wcwidth(0x1f506, "HIGH BRIGHTNESS SYMBOL");
  print_wcwidth(0x1f507, "SPEAKER WITH CANCELLATION STROKE");
  print_wcwidth(0x1f508, "SPEAKER");
  print_wcwidth(0x1f509, "SPEAKER WITH ONE SOUND WAVE");
  print_wcwidth(0x1f50a, "SPEAKER WITH THREE SOUND WAVES");
  print_wcwidth(0x1f50b, "BATTERY");
  print_wcwidth(0x1f50c, "ELECTRIC PLUG");
  print_wcwidth(0x1f50d, "LEFT-POINTING MAGNIFYING GLASS");
  print_wcwidth(0x1f50e, "RIGHT-POINTING MAGNIFYING GLASS");
  print_wcwidth(0x1f50f, "LOCK WITH INK PEN");
  print_wcwidth(0x1f510, "CLOSED LOCK WITH KEY");
  print_wcwidth(0x1f511, "KEY");
  print_wcwidth(0x1f512, "LOCK");
  print_wcwidth(0x1f513, "OPEN LOCK");
  print_wcwidth(0x1f514, "BELL");
  print_wcwidth(0x1f515, "BELL WITH CANCELLATION STROKE");
  print_wcwidth(0x1f516, "BOOKMARK");
  print_wcwidth(0x1f517, "LINK SYMBOL");
  print_wcwidth(0x1f518, "RADIO BUTTON");
  print_wcwidth(0x1f519, "BACK WITH LEFTWARDS ARROW ABOVE");
  print_wcwidth(0x1f51a, "END WITH LEFTWARDS ARROW ABOVE");
  print_wcwidth(0x1f51b, "ON WITH EXCLAMATION MARK WITH LEFT RIGHT ARROW ABOVE");
  print_wcwidth(0x1f51c, "SOON WITH RIGHTWARDS ARROW ABOVE");
  print_wcwidth(0x1f51d, "TOP WITH UPWARDS ARROW ABOVE");
  print_wcwidth(0x1f51e, "NO ONE UNDER EIGHTEEN SYMBOL");
  print_wcwidth(0x1f51f, "KEYCAP TEN");
  print_wcwidth(0x1f520, "INPUT SYMBOL FOR LATIN CAPITAL LETTERS");
  print_wcwidth(0x1f521, "INPUT SYMBOL FOR LATIN SMALL LETTERS");
  print_wcwidth(0x1f522, "INPUT SYMBOL FOR NUMBERS");
  print_wcwidth(0x1f523, "INPUT SYMBOL FOR SYMBOLS");
  print_wcwidth(0x1f524, "INPUT SYMBOL FOR LATIN LETTERS");
  print_wcwidth(0x1f525, "FIRE");
  print_wcwidth(0x1f526, "ELECTRIC TORCH");
  print_wcwidth(0x1f527, "WRENCH");
  print_wcwidth(0x1f528, "HAMMER");
  print_wcwidth(0x1f529, "NUT AND BOLT");
  print_wcwidth(0x1f52a, "HOCHO");
  print_wcwidth(0x1f52b, "PISTOL");
  print_wcwidth(0x1f52c, "MICROSCOPE");
  print_wcwidth(0x1f52d, "TELESCOPE");
  print_wcwidth(0x1f52e, "CRYSTAL BALL");
  print_wcwidth(0x1f52f, "SIX POINTED STAR WITH MIDDLE DOT");
  print_wcwidth(0x1f530, "JAPANESE SYMBOL FOR BEGINNER");
  print_wcwidth(0x1f531, "TRIDENT EMBLEM");
  print_wcwidth(0x1f532, "BLACK SQUARE BUTTON");
  print_wcwidth(0x1f533, "WHITE SQUARE BUTTON");
  print_wcwidth(0x1f534, "LARGE RED CIRCLE");
  print_wcwidth(0x1f535, "LARGE BLUE CIRCLE");
  print_wcwidth(0x1f536, "LARGE ORANGE DIAMOND");
  print_wcwidth(0x1f537, "LARGE BLUE DIAMOND");
  print_wcwidth(0x1f538, "SMALL ORANGE DIAMOND");
  print_wcwidth(0x1f539, "SMALL BLUE DIAMOND");
  print_wcwidth(0x1f53a, "UP-POINTING RED TRIANGLE");
  print_wcwidth(0x1f53b, "DOWN-POINTING RED TRIANGLE");
  print_wcwidth(0x1f53c, "UP-POINTING SMALL RED TRIANGLE");
  print_wcwidth(0x1f53d, "DOWN-POINTING SMALL RED TRIANGLE");
  print_wcwidth(0x1f549, "OM SYMBOL");
  print_wcwidth(0x1f54a, "DOVE OF PEACE");
  print_wcwidth(0x1f550, "CLOCK FACE ONE OCLOCK");
  print_wcwidth(0x1f551, "CLOCK FACE TWO OCLOCK");
  print_wcwidth(0x1f552, "CLOCK FACE THREE OCLOCK");
  print_wcwidth(0x1f553, "CLOCK FACE FOUR OCLOCK");
  print_wcwidth(0x1f554, "CLOCK FACE FIVE OCLOCK");
  print_wcwidth(0x1f555, "CLOCK FACE SIX OCLOCK");
  print_wcwidth(0x1f556, "CLOCK FACE SEVEN OCLOCK");
  print_wcwidth(0x1f557, "CLOCK FACE EIGHT OCLOCK");
  print_wcwidth(0x1f558, "CLOCK FACE NINE OCLOCK");
  print_wcwidth(0x1f559, "CLOCK FACE TEN OCLOCK");
  print_wcwidth(0x1f55a, "CLOCK FACE ELEVEN OCLOCK");
  print_wcwidth(0x1f55b, "CLOCK FACE TWELVE OCLOCK");
  print_wcwidth(0x1f55c, "CLOCK FACE ONE-THIRTY");
  print_wcwidth(0x1f55d, "CLOCK FACE TWO-THIRTY");
  print_wcwidth(0x1f55e, "CLOCK FACE THREE-THIRTY");
  print_wcwidth(0x1f55f, "CLOCK FACE FOUR-THIRTY");
  print_wcwidth(0x1f560, "CLOCK FACE FIVE-THIRTY");
  print_wcwidth(0x1f561, "CLOCK FACE SIX-THIRTY");
  print_wcwidth(0x1f562, "CLOCK FACE SEVEN-THIRTY");
  print_wcwidth(0x1f563, "CLOCK FACE EIGHT-THIRTY");
  print_wcwidth(0x1f564, "CLOCK FACE NINE-THIRTY");
  print_wcwidth(0x1f565, "CLOCK FACE TEN-THIRTY");
  print_wcwidth(0x1f566, "CLOCK FACE ELEVEN-THIRTY");
  print_wcwidth(0x1f567, "CLOCK FACE TWELVE-THIRTY");
  print_wcwidth(0x1f56f, "CANDLE");
  print_wcwidth(0x1f570, "MANTELPIECE CLOCK");
  print_wcwidth(0x1f573, "HOLE");
  print_wcwidth(0x1f574, "MAN IN BUSINESS SUIT LEVITATING");
  print_wcwidth(0x1f575, "SLEUTH OR SPY");
  print_wcwidth(0x1f576, "DARK SUNGLASSES");
  print_wcwidth(0x1f577, "SPIDER");
  print_wcwidth(0x1f578, "SPIDER WEB");
  print_wcwidth(0x1f579, "JOYSTICK");
  print_wcwidth(0x1f587, "LINKED PAPERCLIPS");
  print_wcwidth(0x1f58a, "LOWER LEFT BALLPOINT PEN");
  print_wcwidth(0x1f58b, "LOWER LEFT FOUNTAIN PEN");
  print_wcwidth(0x1f58c, "LOWER LEFT PAINTBRUSH");
  print_wcwidth(0x1f58d, "LOWER LEFT CRAYON");
  print_wcwidth(0x1f590, "RAISED HAND WITH FINGERS SPLAYED");
  print_wcwidth(0x1f595, "REVERSED HAND WITH MIDDLE FINGER EXTENDED");
  print_wcwidth(0x1f596, "RAISED HAND WITH PART BETWEEN MIDDLE AND RING FINGERS");
  print_wcwidth(0x1f5a5, "DESKTOP COMPUTER");
  print_wcwidth(0x1f5a8, "PRINTER");
  print_wcwidth(0x1f5b1, "THREE BUTTON MOUSE");
  print_wcwidth(0x1f5b2, "TRACKBALL");
  print_wcwidth(0x1f5bc, "FRAME WITH PICTURE");
  print_wcwidth(0x1f5c2, "CARD INDEX DIVIDERS");
  print_wcwidth(0x1f5c3, "CARD FILE BOX");
  print_wcwidth(0x1f5c4, "FILE CABINET");
  print_wcwidth(0x1f5d1, "WASTEBASKET");
  print_wcwidth(0x1f5d2, "SPIRAL NOTE PAD");
  print_wcwidth(0x1f5d3, "SPIRAL CALENDAR PAD");
  print_wcwidth(0x1f5dc, "COMPRESSION");
  print_wcwidth(0x1f5dd, "OLD KEY");
  print_wcwidth(0x1f5de, "ROLLED-UP NEWSPAPER");
  print_wcwidth(0x1f5e1, "DAGGER KNIFE");
  print_wcwidth(0x1f5e3, "SPEAKING HEAD IN SILHOUETTE");
  print_wcwidth(0x1f5ef, "RIGHT ANGER BUBBLE");
  print_wcwidth(0x1f5f3, "BALLOT BOX WITH BALLOT");
  print_wcwidth(0x1f5fa, "WORLD MAP");
  print_wcwidth(0x1f5fb, "MOUNT FUJI");
  print_wcwidth(0x1f5fc, "TOKYO TOWER");
  print_wcwidth(0x1f5fd, "STATUE OF LIBERTY");
  print_wcwidth(0x1f5fe, "SILHOUETTE OF JAPAN");
  print_wcwidth(0x1f5ff, "MOYAI");
  print_wcwidth(0x1f600, "GRINNING FACE");
  print_wcwidth(0x1f601, "GRINNING FACE WITH SMILING EYES");
  print_wcwidth(0x1f602, "FACE WITH TEARS OF JOY");
  print_wcwidth(0x1f603, "SMILING FACE WITH OPEN MOUTH");
  print_wcwidth(0x1f604, "SMILING FACE WITH OPEN MOUTH AND SMILING EYES");
  print_wcwidth(0x1f605, "SMILING FACE WITH OPEN MOUTH AND COLD SWEAT");
  print_wcwidth(0x1f606, "SMILING FACE WITH OPEN MOUTH AND TIGHTLY-CLOSED EYES");
  print_wcwidth(0x1f607, "SMILING FACE WITH HALO");
  print_wcwidth(0x1f608, "SMILING FACE WITH HORNS");
  print_wcwidth(0x1f609, "WINKING FACE");
  print_wcwidth(0x1f60a, "SMILING FACE WITH SMILING EYES");
  print_wcwidth(0x1f60b, "FACE SAVOURING DELICIOUS FOOD");
  print_wcwidth(0x1f60c, "RELIEVED FACE");
  print_wcwidth(0x1f60d, "SMILING FACE WITH HEART-SHAPED EYES");
  print_wcwidth(0x1f60e, "SMILING FACE WITH SUNGLASSES");
  print_wcwidth(0x1f60f, "SMIRKING FACE");
  print_wcwidth(0x1f610, "NEUTRAL FACE");
  print_wcwidth(0x1f611, "EXPRESSIONLESS FACE");
  print_wcwidth(0x1f612, "UNAMUSED FACE");
  print_wcwidth(0x1f613, "FACE WITH COLD SWEAT");
  print_wcwidth(0x1f614, "PENSIVE FACE");
  print_wcwidth(0x1f615, "CONFUSED FACE");
  print_wcwidth(0x1f616, "CONFOUNDED FACE");
  print_wcwidth(0x1f617, "KISSING FACE");
  print_wcwidth(0x1f618, "FACE THROWING A KISS");
  print_wcwidth(0x1f619, "KISSING FACE WITH SMILING EYES");
  print_wcwidth(0x1f61a, "KISSING FACE WITH CLOSED EYES");
  print_wcwidth(0x1f61b, "FACE WITH STUCK-OUT TONGUE");
  print_wcwidth(0x1f61c, "FACE WITH STUCK-OUT TONGUE AND WINKING EYE");
  print_wcwidth(0x1f61d, "FACE WITH STUCK-OUT TONGUE AND TIGHTLY-CLOSED EYES");
  print_wcwidth(0x1f61e, "DISAPPOINTED FACE");
  print_wcwidth(0x1f61f, "WORRIED FACE");
  print_wcwidth(0x1f620, "ANGRY FACE");
  print_wcwidth(0x1f621, "POUTING FACE");
  print_wcwidth(0x1f622, "CRYING FACE");
  print_wcwidth(0x1f623, "PERSEVERING FACE");
  print_wcwidth(0x1f624, "FACE WITH LOOK OF TRIUMPH");
  print_wcwidth(0x1f625, "DISAPPOINTED BUT RELIEVED FACE");
  print_wcwidth(0x1f626, "FROWNING FACE WITH OPEN MOUTH");
  print_wcwidth(0x1f627, "ANGUISHED FACE");
  print_wcwidth(0x1f628, "FEARFUL FACE");
  print_wcwidth(0x1f629, "WEARY FACE");
  print_wcwidth(0x1f62a, "SLEEPY FACE");
  print_wcwidth(0x1f62b, "TIRED FACE");
  print_wcwidth(0x1f62c, "GRIMACING FACE");
  print_wcwidth(0x1f62d, "LOUDLY CRYING FACE");
  print_wcwidth(0x1f62e, "FACE WITH OPEN MOUTH");
  print_wcwidth(0x1f62f, "HUSHED FACE");
  print_wcwidth(0x1f630, "FACE WITH OPEN MOUTH AND COLD SWEAT");
  print_wcwidth(0x1f631, "FACE SCREAMING IN FEAR");
  print_wcwidth(0x1f632, "ASTONISHED FACE");
  print_wcwidth(0x1f633, "FLUSHED FACE");
  print_wcwidth(0x1f634, "SLEEPING FACE");
  print_wcwidth(0x1f635, "DIZZY FACE");
  print_wcwidth(0x1f636, "FACE WITHOUT MOUTH");
  print_wcwidth(0x1f637, "FACE WITH MEDICAL MASK");
  print_wcwidth(0x1f638, "GRINNING CAT FACE WITH SMILING EYES");
  print_wcwidth(0x1f639, "CAT FACE WITH TEARS OF JOY");
  print_wcwidth(0x1f63a, "SMILING CAT FACE WITH OPEN MOUTH");
  print_wcwidth(0x1f63b, "SMILING CAT FACE WITH HEART-SHAPED EYES");
  print_wcwidth(0x1f63c, "CAT FACE WITH WRY SMILE");
  print_wcwidth(0x1f63d, "KISSING CAT FACE WITH CLOSED EYES");
  print_wcwidth(0x1f63e, "POUTING CAT FACE");
  print_wcwidth(0x1f63f, "CRYING CAT FACE");
  print_wcwidth(0x1f640, "WEARY CAT FACE");
  print_wcwidth(0x1f641, "SLIGHTLY FROWNING FACE");
  print_wcwidth(0x1f642, "SLIGHTLY SMILING FACE");
  print_wcwidth(0x1f645, "FACE WITH NO GOOD GESTURE");
  print_wcwidth(0x1f646, "FACE WITH OK GESTURE");
  print_wcwidth(0x1f647, "PERSON BOWING DEEPLY");
  print_wcwidth(0x1f648, "SEE-NO-EVIL MONKEY");
  print_wcwidth(0x1f649, "HEAR-NO-EVIL MONKEY");
  print_wcwidth(0x1f64a, "SPEAK-NO-EVIL MONKEY");
  print_wcwidth(0x1f64b, "HAPPY PERSON RAISING ONE HAND");
  print_wcwidth(0x1f64c, "PERSON RAISING BOTH HANDS IN CELEBRATION");
  print_wcwidth(0x1f64d, "PERSON FROWNING");
  print_wcwidth(0x1f64e, "PERSON WITH POUTING FACE");
  print_wcwidth(0x1f64f, "PERSON WITH FOLDED HANDS");
  print_wcwidth(0x1f680, "ROCKET");
  print_wcwidth(0x1f681, "HELICOPTER");
  print_wcwidth(0x1f682, "STEAM LOCOMOTIVE");
  print_wcwidth(0x1f683, "RAILWAY CAR");
  print_wcwidth(0x1f684, "HIGH-SPEED TRAIN");
  print_wcwidth(0x1f685, "HIGH-SPEED TRAIN WITH BULLET NOSE");
  print_wcwidth(0x1f686, "TRAIN");
  print_wcwidth(0x1f687, "METRO");
  print_wcwidth(0x1f688, "LIGHT RAIL");
  print_wcwidth(0x1f689, "STATION");
  print_wcwidth(0x1f68a, "TRAM");
  print_wcwidth(0x1f68b, "TRAM CAR");
  print_wcwidth(0x1f68c, "BUS");
  print_wcwidth(0x1f68d, "ONCOMING BUS");
  print_wcwidth(0x1f68e, "TROLLEYBUS");
  print_wcwidth(0x1f68f, "BUS STOP");
  print_wcwidth(0x1f690, "MINIBUS");
  print_wcwidth(0x1f691, "AMBULANCE");
  print_wcwidth(0x1f692, "FIRE ENGINE");
  print_wcwidth(0x1f693, "POLICE CAR");
  print_wcwidth(0x1f694, "ONCOMING POLICE CAR");
  print_wcwidth(0x1f695, "TAXI");
  print_wcwidth(0x1f696, "ONCOMING TAXI");
  print_wcwidth(0x1f697, "AUTOMOBILE");
  print_wcwidth(0x1f698, "ONCOMING AUTOMOBILE");
  print_wcwidth(0x1f699, "RECREATIONAL VEHICLE");
  print_wcwidth(0x1f69a, "DELIVERY TRUCK");
  print_wcwidth(0x1f69b, "ARTICULATED LORRY");
  print_wcwidth(0x1f69c, "TRACTOR");
  print_wcwidth(0x1f69d, "MONORAIL");
  print_wcwidth(0x1f69e, "MOUNTAIN RAILWAY");
  print_wcwidth(0x1f69f, "SUSPENSION RAILWAY");
  print_wcwidth(0x1f6a0, "MOUNTAIN CABLEWAY");
  print_wcwidth(0x1f6a1, "AERIAL TRAMWAY");
  print_wcwidth(0x1f6a2, "SHIP");
  print_wcwidth(0x1f6a3, "ROWBOAT");
  print_wcwidth(0x1f6a4, "SPEEDBOAT");
  print_wcwidth(0x1f6a5, "HORIZONTAL TRAFFIC LIGHT");
  print_wcwidth(0x1f6a6, "VERTICAL TRAFFIC LIGHT");
  print_wcwidth(0x1f6a7, "CONSTRUCTION SIGN");
  print_wcwidth(0x1f6a8, "POLICE CARS REVOLVING LIGHT");
  print_wcwidth(0x1f6a9, "TRIANGULAR FLAG ON POST");
  print_wcwidth(0x1f6aa, "DOOR");
  print_wcwidth(0x1f6ab, "NO ENTRY SIGN");
  print_wcwidth(0x1f6ac, "SMOKING SYMBOL");
  print_wcwidth(0x1f6ad, "NO SMOKING SYMBOL");
  print_wcwidth(0x1f6ae, "PUT LITTER IN ITS PLACE SYMBOL");
  print_wcwidth(0x1f6af, "DO NOT LITTER SYMBOL");
  print_wcwidth(0x1f6b0, "POTABLE WATER SYMBOL");
  print_wcwidth(0x1f6b1, "NON-POTABLE WATER SYMBOL");
  print_wcwidth(0x1f6b2, "BICYCLE");
  print_wcwidth(0x1f6b3, "NO BICYCLES");
  print_wcwidth(0x1f6b4, "BICYCLIST");
  print_wcwidth(0x1f6b5, "MOUNTAIN BICYCLIST");
  print_wcwidth(0x1f6b6, "PEDESTRIAN");
  print_wcwidth(0x1f6b7, "NO PEDESTRIANS");
  print_wcwidth(0x1f6b8, "CHILDREN CROSSING");
  print_wcwidth(0x1f6b9, "MENS SYMBOL");
  print_wcwidth(0x1f6ba, "WOMENS SYMBOL");
  print_wcwidth(0x1f6bb, "RESTROOM");
  print_wcwidth(0x1f6bc, "BABY SYMBOL");
  print_wcwidth(0x1f6bd, "TOILET");
  print_wcwidth(0x1f6be, "WATER CLOSET");
  print_wcwidth(0x1f6bf, "SHOWER");
  print_wcwidth(0x1f6c0, "BATH");
  print_wcwidth(0x1f6c1, "BATHTUB");
  print_wcwidth(0x1f6c2, "PASSPORT CONTROL");
  print_wcwidth(0x1f6c3, "CUSTOMS");
  print_wcwidth(0x1f6c4, "BAGGAGE CLAIM");
  print_wcwidth(0x1f6c5, "LEFT LUGGAGE");
  print_wcwidth(0x1f6cb, "COUCH AND LAMP");
  print_wcwidth(0x1f6cc, "SLEEPING ACCOMMODATION");
  print_wcwidth(0x1f6cd, "SHOPPING BAGS");
  print_wcwidth(0x1f6ce, "BELLHOP BELL");
  print_wcwidth(0x1f6cf, "BED");
  print_wcwidth(0x1f6e0, "HAMMER AND WRENCH");
  print_wcwidth(0x1f6e1, "SHIELD");
  print_wcwidth(0x1f6e2, "OIL DRUM");
  print_wcwidth(0x1f6e3, "MOTORWAY");
  print_wcwidth(0x1f6e4, "RAILWAY TRACK");
  print_wcwidth(0x1f6e5, "MOTOR BOAT");
  print_wcwidth(0x1f6e9, "SMALL AIRPLANE");
  print_wcwidth(0x1f6eb, "AIRPLANE DEPARTURE");
  print_wcwidth(0x1f6ec, "AIRPLANE ARRIVING");
  print_wcwidth(0x1f6f0, "SATELLITE");
  print_wcwidth(0x1f6f3, "PASSENGER SHIP");
  return 0;
}
